# -*- coding: utf-8 -*-
# Sources:
#   ids 1-20  "אנטומיה ב' - שאלות אמריקאיות לתרגול - 97509.pdf" (answer key included)
#   ids 21-23 "אנטומיה ב' - שאלות חזרה ותרגול - 97508.pdf" — the multiple-choice
#             questions on p.6. That document ships no answer key, so those
#             three answers are derived from standard anatomy, not transcribed.
#   ids 24-65 Kahoot "אנטומיה ב' - רפואה משלימה" by tzafiravivlevy, read from
#             Kahoot's public REST API, so the correct answers are the course
#             author's own. Text is verbatim apart from three normalisations:
#             HTML entities unescaped, whitespace collapsed, and a leading
#             "?"/":" moved to the end (28 of the 43 stems stored it first,
#             having been typed in a right-to-left field). The author's joke
#             final question was dropped as it is not anatomy.
#   ids 66-73 Kahoot "שרירים - רפואת הספורט למדריכים" by the same author, same
#             API source and same normalisations. Two of its ten questions ask
#             about an attached picture hosted on Kahoot with no licence
#             information; they were left out rather than commit an unlicensed
#             image, since without it they cannot be answered.
QUESTIONS = [
    {
        "id": 1,
        "question": "לאיזה מהשרירים הבאים Origin או Insertion ב- Greater Trochanter?",
        "options": ["Iliopsoas", "Gluteus Medius", "Hamstrings", "Gluteus Maximuse"],
        "answer": 1,
        "anatomy_components": ["Gluteus Maximus", "Gluteus Medius", "Greater Trochanter", "Hamstrings", "Iliopsoas"],
    },
    {
        "id": 2,
        "question": "מי מהשרירים הבאים מבצעים את אותן הפעולות",
        "options": [
            "Latissimuse Dorsi + Anterior Deltoid",
            "Tibialis Anterior + Tibialis Posterior",
            "Periformis + Obturator Internus",
            "Quadriceps + Semimembranosus",
        ],
        "answer": 2,
        "anatomy_components": [
            "Anterior Deltoid",
            "Latissimus Dorsi",
            "Obturator Internus",
            "Piriformis",
            "Quadriceps",
            "Semimembranosus",
            "Tibialis Anterior",
            "Tibialis Posterior",
        ],
    },
    {
        "id": 3,
        "question": "איזה שריר מהבאים מתחבר אל Coracoid process?",
        "options": ["Coracobrachialis", "Brachialis", "Triceps", "Supraspinatus"],
        "answer": 0,
        "anatomy_components": ["Brachialis", "Coracobrachialis", "Coracoid Process", "Supraspinatus", "Triceps"],
    },
    {
        "id": 4,
        "question": "מפרק הקרסול הוא מפרק מסוג",
        "options": ["Ball & Socket", "Hinge", "Ellipsoid", "Sutur"],
        "answer": 1,
        "anatomy_components": ["Ankle Joint"],
    },
    {
        "id": 5,
        "question": "מי מהבאים מתחבר עם עצם ה- Femur?",
        "options": ["Tibia", "Patella", "Acetabulum", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Acetabulum", "Femur", "Patella", "Tibia"],
    },
    {
        "id": 6,
        "question": "לאיזה מהשרירים הבאים יש נקודת אחיזה זהה?",
        "options": [
            "Trapezius + Deltoid",
            "Pectoralis major + Pectoralis minor",
            "Latissimus dorsi + Deltoid",
            "Supraspinatus + Subscapularis",
        ],
        "answer": 0,
        "anatomy_components": [
            "Deltoid",
            "Latissimus Dorsi",
            "Pectoralis Major",
            "Pectoralis Minor",
            "Subscapularis",
            "Supraspinatus",
            "Trapezius",
        ],
    },
    {
        "id": 7,
        "question": "מי מהשרירים הבאים מסוגל להניע את Phalang 1?",
        "options": [
            "Extensor Indicis",
            "Flexor Digitorum Longus",
            "Brachioradialis",
            "Flexor Pollicis Longus",
        ],
        "answer": 3,
        "anatomy_components": [
            "Brachioradialis",
            "Extensor Indicis",
            "Flexor Digitorum Longus",
            "Flexor Pollicis Longus",
            "Phalang 1",
        ],
    },
    {
        "id": 8,
        "question": "מי מהבאים אינו שייך למייצבי הכתף",
        "options": ["Supraspinatus", "Serratus Anterior", "Subscapularis", "Teres Minor"],
        "answer": 1,
        "anatomy_components": ["Serratus Anterior", "Subscapularis", "Supraspinatus", "Teres Minor"],
    },
    {
        "id": 9,
        "question": "מי מהבאים מונע עודף תנועה במישור הסגיטלי?",
        "options": ["M.C.L", "P.C.L", "L.C.L", "Annular Ligament"],
        "answer": 1,
        "anatomy_components": ["Annular Ligament", "LCL", "MCL", "PCL"],
    },
    {
        "id": 10,
        "question": "מי מהבאים שייך למפרקי חגורת הכתפיים",
        "options": [
            "Patello femoral joint",
            "Radio ulnar joint",
            "Acromio clavicular joint",
            "Radio carpal joint",
        ],
        "answer": 2,
        "anatomy_components": [
            "Acromioclavicular Joint",
            "Patellofemoral Joint",
            "Radiocarpal Joint",
            "Radioulnar Joint",
        ],
    },
    {
        "id": 11,
        "question": "תנועת ה-Inversion מתבצעת במפרק",
        "options": ["Subtalar Joint", "P.I.P", "D.I.P", "Hip Joint"],
        "answer": 0,
        "anatomy_components": ["DIP Joint", "Hip Joint", "PIP Joint", "Subtalar Joint"],
    },
    {
        "id": 12,
        "question": "באיזה מישור מסוגל לעבוד ה-Middle Deltoid?",
        "options": ["סגיטלי", "פרונטלי", "הוריזונטלי", "טרנסברסלי"],
        "answer": 1,
        "anatomy_components": ["Deltoid"],
    },
    {
        "id": 13,
        "question": "במפרק Proximal Radioulnar Joint מתקיימת תנועה –",
        "options": ["Flexion", "Extension", "Diviation", "Pronation"],
        "answer": 3,
        "anatomy_components": ["Proximal Radioulnar Joint"],
    },
    {
        "id": 14,
        "question": "ברוטציה של הגב שמאלה יעבדו השרירים",
        "options": [
            "Right External Obliqe + Left Internal Obliqe",
            "Left External Obliqe + Right Internal Obliqe",
            "Left External Obliqe + Left Internal Obliqe",
            "Right External Obliqe + Right Internal Obliqe",
        ],
        "answer": 0,
        "anatomy_components": ["External Oblique", "Internal Oblique"],
    },
    {
        "id": 15,
        "question": "שריר המסתיים בעצם ה-Radius מסוגל לבצע -",
        "options": ["Extension", "Elevation", "Supination", "Abduction"],
        "answer": 2,
        "anatomy_components": ["Radius"],
    },
    {
        "id": 16,
        "question": "מי מהבאים הם אגוניסט אנטגוניסט אחד לשני?",
        "options": [
            "Biceps Brachii + Brachialis",
            "Serratus Anterior + Rhomboid",
            "Deltoid + Supraspinatus",
            "Semimembranosus + Semitendinosus",
        ],
        "answer": 1,
        "anatomy_components": [
            "Biceps Brachii",
            "Brachialis",
            "Deltoid",
            "Rhomboid",
            "Semimembranosus",
            "Semitendinosus",
            "Serratus Anterior",
            "Supraspinatus",
        ],
    },
    {
        "id": 17,
        "question": "מפרק Sterno-clavicular Joint הוא מפרק מסוג:",
        "options": ["Saddle", "Ellipsoid", "Ball & Socket", "Gliding"],
        "answer": 0,
        "anatomy_components": ["Sternoclavicular Joint"],
    },
    {
        "id": 18,
        "question": "מי מהבאים מבצע P.P.T?",
        "options": ["Rectus Abdominis", "Gluteus Maximuse", "External Obliqe", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["External Oblique", "Gluteus Maximus", "Rectus Abdominis"],
    },
    {
        "id": 19,
        "question": "מי מהבאים הוא מפרק מסוג Pivot?",
        "options": [
            "C1-C2",
            "Proximal Tibiofibular Joint",
            "Atlanto Occipital Joint",
            "Tibiofemoral Joint",
        ],
        "answer": 0,
        "anatomy_components": [
            "Atlanto-Occipital Joint",
            "C1-C2 Joint",
            "Proximal Tibiofibular Joint",
            "Tibiofemoral Joint",
        ],
    },
    {
        "id": 20,
        "question": "מי מהבאים אחראי על Upward Rotation?",
        "options": ["Posterior Deltoid", "Teres Major", "Teres Minor", "Serratus Anterior"],
        "answer": 3,
        "anatomy_components": ["Posterior Deltoid", "Serratus Anterior", "Teres Major", "Teres Minor"],
    },
    {
        "id": 21,
        "question": "מי מהשרירים הבאים מניע את האגודל?",
        "options": [
            "Flexor Indicis",
            "Extensor Digitorum",
            "Abductor Pollicis Brevis",
            "Flexor Carpi Ulnaris",
        ],
        "answer": 2,
        # "Flexor Indicis" is not a real named muscle, so it gets no page.
        "anatomy_components": ["Abductor Pollicis Brevis", "Extensor Digitorum", "Flexor Carpi Ulnaris"],
    },
    {
        "id": 22,
        "question": "מי מהשרירים הבאים מסתיים ב- ULNA?",
        "options": ["Biceps Brachii", "Brachialis", "Supinator", "Pronator Teres"],
        "answer": 1,
        "anatomy_components": ["Biceps Brachii", "Brachialis", "Pronator Teres", "Supinator", "Ulna"],
    },
    {
        "id": 23,
        "question": "מי מהעצמות הבאות לא משתתפת במפרק RADIO-CARPAL JOINT?",
        "options": ["Lunate", "Scaphoid", "Radius", "Metacarpal 2"],
        "answer": 3,
        "anatomy_components": ["Lunate", "Metacarpal 2", "Radiocarpal Joint", "Radius", "Scaphoid"],
    },
    {
        "id": 24,
        "question": "מי מהמפרקים הבאים הוא חלק ממפרקי חגורת הכתפיים?",
        "options": ["Radio-ulnar joint", "Knee joint", "Gleno-humeral joint", "Patello-femoral joint"],
        "answer": 2,
        "anatomy_components": ["Glenohumeral Joint", "Knee Joint", "Patellofemoral Joint", "Radioulnar Joint"],
    },
    {
        "id": 25,
        "question": "מי מהבאים מייצב את הכתף בצורה פאסיבית?",
        "options": ["P.C.L", "Supraspinatus", "Meniscus", "Glenohumeral Ligament"],
        "answer": 3,
        "anatomy_components": ["Glenohumeral Ligament", "PCL", "Supraspinatus"],
    },
    {
        "id": 26,
        "question": "מי מהבאים משתתף במפרק הכתף?",
        "options": [
            "Accetabulum + Humerus",
            "Acromion + spine of scapula",
            "Ilium + Head of humerus",
            "Glenoid fossa + Head of humerus",
        ],
        "answer": 3,
        "anatomy_components": ["Acetabulum", "Acromion", "Glenoid Fossa", "Humerus", "Ilium", "Spine of Scapula"],
    },
    {
        "id": 27,
        "question": "של השכמה Elevation מי מהשרירים הבאים תפקידו לבצע?",
        "options": [
            "Upper Trapezius + Levator Scapula",
            "latissimus Dorsi + Teres Major",
            "Middle Trapezius + Rhomboids",
            "Sternocleidomastoid",
        ],
        "answer": 0,
        "anatomy_components": [
            "Latissimus Dorsi",
            "Levator Scapulae",
            "Rhomboid",
            "Sternocleidomastoid",
            "Teres Major",
            "Trapezius",
        ],
    },
    {
        "id": 28,
        "question": "clavicle - בחלק הלטרלי של ה origin למי מהשרירים הבאים?",
        "options": ["Rhomboids", "Deltoid", "Pectoralis Major", "Latissimus Dorsi"],
        "answer": 1,
        "anatomy_components": ["Clavicle", "Deltoid", "Latissimus Dorsi", "Pectoralis Major", "Rhomboid"],
    },
    {
        "id": 29,
        "question": "במפרק הכתף Internal Rotation מי מהשרירים הבאים מבצע?",
        "options": ["Latissimuse Dorsi", "Teres Major", "Anterior Deltoid", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Anterior Deltoid", "Latissimus Dorsi", "Teres Major"],
    },
    {
        "id": 30,
        "question": "Rotators Cuff - מי מהבאים אינו חלק מקבוצת ה?",
        "options": ["Supraspinatus", "Serratus Anterior", "Subscapularis", "Infraspinatus"],
        "answer": 1,
        "anatomy_components": ["Infraspinatus", "Serratus Anterior", "Subscapularis", "Supraspinatus"],
    },
    {
        "id": 31,
        "question": "מי מהשרירים הבאים עובד במישור הסגיטלי?",
        "options": ["Deltoid", "Gluteus Medius", "Triceps", "Adductors Longus"],
        "answer": 2,
        "anatomy_components": ["Deltoid", "Gluteus Medius", "Triceps"],
    },
    {
        "id": 32,
        "question": "הוא מפרק מסוג Radiocarpal מפרק:",
        "options": ["Ball & Socket", "Condyle", "Hinge", "החלקתי"],
        "answer": 1,
        "anatomy_components": ["Radiocarpal Joint"],
    },
    {
        "id": 33,
        "question": "סמן את המשפט הנכון:",
        "options": [
            "Hinge הוא מפרק מסוג M.T.P 1 מפרק",
            "Hinge מפרק הקרסול הוא מפרק מסוג",
            "Deltoid Ligament- הרצועה הפגיעה ביותר בקרסול שייכת ל",
            "Tibialis Anterior בעלייה על קצות הבהונות השריר שעובד הוא",
        ],
        "answer": 1,
        "anatomy_components": ["Ankle Joint", "Deltoid Ligament", "MTP 1 Joint", "Tibialis Anterior"],
    },
    {
        "id": 34,
        "question": "Coracoid Process - מי מהבאים נאחז ב?",
        "options": ["Long head of biceps", "Triceps", "Short head of biceps", "Deltoid"],
        "answer": 2,
        "anatomy_components": ["Biceps Brachii", "Coracoid Process", "Deltoid", "Triceps"],
    },
    {
        "id": 35,
        "question": "מי מהבאים יודע לבצע סופינציה?",
        "options": ["Biceps Brachii", "Bracioradialis", "Pronator", "Brachialis"],
        "answer": 0,
        "anatomy_components": ["Biceps Brachii", "Brachialis", "Brachioradialis", "Pronator Teres"],
    },
    {
        "id": 36,
        "question": "מי מהשרירים הבאים העמוק ביותר?",
        "options": ["Latissimuse Dorsi", "External Oblique", "Transverse Abdominis", "Sartorius"],
        "answer": 2,
        "anatomy_components": ["External Oblique", "Latissimus Dorsi", "Sartorius", "Transverse Abdominis"],
    },
    {
        "id": 37,
        "question": "ברוטציה של הגב לכיוון שמאל - מי עובד?",
        "options": [
            "Left Internal Obliqe + Left External Obliqe",
            "Left Internal Obliqe + Right External Obliqe",
            "Left External Obliqe + Right External Obliqe",
            "Left Internal Obliqe + Right Internal Obliqe",
        ],
        "answer": 1,
        "anatomy_components": ["External Oblique", "Internal Oblique"],
    },
    {
        "id": 38,
        "question": "Iliacus- מה לא נכון לגבי שריר ה?",
        "options": [
            "Gluteus Maximuse -הוא אנטגוניסט לשריר ה",
            "ומבצע כפיפת ירך Iliac Fossa- מתחיל ב",
            "במפרק ירך Flexion -ו A.P.T יודע לבצע",
            "ומבצע פשיטת ירך Greather Trochanter -מסתיים ב",
        ],
        "answer": 3,
        "anatomy_components": ["Gluteus Maximus", "Greater Trochanter", "Iliacus"],
    },
    {
        "id": 39,
        "question": "P.P.T מי מהשרירים הבאים מבצע?",
        "options": ["Quadriceps", "Rectus Abdominis", "Psoas Major", "Ilio psoas"],
        "answer": 1,
        "anatomy_components": ["Iliopsoas", "Psoas Major", "Quadriceps", "Rectus Abdominis"],
    },
    {
        "id": 40,
        "question": "מי מהבאים הוא שריר דו מפרקי?",
        "options": ["Biceps Brachii", "Sartorius", "Hamstrings", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Biceps Brachii", "Hamstrings", "Sartorius"],
    },
    {
        "id": 41,
        "question": "איזו רצועה מהבאות שייכת למפרק כתף?",
        "options": ["A.C.L", "Coracohumeral Ligament", "M.C.L", "Iliofemoral Ligament"],
        "answer": 1,
        "anatomy_components": ["ACL", "Coracohumeral Ligament", "Iliofemoral Ligament", "MCL"],
    },
    {
        "id": 42,
        "question": "איזה שרירים נאחזים ב- I.T.B",
        "options": [
            "Gluteus Medius + Gluteus Minimus",
            "Gastrochnemius + Soleus",
            "Latissimuse Dordi + Pectoralis Minor",
            "T.F.L + Gluteus Maximuse",
        ],
        "answer": 3,
        "anatomy_components": [
            "Gastrocnemius",
            "Gluteus Maximus",
            "Gluteus Medius",
            "Gluteus Minimus",
            "Iliotibial Band",
            "Latissimus Dorsi",
            "Pectoralis Minor",
            "Soleus",
            "Tensor Fasciae Latae",
        ],
    },
    {
        "id": 43,
        "question": "מי מהבאים מייצב את מפרק הברך?",
        "options": ["Gluteus Minimus", "Psoas Major", "A.C.L + P.C.L", "Patella"],
        "answer": 2,
        "anatomy_components": ["ACL", "Gluteus Minimus", "PCL", "Patella", "Psoas Major"],
    },
    {
        "id": 44,
        "question": "מי מהבאים מבצעים את אותן הפעולות?",
        "options": [
            "Tibialis Anterior+ Tibialis Posterior",
            "Peroneus Longus + Tibialis Anterior",
            "Quadriceps",
            "Gastrochnemius + soleus",
        ],
        "answer": 3,
        "anatomy_components": [
            "Gastrocnemius",
            "Peroneus Longus",
            "Quadriceps",
            "Soleus",
            "Tibialis Anterior",
            "Tibialis Posterior",
        ],
    },
    {
        "id": 45,
        "question": "מי מהבאים מבצע כפיפה של עמוד השדרה?",
        "options": ["Rectus Abdominis", "External Obliqe", "כל התשובות נכונות", "Intrnal Obliqe"],
        "answer": 2,
        "anatomy_components": ["External Oblique", "Internal Oblique", "Rectus Abdominis"],
    },
    {
        "id": 46,
        "question": "מי מהשרירים הבאים יניע את האגודל?",
        "options": [
            "Extensor Indicis",
            "Palmaris Longus",
            "Flexor Pollicis Longus",
            "Flexor Hallucis Longus",
        ],
        "answer": 2,
        "anatomy_components": [
            "Extensor Indicis",
            "Flexor Hallucis Longus",
            "Flexor Pollicis Longus",
            "Palmaris Longus",
        ],
    },
    {
        "id": 47,
        "question": "איזו רצועה מהבאות תפקידה למנוע עודף תנועה במישור הסגיטלי?",
        "options": ["M.C.L", "P.C.L", "Medial Meniscus", "L.C.L"],
        "answer": 1,
        "anatomy_components": ["LCL", "MCL", "Medial Meniscus", "PCL"],
    },
    {
        "id": 48,
        "question": "Femur- בעצם ה origin למי מהשרירים הבאים?",
        "options": ["Vastus Medialis", "Longissimuse", "Semimembranosus", "Rectus Femoris"],
        "answer": 0,
        "anatomy_components": ["Femur", "Longissimus", "Rectus Femoris", "Semimembranosus", "Vastus Medialis"],
    },
    {
        "id": 49,
        "question": "מהי הבורסה העלולה להינזק מעמידה ממושכת על הברכיים?",
        "options": ["Trochanteric Bursa", "Prepatellar Bursa", "Suprapatellar Bursa", "Subacromial Bursa"],
        "answer": 1,
        "anatomy_components": ["Prepatellar Bursa", "Subacromial Bursa", "Suprapatellar Bursa", "Trochanteric Bursa"],
    },
    {
        "id": 50,
        "question": "מבצע Periformis -שריר ה:",
        "options": [
            "Internal Rotation מפרק ירך",
            "Abduction מפרק ירך",
            "External Rotation מפרק ירך",
            "כל התשובות נכונות",
        ],
        "answer": 2,
        "anatomy_components": ["Piriformis"],
    },
    {
        "id": 51,
        "question": "מתבצעת במפרק Eversion- תנועת ה:",
        "options": ["D.I.P jt", "Talo-Crural jt", "Knee jt", "Subtalar jt"],
        "answer": 3,
        "anatomy_components": ["DIP Joint", "Knee Joint", "Subtalar Joint", "Talocrural Joint"],
    },
    {
        "id": 52,
        "question": "מי מהשרירים הבאים מניע שכמה?",
        "options": ["Hamstrings", "Trapezius", "Latissimuse Dorsi", "Subscapularis"],
        "answer": 1,
        "anatomy_components": ["Hamstrings", "Latissimus Dorsi", "Subscapularis", "Trapezius"],
    },
    {
        "id": 53,
        "question": "מבצע Sternoclaidomastoid-שריר ה:",
        "options": ["Extension דו צדדי", "רוטציה לאותו הצד", "Flexion דו צדדי", "סופינציה"],
        "answer": 2,
        "anatomy_components": ["Sternocleidomastoid"],
    },
    {
        "id": 54,
        "question": "Anterior Deltoid מה מבצע?",
        "options": [
            "Extension, Horizontal Abduction, External rotation",
            "Flexion, Horizontal Adduction, Internal rotation",
            "Abduction",
            "כל התשובות נכונות",
        ],
        "answer": 1,
        "anatomy_components": ["Anterior Deltoid"],
    },
    {
        "id": 55,
        "question": "למי מהשרירים הבאים יש נקודת אוריגן זהה?",
        "options": [
            "Pectoralis Minor + Pectoralis Major",
            "Deltoid + Trapezius",
            "Semimembranosus+ Semitendinosus",
            "Gastrocnemius + Soleus",
        ],
        "answer": 2,
        "anatomy_components": [
            "Deltoid",
            "Gastrocnemius",
            "Pectoralis Major",
            "Pectoralis Minor",
            "Semimembranosus",
            "Semitendinosus",
            "Soleus",
            "Trapezius",
        ],
    },
    {
        "id": 56,
        "question": "מי מהבאים מבצעים פעולות מנוגדות של סיבוב אגן ?",
        "options": [
            "Rectus Abdominis - Internal obliqe",
            "External obliqe - Internal Obliqe",
            "Ilio psoas - Gluteus Maximuse",
            "Ilio psoas - Vastus Medialis",
        ],
        "answer": 2,
        "anatomy_components": [
            "External Oblique",
            "Gluteus Maximus",
            "Iliopsoas",
            "Internal Oblique",
            "Rectus Abdominis",
            "Vastus Medialis",
        ],
    },
    {
        "id": 57,
        "question": "מי מהשרירים הבאים מבצע P.P.T?",
        "options": ["Iliopsoas", "Quadriceps", "Rectus Abdominis", "Gluteus Medius"],
        "answer": 2,
        "anatomy_components": ["Gluteus Medius", "Iliopsoas", "Quadriceps", "Rectus Abdominis"],
    },
    {
        "id": 58,
        "question": "איזה מהמפרקים הבאים עלול להוות מצב חירום בעת פריקה?",
        "options": [
            "Acromio-clavicular jt",
            "Sterno-clavicular jt",
            "Gleno-humeral jt",
            "Patello-femoral jt",
        ],
        "answer": 1,
        "anatomy_components": [
            "Acromioclavicular Joint",
            "Glenohumeral Joint",
            "Patellofemoral Joint",
            "Sternoclavicular Joint",
        ],
    },
    {
        "id": 59,
        "question": "לאיזה שריר מהבאים יש Insrtion בעצם ה- Radius?",
        "options": ["Brachialis", "Rhomboids", "Triceps", "Biceps Brachii"],
        "answer": 3,
        "anatomy_components": ["Biceps Brachii", "Brachialis", "Radius", "Rhomboid", "Triceps"],
    },
    {
        "id": 60,
        "question": "מפרק C.M.C 1 הוא מפרק מסוג:",
        "options": ["Gliding", "Pivot", "Saddle", "Ball & Socket"],
        "answer": 2,
        "anatomy_components": ["CMC 1 Joint"],
    },
    {
        "id": 61,
        "question": "למי מהשרירים הבאים אחיזה בצלעות ?",
        "options": ["Latissimuse Dorsi", "Serratus Anterior", "External Obliqe", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["External Oblique", "Latissimus Dorsi", "Serratus Anterior"],
    },
    {
        "id": 62,
        "question": "איזו רצועה מבין הבאות היא הפגיעה ביותר במפרק הקרסול?",
        "options": ["Deltoid Ligament", "Glenohumeral Ligament", "A.T.F.L", "P.C.L"],
        "answer": 2,
        "anatomy_components": ["ATFL", "Ankle Joint", "Deltoid Ligament", "Glenohumeral Ligament", "PCL"],
    },
    {
        "id": 63,
        "question": "למי מהשרירים הבאים Insertion ב - Bicipital Groove ?",
        "options": ["Teres Minor", "Teres Major", "Triceps", "Serratus Anterior"],
        "answer": 1,
        "anatomy_components": ["Bicipital Groove", "Serratus Anterior", "Teres Major", "Teres Minor", "Triceps"],
    },
    {
        "id": 64,
        "question": "מי מהשרירים הבאים מבצע Side Flexion?",
        "options": [
            "Internal Obliqe",
            "Q.L ( Quadratus Lumborum )",
            "External Obliqe",
            "כל התשובות נכונות",
        ],
        "answer": 3,
        "anatomy_components": ["External Oblique", "Internal Oblique", "Quadratus Lumborum"],
    },
    {
        "id": 65,
        "question": "מי מצמד השרירים הבאים מבצעים פעולות מנוגדות?",
        "options": [
            "Rhomboids + Serratus Anterior",
            "Gluteus Medius + Adductor Brevis",
            "Tibialis Anterior + Soleus",
            "כל התשובות נכונות",
        ],
        "answer": 3,
        "anatomy_components": [
            "Adductor Brevis",
            "Gluteus Medius",
            "Rhomboid",
            "Serratus Anterior",
            "Soleus",
            "Tibialis Anterior",
        ],
    },
    {
        "id": 66,
        "question": "מהו השריר העיקרי המרחיק כתף?",
        "options": ["Pectoralis Major", "Quadriceps", "Deltoid", "Hamstrings"],
        "answer": 2,
        "anatomy_components": ["Deltoid", "Hamstrings", "Pectoralis Major", "Quadriceps"],
    },
    {
        "id": 67,
        "question": "למי מהשרירים הבאים יש יותר מגיד אחד בנקודת ההתחלה?",
        "options": ["Biceps Brachii", "Quadriceps", "Triceps", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Biceps Brachii", "Quadriceps", "Triceps"],
    },
    {
        "id": 68,
        "question": "הפעולה העיקרית של שרירי ה- Hamstrings היא:",
        "options": ["פשיטה במפרק הברך", "הרחקה במפרק ירך", "כפיפה במפרק הברך", "כפיפה במפרק כתף"],
        "answer": 2,
        "anatomy_components": ["Hamstrings"],
    },
    {
        "id": 69,
        "question": "מי מהשרירים הבאים מבצע קירוב אופקי במפרק הכתף?",
        "options": ["Gastrocnemius", "Gluteus Medius", "Pectoralis Major", "Triceps"],
        "answer": 2,
        "anatomy_components": ["Gastrocnemius", "Gluteus Medius", "Pectoralis Major", "Triceps"],
    },
    {
        "id": 70,
        "question": "מי מהשרירים שלמדת מקרב שכמות אל עמוד השדרה?",
        "options": ["Rectus Abdominis", "Trapezius", "Hamstrings", "Quadriceps"],
        "answer": 1,
        "anatomy_components": ["Hamstrings", "Quadriceps", "Rectus Abdominis", "Trapezius"],
    },
    {
        "id": 71,
        "question": "מי משרירי הבטן מכופף את הגו?",
        "options": ["Transverse Abdominis", "External Oblique", "Rectus Abdominis", "Internal Oblique"],
        "answer": 2,
        "anatomy_components": ["External Oblique", "Internal Oblique", "Rectus Abdominis", "Transverse Abdominis"],
    },
    {
        "id": 72,
        "question": "מי מהשרירים שלמדת פושט ברך ומכופף ירך?",
        "options": ["Hamstrings", "Biceps Brachii", "Rectus Femoris", "Long head of triceps"],
        "answer": 2,
        "anatomy_components": ["Biceps Brachii", "Hamstrings", "Rectus Femoris", "Triceps"],
    },
    {
        "id": 73,
        "question": "מה מסוגל לבצע ה- Long head of Triceps?",
        "options": ["כפיפת כתף", "פשיטת כתף ופשיטת כתף", "הרחקת כתף", "קירוב אופקי בכתף"],
        "answer": 1,
        "anatomy_components": ["Triceps"],
    },
]
