# -*- coding: utf-8 -*-
# Orthopedics question bank.
#
# Sources, both supplied by the course and both carrying their own answer key,
# so no answer here was derived:
#   ids 1001-1013 "אורתופדיה - שאלות דוגמה אורתופדיה צאלי עם תשובות נכונות -
#             98761.DOCX". The correct option is the one highlighted yellow in
#             the document; the highlight is the key.
#   ids 1014-1015 "אורתופדיה - שאלות לדוגמה מחיים לחומר שלו - 98791.DOCX",
#             which lists its answers as letters in a "תשובות" block at the end.
#   ids 1016-1035 "אורתופדיה - אורתופדיה בדיקות - 98150.PDF", the lecture
#             slides. Unlike the two sheets above this one carries no answer
#             key, because it is not a question paper — each answer is the
#             fact its slide states, and the distractors are the other terms
#             and modalities from the same slides. 1016-1020 are the five
#             terms on slide 9 (הפרעות תחושה וכאב); 1021-1035 cover the five
#             imaging modalities on slides 15-19, three questions each —
#             ionising radiation, what it shows, and how it works.
#
# Question text is verbatim apart from two normalisations: the "א. ב. ג. ד."
# prefixes are dropped, since the app renders options as buttons and shows no
# letters, and for the same reason two distractors reading "א+ב נכונות" are
# rephrased by position. Option order is untouched, so the answer indices below
# are the document's own.
#
# Ids start at 1001 because /questions/{id}/answer identifies a question by id
# alone, with no course in the path — see courses.py, which refuses to start if
# two courses ever claim the same number.
#
# anatomy_components borrows the reference pages in frontend/src/anatomyData.ts
# rather than orthopedics having its own. It is empty where a question is about
# a process — fracture healing, hernia, choice of imaging — rather than about a
# structure the reader could go and look at.
#   ids 1036-1222 the six lecture decks, read as rendered page images:
#             98153 upper limb, 98624 elbow/wrist/hand, 98151 spine, 98720
#             pelvis/hip/knee, 98152 lower limb. The seventh deck supplied,
#             98417 shoulder, is anatomy and imaging only and yielded nothing.
#             Pathologies only — the anatomy in these decks is the other
#             course's subject. Each pathology gets a question on where the
#             problem is and one on how it presents, and a third where its
#             slide supports one. Every answer is what its slide states,
#             including where a slide departs from textbook convention: the
#             course is what these students are examined on.
QUESTIONS = [
    {
        "id": 1001,
        "question": "מה לא  נכון לגבי הרצועה ?",
        "options": [
            "בקרע מלא דרוש ניתוח על מנת לאחות את הרצועה",
            "בקרע מלא ניתן לקבע את המפרק והרצועה תתאחה לאחר 6 שבועות",
            "יציבות המפרק נפגעת בעקבות הקרע",
            "לרצועה אספקת דם פחות טובה ולכן ריפוי איטי",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1002,
        "question": "מה יכול להיות  סיבוך של שבר ?",
        "options": ["קיצור הגפה", "הגבלת טווח התנועה במפרק", "פגיעה בכלי דם או/ו עצב", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1003,
        "question": "מה המנגנון הגורם לשברי מאמץ בחוליות (spondylolisis) ?",
        "options": ["פשיטת גב", "גיפוף גב", "שתי התשובות הראשונות נכונות", "אף תשובה לא נכונה"],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1004,
        "question": "באילו אזורים נפוצה פריצת דיסק ?",
        "options": ["L1-L2", "L2-L3", "L4-L5", "פריצת דיסק יכולה לקרות באופן שווה בכל הנ''ל"],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1005,
        "question": "מה זה spondylolistesis   ?",
        "options": [
            "שברי מאמץ בחוליות",
            "החלקה של חוליה אחת על גבי השנייה בעקבות שברי מאמץ",
            "פריצות דיסק קטנות באזור המותני",
            "מקרה פרטי של בלט דיסק",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1006,
        "question": "מה הסכנה העיקרית בשבר פתוח ?",
        "options": ["איבוד דם", "זיהום", "שתי התשובות הראשונות נכונות", "אין שום הבדל בין שבר פתוח לסגור"],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1007,
        "question": "מה נכון לגבי פריקות כתף ?",
        "options": [
            "מתרחש בה שבר של עצם הזרוע",
            "נפוצות יותר פריקות אחוריות ותחתונות של הכתף",
            "המנח בו מתרחשות  פשיטה ורוטציה פנימה",
            "יציבות הכתף נפגעת בעקבות פגיעה ברצועות",
        ],
        "answer": 3,
        "anatomy_components": ["Glenohumeral Joint", "Glenohumeral Ligament"],
    },
    {
        "id": 1008,
        "question": "מה המנח של פריקת כתף קדמית ?",
        "options": [
            "רוטציה פנימה ופשיטת כתף",
            "ריחוק אופקי בלבד",
            "רוטציה החוצה וריחוק כתף",
            "אף תשובה לא נכונה",
        ],
        "answer": 2,
        "anatomy_components": ["Glenohumeral Joint"],
    },
    {
        "id": 1009,
        "question": "איזה רקמה נפגעת במרפק טניס ?",
        "options": ["עצב", "שרירי פושטי שורש כף היד", "שרירי מכופפי שורש כף היד", "בורסה של המרפק"],
        "answer": 1,
        "anatomy_components": [
            "Extensor Carpi Radialis Brevis",
            "Extensor Carpi Ulnaris",
            "Lateral Epicondyle",
        ],
    },
    {
        "id": 1010,
        "question": "מה זה OSHGOOD SHLATER ?",
        "options": [
            "שם של מדען גרמני שהמציא את מכשיר הרנטגן",
            "עומס על גיד הפיקה בעקבות גדילה מהירה של עצם",
            "עומס על גיד הפיקה בעקבות גדילה מהירה של שריר",
            "מאפיין יותר אנשים בגילאי 40+",
        ],
        "answer": 1,
        "anatomy_components": ["Patella", "Tibia"],
    },
    {
        "id": 1011,
        "question": "מה זה בקע מפשעתי ?",
        "options": [
            "פריצת דיסק לכיוון המפשעה",
            "פריצת מעיים לתוך החלל של המפשעה",
            "שקע טבעי שקיים אצל כל האוכלוסייה",
            "מצב  של קרע בשרירי הירך",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1012,
        "question": "באיזה שלב בן אדם ירגיש כאב בעקבות שחיקת סחוס הברך ?",
        "options": [
            "כבר בשלב ההתחלתי מכיוון שלסחוס יש רשת עצבים ענפה",
            "בן אדם לא ירגיש כאב בשום שלב",
            "הכאב יורגש בדרגה 3+4 , בעת חשיפה של עצם",
            "אף תשובה אינה נכונה",
        ],
        "answer": 2,
        "anatomy_components": ["Knee Joint"],
    },
    {
        "id": 1013,
        "question": "כיצד נטפל בשבר פתוח ?",
        "options": [
            "נקבע על ידי גבס",
            "נקבע על ידי ברזלים בתוך העצם",
            "נקבע על ידי מקבע חיצוני ואנטיביוטיקה",
            "שבר פתוח אינו מסוכן ומתרפא באופן עצמאי ללא כל התערבות",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1014,
        "question": "מטרת האבחון החולה האורתופדי:",
        "options": [
            "למצוא את התהליך הפתולוגי",
            "להבין את החסר הפונקציונאלי",
            "הבנת המוגבלות הנובעת מתוך החסר הפונקציונאלי",
            "כל המשפטים הנ\"ל נכונים.",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1015,
        "question": "מהי שיטת דימות המתאימה ביותר לאבחון שבר?:",
        "options": ["צילום רנטגן", "צילום MRI", "אולטרסאונד", "אף אחד מהנ\"ל"],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1016,
        "question": "מה המשמעות של Hypoesthesia?",
        "options": [
            "תחושתיות יתר",
            "ירידה תחושתית",
            "גירוי לא מכאיב מעורר כאב",
            "תחושה לא תקינה - נימולים, דקירות ותחושת שריפה",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1017,
        "question": "מה המשמעות של Hyperesthesia?",
        "options": [
            "גירוי מכאיב גורם לכאב מוגבר מן הצפוי",
            "ירידה תחושתית",
            "תחושתיות יתר",
            "גירוי לא מכאיב מעורר כאב",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1018,
        "question": "מה המשמעות של Paresthesia?",
        "options": [
            "תחושה לא תקינה - נימולים, דקירות ותחושת שריפה",
            "ירידה תחושתית",
            "תחושתיות יתר",
            "גירוי מכאיב גורם לכאב מוגבר מן הצפוי",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1019,
        "question": "מה המשמעות של Hyperalgesia?",
        "options": [
            "גירוי לא מכאיב מעורר כאב",
            "תחושתיות יתר",
            "ירידה תחושתית",
            "גירוי מכאיב גורם לכאב מוגבר מן הצפוי",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1020,
        "question": "מה המשמעות של Allodynia?",
        "options": [
            "גירוי מכאיב גורם לכאב מוגבר מן הצפוי",
            "ירידה תחושתית",
            "גירוי לא מכאיב מעורר כאב",
            "תחושתיות יתר",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1021,
        "question": "האם קיימת קרינה מייננת בצילום רנטגן (X-ray)?",
        "options": [
            "ללא קרינה מייננת",
            "קרינה מייננת נמוכה",
            "קרינה מייננת",
            "קרינה מייננת הנובעת מהזרקת חומר סימון רדיואקטיבי",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1022,
        "question": "האם קיימת קרינה מייננת ב-CT?",
        "options": [
            "קרינה מייננת נמוכה",
            "ללא קרינה מייננת",
            "קרינה מייננת",
            "קרינה מייננת הנובעת מהזרקת חומר סימון רדיואקטיבי",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1023,
        "question": "האם קיימת קרינה מייננת ב-MRI?",
        "options": [
            "קרינה מייננת",
            "קרינה מייננת נמוכה",
            "קרינה מייננת הנובעת מהזרקת חומר סימון רדיואקטיבי",
            "ללא קרינה מייננת",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1024,
        "question": "האם קיימת קרינה מייננת במיפוי עצמות?",
        "options": [
            "קרינה מייננת הנובעת מהזרקת חומר סימון רדיואקטיבי",
            "ללא קרינה מייננת",
            "קרינה מייננת נמוכה",
            "קרינה מייננת",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1025,
        "question": "האם קיימת קרינה מייננת באולטרה סאונד (US)?",
        "options": [
            "קרינה מייננת נמוכה",
            "ללא קרינה מייננת",
            "קרינה מייננת",
            "קרינה מייננת הנובעת מהזרקת חומר סימון רדיואקטיבי",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1026,
        "question": "מה מאתרת בדיקת רנטגן (X-ray)?",
        "options": [
            "מניסקוסים, דיסקים ורצועות",
            "שברים, פריקות והסתיידויות",
            "שברי מאמץ, דלקות וגידולים",
            "שרירים, גידים ורצועות",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1027,
        "question": "אילו שברים מודגמים במיוחד ב-CT?",
        "options": [
            "שברים בעצמות ארוכות בלבד",
            "שברי מאמץ בלבד",
            "שברים מורכבים, תוך מפרקיים, קטנים ובחוליות",
            "CT אינו מתאים להדגמת שברים",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1028,
        "question": "באילו רקמות יעילה בדיקת MRI?",
        "options": [
            "רקמת עצם בלבד",
            "הסתיידויות בלבד",
            "אזורים עם פעילות מוגברת של בניית עצם",
            "רקמות רכות - מניסקוסים, דיסקים, רצועות ומערכת העצבים",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1029,
        "question": "מה מאתר מיפוי עצמות?",
        "options": [
            "שברי מאמץ, דלקות, גידולים וזיהומים",
            "קרעים ברצועות בלבד",
            "מניסקוסים ודיסקים בלבד",
            "פריקות מפרקים בלבד",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1030,
        "question": "אילו מבנים נבדקים באולטרה סאונד (US)?",
        "options": [
            "חוליות ודיסקים",
            "מוח וחוט השדרה",
            "שרירים, רצועות, גידים ואיברים פנימיים",
            "עצמות בלבד",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1031,
        "question": "מה מאפיין את בדיקת הרנטגן (X-ray) מבחינת זמינות?",
        "options": [
            "בדיקה יקרה וארוכה",
            "מחייבת הזרקת חומר סימון רדיואקטיבי",
            "תלויה במיומנות המפעיל",
            "בדיקה פשוטה וזמינה",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1032,
        "question": "כיצד מדמה בדיקת CT את האזור הנבדק?",
        "options": [
            "צילום תלת מימדי ברזולוציה גבוהה",
            "צילום דו מימדי ברזולוציה נמוכה",
            "הדמיה בזמן אמת בלבד",
            "הדמיה המבוססת על חומר רדיואקטיבי",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1033,
        "question": "מתי השימוש ב-MRI בעייתי?",
        "options": [
            "כאשר יש חשד לשבר",
            "כאשר המטופל צעיר מאוד",
            "כאשר יש מתכות בגוף",
            "כאשר יש צורך בהדמיית רקמות רכות",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1034,
        "question": "כיצד מתבצע מיפוי עצמות?",
        "options": ["בהזרקת חומר סימון רדיואקטיבי", "בגלי קול", "בשדה מגנטי", "בצילום תלת מימדי"],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1035,
        "question": "מהי מגבלה של בדיקת אולטרה סאונד (US)?",
        "options": [
            "חשיפה לקרינה מייננת גבוהה",
            "אינו יכול לחדור עצמות ועומק החדירה מוגבל",
            "מחייב הזרקת חומר ניגוד",
            "אורך זמן רב מאוד",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1036,
        "question": "מהו מנגנון הפציעה האופייני ל-Clavicle fracture על פי המצגת?",
        "options": [
            "חבלה ישירה לזרוע הדורשת כוח רב",
            "נפילה על יד מושטת לפנים כאשר שורש כף היד במנח DF",
            "מנגנון לא ישיר – נפילה על הצד או נפילה עם יד מושטת לפנים",
            "כוח שמופעל על היד כאשר היא ב-Abduction מלא",
        ],
        "answer": 2,
        "anatomy_components": ["Clavicle"],
    },
    {
        "id": 1037,
        "question": "מה כולל הטיפול השמרני בשבועות הראשונים לאחר Clavicle fracture?",
        "options": [
            "מתלה, הנעת מרפק ושורש כף יד ותנועות עדינות בכתף (פנדולרי)",
            "Manipulation Under Anesthesia (MUA) בהרדמה מלאה",
            "Internal fixation with plates and screws",
            "רדוקציה מוקדמת על ידי רופא בלבד",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1038,
        "question": "מהם הסימנים של Acromioclavicular joint dislocation?",
        "options": [
            "כאב בשורש כף היד ובאזור ה-snuff box המתגבר באחיזת חפצים",
            "כאב באזור המפרק שמתגבר בתנועה, בעיקר בתנועת Horizontal Adduction, ועלול להתלוות בכאב בזרוע ובצוואר",
            "אובדן טווחי תנועה פסיביים ואקטיביים בכל תנועות הכתף",
            "בלט במרכז השריר – Popeye sign",
        ],
        "answer": 1,
        "anatomy_components": ["Acromioclavicular Joint"],
    },
    {
        "id": 1039,
        "question": "מהו המנגנון של Acromioclavicular joint dislocation?",
        "options": [
            "נפילה על יד מושטת לפנים (FOOSH)",
            "עומס יתר של פעילות חוזרנית של GRIP",
            "אפילפסיה או התחשמלות",
            "נפילות על הכתף והזרוע",
        ],
        "answer": 3,
        "anatomy_components": ["Acromioclavicular Joint"],
    },
    {
        "id": 1040,
        "question": "מה כולל הטיפול ב-Acromioclavicular joint dislocation לפי המצגת?",
        "options": [
            "Hemi-Arthroplasty או Reverse Arthroplasty",
            "קיבוע בגבס למשך שישה שבועות ללא כל תנועה",
            "מנוחה מפעילות ספורטיבית ומפעולות מכאיבות, חבישה וחיזוק",
            "Manipulation Under Anesthesia (MUA)",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1041,
        "question": "מהו המנגנון של שבר הומרוס באזור ה-Surgical Neck?",
        "options": [
            "נפילה על הצד",
            "נפילה על הזרוע",
            "חבלה ישירה לזרוע הדורשת כוח רב",
            "נפילה על יד מושטת לפנים עם שורש כף היד ב-DF",
        ],
        "answer": 1,
        "anatomy_components": ["Humerus"],
    },
    {
        "id": 1042,
        "question": "באיזו אוכלוסייה נפוץ שבר הומרוס באזור ה-Surgical Neck?",
        "options": [
            "בקרב ילדים ומתבגרים בתקופת גדילה מהירה",
            "בקרב נשים בהריון",
            "בקרב ספורטאים צעירים לאחר פעילות חוזרנית",
            "באוכלוסייה מבוגרת (אוסטאופורוזיס)",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1043,
        "question": "מהו המנגנון של שבר ב-Humeral Shaft?",
        "options": [
            "חבלה ישירה לזרוע, נדרש כוח רב",
            "מנגנון לא ישיר של נפילה על הצד",
            "נפילה על יד מושטת לפנים (FOOSH)",
            "90° Abd + Ext rot",
        ],
        "answer": 0,
        "anatomy_components": ["Humerus"],
    },
    {
        "id": 1044,
        "question": "מהי הסכנה המרכזית בשבר של ה-Humeral Shaft וכיצד היא מתבטאת?",
        "options": [
            "אספקת דם נמוכה לעצם המובילה ל-Avascular necrosis (AVN)",
            "היווצרות Hill sachs בראש ההומרוס",
            "פגיעה בכלי דם ועצבים – Drop wrist",
            "הפרעה תחושתית באצבעות 1-4 המתגברת בלילה",
        ],
        "answer": 2,
        "anatomy_components": ["Humerus"],
    },
    {
        "id": 1045,
        "question": "אילו אפשרויות טיפול בשברים של ההומרוס מוצגות במצגת?",
        "options": [
            "קיבוע חיצוני ואנטיביוטיקה בלבד",
            "Manipulation Under Anesthesia (MUA) בלבד",
            "חבישה, מנוחה וחיזוק בלבד",
            "טיפול לא ניתוחי, Locking Plate, Locking Nail, Hemi-Arthroplasty ו-Reverse Arthroplasty",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1046,
        "question": "מהי ההגדרה של Dislocation ושל Subluxation בכתף לפי המצגת?",
        "options": [
            "Dislocation – קרע של הלברום; Subluxation – שבר של ראש ההומרוס",
            "Dislocation – היפרדות בין ראש ההומרוס לגלנואיד; Subluxation – פריקה חלקית",
            "Dislocation – פריקה חלקית; Subluxation – היפרדות מלאה בין ראש ההומרוס לגלנואיד",
            "Dislocation – קושי לשמור על מנח ראש ההומרוס בתנועה; Subluxation – נעילה של המפרק",
        ],
        "answer": 1,
        "anatomy_components": ["Glenohumeral Joint"],
    },
    {
        "id": 1047,
        "question": "מה גורם בדרך כלל לפריקת כתף אחורית?",
        "options": [
            "נפילה על יד מושטת לפנים",
            "כוח שמופעל על היד כאשר היא ב-Abd מלא",
            "אפילפסיה או התחשמלות",
            "נפילה על הכתף והזרוע",
        ],
        "answer": 2,
        "anatomy_components": ["Glenohumeral Joint"],
    },
    {
        "id": 1048,
        "question": "מתי מתרחשת פריקת כתף תחתונה ומה שכיחותה?",
        "options": [
            "כוח שמופעל על היד כאשר היא ב-Abd מלא, פחות מ-1% מהמקרים",
            "90° Abd + Ext rot, כ-95% מהמקרים",
            "עקב תנועה חוזרנית מעל גובה הראש",
            "נפילה על הצד, כ-50% מהמקרים",
        ],
        "answer": 0,
        "anatomy_components": ["Glenohumeral Joint"],
    },
    {
        "id": 1049,
        "question": "מהם התסמינים של פריקת כתף לפי המצגת?",
        "options": [
            "כאב בלילה ובשכיבה על הצד עם רגישות מקומית למישוש",
            "קליקים בתנועה ותחושת חולשה ועייפות",
            "נעילה של הגפה במצב כפיפה, עם או ללא כאב",
            "כאב, אין תנועתיות והיד נראית תלויה לצד הגוף, ובהסתכלות אסימטריה בגובה הכתפיים",
        ],
        "answer": 3,
        "anatomy_components": ["Glenohumeral Joint"],
    },
    {
        "id": 1050,
        "question": "מה נכון לגבי הטיפול הראשוני בפריקת כתף?",
        "options": [
            "הרדוקציה תבוצע רק לאחר שלושה שבועות של מנוחה",
            "רדוקציה מוקדמת ככל האפשר על ידי רופא בלבד, ובתחילת השיקום יש להימנע משילוב Abd + Ext. Rot",
            "כל מטפל רשאי לבצע רדוקציה, ויש לעודד מיד תנועות Abd + Ext. Rot",
            "אין צורך בצילום רנטגן לפני הרדוקציה",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1051,
        "question": "מהי פגיעת Hill sachs הנלווית לפריקת כתף?",
        "options": [
            "שבר של ראש ההומרוס",
            "קרע של הלברום בחלק האנטריורי-אינפריורי",
            "קרע של גיד ה-Long head of Biceps",
            "היצרות של מעטפת הגיד",
        ],
        "answer": 0,
        "anatomy_components": ["Humerus"],
    },
    {
        "id": 1052,
        "question": "מהי Bankart Lesion הנלווית לפריקת כתף?",
        "options": [
            "שבר של ראש ההומרוס",
            "דלקת של הבורסה הסובאקרומיאלית",
            "קרע של הלברום (Anterior inferior labral lesion)",
            "פגיעה בעצב המדיאני בשורש כף היד",
        ],
        "answer": 2,
        "anatomy_components": ["Glenoid Fossa"],
    },
    {
        "id": 1053,
        "question": "מה מאפיין Shoulder Instability (חוסר יציבות) בכתף?",
        "options": [
            "אובדן טווחי תנועה פסיביים ואקטיביים בכל תנועות הכתף",
            "קושי לשמור את מנח ראש ההומרוס אל מול הגלנואיד בתנועות הכתף",
            "היפרדות מלאה וקבועה בין ראש ההומרוס לגלנואיד",
            "היצרות של מעטפת הגיד או עיבוי של הגיד",
        ],
        "answer": 1,
        "anatomy_components": ["Glenohumeral Joint"],
    },
    {
        "id": 1054,
        "question": "מהם התסמינים של Shoulder Instability?",
        "options": [
            "כאב מפושט במנוחה שמתגבר בתנועה וכאבי לילה",
            "בלט במרכז השריר ושמיעת צליל \"פופ\"",
            "רגישות למישוש בבסיס האצבע",
            "כאב בתנועה, קליקים, תחושת חולשה ועייפות (בזריקת כדור)",
        ],
        "answer": 3,
        "anatomy_components": ["Glenohumeral Joint"],
    },
    {
        "id": 1055,
        "question": "אילו גורמים תורמים ל-Shoulder Instability?",
        "options": [
            "פריקה, פגיעה בלברום, גמישות יתר, חולשה שרירית ופעולות חוזרניות",
            "סוכרת, שבץ, ניתוחים וקיבוע ממושך",
            "נפילה על יד מושטת לפנים ועבודה עם כלים כבדים",
            "הריון והרמת התינוק",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1056,
        "question": "היכן ממוקם הקרע בקרע של גיד הבייספס המתואר במצגת?",
        "options": [
            "ב-Short head of Biceps",
            "בגיד המשותף של פושטי האמה",
            "ב-Long head of Biceps",
            "בגיד ה-Supraspinatus",
        ],
        "answer": 2,
        "anatomy_components": ["Biceps Brachii"],
    },
    {
        "id": 1057,
        "question": "מהם התסמינים של קרע של גיד ה-Long head of Biceps?",
        "options": [
            "כאב בשורש כף היד המשליך לאגודל ולכף היד",
            "כאב פתאומי בכתף קדמית, שמיעת צליל \"פופ\" ובלט במרכז השריר – Popeye sign",
            "אסימטריה בגובה הכתפיים והיד תלויה לצד הגוף",
            "הפרעה תחושתית באצבעות 1-4",
        ],
        "answer": 1,
        "anatomy_components": ["Biceps Brachii"],
    },
    {
        "id": 1058,
        "question": "מה נכון לגבי קרע מלא וקרע חלקי של גיד ה-Long head of Biceps?",
        "options": [
            "קרע מלא אופייני בקרב מבוגרים, קרע חלקי אופייני בקרב צעירים",
            "קרע מלא אופייני בקרב צעירים, קרע חלקי אופייני בקרב מבוגרים",
            "שני סוגי הקרע אופייניים לנשים בגילאי 40-60",
            "שני סוגי הקרע נגרמים רק ממנגנון אקוטי של נפילה",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1059,
        "question": "באיזו רקמה ממוקמת הפתולוגיה ב-Rotator cuff Tendinopathy?",
        "options": ["בבורסה הסובאקרומיאלית", "בקפסולה המפרקית", "בלברום", "בגיד"],
        "answer": 3,
        "anatomy_components": ["Infraspinatus", "Subscapularis", "Supraspinatus", "Teres Minor"],
    },
    {
        "id": 1060,
        "question": "מהם התסמינים האופייניים ל-Rotator cuff Tendinopathy?",
        "options": [
            "נעילה של האצבע במצב כפיפה",
            "כאב רק במנוחה שחולף לחלוטין בתנועה",
            "כאב בהרמת היד בעיקר מעל 90° וכאב ברוטציות בעיקר בתנועת HBB, המתגברים בהתנגדות לתנועה",
            "כאב בשורש כף היד ובאזור ה-snuff box",
        ],
        "answer": 2,
        "anatomy_components": ["Supraspinatus"],
    },
    {
        "id": 1061,
        "question": "כיצד מתבטאת מעורבות ה-Biceps ב-Rotator cuff Tendinopathy?",
        "options": [
            "כאב לטרלי במרפק שמתגבר ב-Supination ובהרמת חפצים",
            "כאב באזור הקדמי של הכתף שיכול להשליך לזרוע, וכאבים בכיפוף כתף או מרפק ובהרמת היד בייחוד עם התנגדות",
            "חולשת מכופפי כף היד וכאב המתגבר ב-PF ו-Grip",
            "אסימטריה בגובה הכתפיים",
        ],
        "answer": 1,
        "anatomy_components": ["Biceps Brachii"],
    },
    {
        "id": 1062,
        "question": "אילו בורסות מרכזיות בכתף מוזכרות במצגת בהקשר של Bursitis?",
        "options": [
            "Prepatellar bursa, Suprapatellar bursa ו-Trochanteric bursa",
            "Subacromial bursa בלבד",
            "Subdeltoid bursa ו-Trochanteric bursa",
            "Subdeltoid bursa, Subcoracoid bursa ו-Subacromial bursa",
        ],
        "answer": 3,
        "anatomy_components": ["Subacromial Bursa", "Subdeltoid Bursa"],
    },
    {
        "id": 1063,
        "question": "מהם התסמינים של Bursitis בכתף?",
        "options": [
            "כאב בהרמת היד, הגבלה בתנועה, כאב בלילה ובשכיבה על הצד ורגישות מקומית למישוש",
            "נעילה של האצבע במצב כפיפה ורגישות בבסיס האצבע",
            "כאב בשורש כף היד ובאזור ה-snuff box המתגבר באחיזת חפצים",
            "כאב באזור המפרק המתגבר בעיקר בתנועת Horizontal Adduction",
        ],
        "answer": 0,
        "anatomy_components": ["Subacromial Bursa"],
    },
    {
        "id": 1064,
        "question": "מהו מנגנון הפציעה ב-Bursitis לפי המצגת?",
        "options": [
            "אפילפסיה או התחשמלות",
            "נפילה על יד מושטת לפנים (FOOSH)",
            "שימוש יתר וטראומה",
            "אספקת דם נמוכה לרקמה",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1065,
        "question": "מה מאפיין את טווחי התנועה ב-Frozen Shoulder (Adhesive Capsulitis)?",
        "options": [
            "אובדן טווחי תנועה אקטיביים בלבד, כאשר הטווחים הפסיביים תקינים",
            "טווחי תנועה מלאים עם כאב רק בסוף הטווח",
            "אובדן טווחי תנועה פסיביים ואקטיביים בכל תנועות הכתף, עם הגבלה ניכרת ברוטציה חיצונית",
            "עלייה בטווחי התנועה עקב גמישות יתר של הקפסולה",
        ],
        "answer": 2,
        "anatomy_components": ["Glenohumeral Joint"],
    },
    {
        "id": 1066,
        "question": "מהם שלושת השלבים של כתף קפואה לפי סדרם?",
        "options": [
            "שלב הקיפאון, שלב הכאב, שלב ההפשרה",
            "שלב ההפשרה, שלב הכאב, שלב הקיפאון",
            "שלב הכאב, שלב הקיפאון, שלב ההפשרה",
            "שלב הכאב, שלב ההפשרה, שלב הקיפאון",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1067,
        "question": "אילו גורמי סיכון לכתף קפואה משנית מוזכרים במצגת?",
        "options": [
            "הריון והרמת התינוק",
            "עבודה עם כלים כבדים ופעילות חוזרנית של GRIP",
            "אוסטאופורוזיס ונפילה על הזרוע",
            "סוכרת, שבץ, חבלות ושברים, ניתוחים, חוסר תנועתיות או קיבוע ממושך ודלקות פרקים",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1068,
        "question": "מה נכון לגבי הטיפול בכתף קפואה לפי המצגת?",
        "options": [
            "בשני השלבים הראשונים הטיפול עדין וללא כאב, שלב ההפשרה הוא האפקטיבי ביותר לתרגול, ו-Manipulation Under Anesthesia (MUA) הוא מוצא אחרון",
            "יש להתחיל בתרגול אגרסיבי ומכאיב כבר בשלב הכאב",
            "Manipulation Under Anesthesia (MUA) הוא הטיפול הראשון שיש להציע לכל מטופל",
            "אין כל טיפול והמצב אינו חולף לעולם",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1069,
        "question": "אילו תנועות מגבירות את הכאב ב-Lateral Epicondylalgia (Tennis Elbow)?",
        "options": [
            "PF של שורש כף היד ו-Grip",
            "Horizontal Adduction של הכתף",
            "Ext של שורש כף היד (DF) ואצבעות, Grip, Supination והרמת חפצים",
            "תנועות האגודל עם Rad Deviation",
        ],
        "answer": 2,
        "anatomy_components": ["Lateral Epicondyle"],
    },
    {
        "id": 1070,
        "question": "אילו גורמים תורמים ל-Tennis Elbow לפי המצגת?",
        "options": [
            "הריון, סוכרת ועומס סטטי ממושך על האזור הפלמרי של כף היד",
            "שימוש יתר (ספורט/עבודה/פנאי), פעילות חדשה, פעילות חוזרנית של DF שורש כף היד ו/או GRIP, עבודה עם כלים כבדים וחולשת שרירים",
            "נפילה על יד מושטת לפנים והתחשמלות",
            "גמישות יתר ופגיעה בלברום",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1071,
        "question": "היכן ממוקמת הבעיה ב-Golfers Elbow (Medial Epicondylitis)?",
        "options": [
            "בגיד המשותף של מכופפי שורש כף היד באפיקונדיל המדיאלי",
            "בגיד המשותף של פושטי האמה באפיקונדיל הלטרלי",
            "בבורסה של המרפק",
            "בקפסולה המפרקית של המרפק",
        ],
        "answer": 0,
        "anatomy_components": [
            "Flexor Carpi Radialis",
            "Flexor Carpi Ulnaris",
            "Medial Epicondyle",
            "Pronator Teres",
        ],
    },
    {
        "id": 1072,
        "question": "מהם התסמינים של Golfers Elbow?",
        "options": [
            "כאב לטרלי במרפק שמתגבר ב-Supination ובהרמת חפצים",
            "נעילה של האצבע במצב כפיפה",
            "הפרעה תחושתית באצבעות 1-4",
            "כאבים מקומיים שיכולים להשליך לזרוע או לאמה, חולשת מכופפי כף היד וכאב המתגבר בתנועות PF ו-Grip",
        ],
        "answer": 3,
        "anatomy_components": ["Medial Epicondyle"],
    },
    {
        "id": 1073,
        "question": "מה היחס בין שכיחות Golfers Elbow לשכיחות מרפק טניס הלטרלי?",
        "options": [
            "נפוץ פי 4-7 יותר מהמרפק הלטרלי",
            "הרבה פחות נפוץ – ביחס של 1:4 עד 1:7",
            "שכיחות זהה לחלוטין בין השניים",
            "פחות נפוץ, ביחס של 1:100",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1074,
        "question": "היכן ממוקם השבר ב-Colles' Fracture?",
        "options": [
            "בחלק הפרוקסימלי של עצם ה-Ulna",
            "בעצם ה-Scaphoid",
            "בחלק הדיסטלי של עצם ה-Radius",
            "בחלק הדיסטלי של ה-Humerus",
        ],
        "answer": 2,
        "anatomy_components": ["Radius"],
    },
    {
        "id": 1075,
        "question": "מהו מנגנון הפציעה ב-Colles' Fracture?",
        "options": [
            "נפילה על יד מושטת לפנים (FOOSH) כאשר שורש כף היד במנח DF",
            "חבלה ישירה לזרוע הדורשת כוח רב",
            "נפילה על הצד",
            "90° Abd + Ext rot",
        ],
        "answer": 0,
        "anatomy_components": ["Radius"],
    },
    {
        "id": 1076,
        "question": "מהם הסיבוכים האפשריים של Colles' Fracture?",
        "options": [
            "Avascular necrosis (AVN) של העצם",
            "פגיעה בכלי דם ועצבים המתבטאת ב-Drop wrist",
            "פריקות חוזרות ותת פריקות",
            "דפורמציה, הגבלה בטווחי תנועה ופגיעה עצבית (מדיאן)",
        ],
        "answer": 3,
        "anatomy_components": ["Radius"],
    },
    {
        "id": 1077,
        "question": "מהם הסימפטומים של Scaphoid fracture?",
        "options": [
            "אסימטריה בגובה הכתפיים והיד תלויה לצד הגוף",
            "כאב באזור המפרק המתגבר בתנועת Horizontal Adduction",
            "בלט במרכז השריר – Popeye sign",
            "כאב בשורש כף היד ובאזור ה-snuff box, הגבלה בטווחי תנועה וכאב באחיזת חפצים",
        ],
        "answer": 3,
        "anatomy_components": ["Scaphoid"],
    },
    {
        "id": 1078,
        "question": "מה מאפיין את האבחון של Scaphoid fracture?",
        "options": [
            "מאובחן בקלות בצילום רנטגן כבר ביום הפציעה",
            "ניתן לאבחון רק במהלך ניתוח",
            "לעיתים קשה לזיהוי בצילום רנטגן, בעיקר בימים הראשונים",
            "מאובחן על סמך בדיקת הדמיה של הכתף",
        ],
        "answer": 2,
        "anatomy_components": ["Scaphoid"],
    },
    {
        "id": 1079,
        "question": "על איזה מבנה מופעל לחץ ב-Carpal Tunnel Syndrome?",
        "options": ["העצב הרדיאלי", "העצב המדיאני", "גידי האגודל", "הבורסה הסובאקרומיאלית"],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1080,
        "question": "מהם התסמינים של Carpal Tunnel Syndrome?",
        "options": [
            "כאב בחלק הרדיאלי של שורש כף היד מעל האגודל המתגבר בתנועות האגודל",
            "כאב בשורש כף היד ובאזור ה-snuff box",
            "תסמינים המתחילים בהדרגה, הפרעה תחושתית באצבעות 1-4, קושי בפעולות grip ובמוטוריקה עדינה, ונימול שעלול להתגבר בלילה",
            "נעילה של האצבע במצב כפיפה עם רגישות בבסיס האצבע",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1081,
        "question": "אילו גורמים משפיעים על Carpal Tunnel Syndrome לפי המצגת?",
        "options": [
            "אוסטאופורוזיס וגיל מבוגר",
            "אפילפסיה והתחשמלות",
            "גמישות יתר ופגיעה בלברום",
            "סוכרת, עומס או שימוש יתר (ספורט/עבודה), עומס סטטי ממושך על האזור הפלמרי של כף היד, ולאחר שברי אמה וכף יד",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1082,
        "question": "היכן ממוקמת הפתולוגיה ב-De Quervain's Syndrome?",
        "options": [
            "טנדינופתיה של גידי האגודל",
            "טנדינופתיה של הגיד המשותף של פושטי האמה",
            "לחץ על העצב המדיאני בתעלה הקרפלית",
            "שבר בחלק הדיסטלי של הרדיוס",
        ],
        "answer": 0,
        "anatomy_components": ["Extensor Pollicis Brevis", "Extensor Pollicis Longus"],
    },
    {
        "id": 1083,
        "question": "מהם התסמינים של De Quervain's Syndrome?",
        "options": [
            "הפרעה תחושתית באצבעות 1-4 המתגברת בלילה",
            "כאב בחלק הרדיאלי של שורש כף היד מעל האגודל, השלכת כאב אפשרית לאגודל ולכף היד, וכאב המתגבר בתנועות האגודל",
            "כאב באזור ה-snuff box המתגבר באחיזת חפצים והגבלה בטווחי תנועה",
            "נעילה של האגודל במצב כפיפה עם רגישות בבסיסו",
        ],
        "answer": 1,
        "anatomy_components": ["Extensor Pollicis Brevis"],
    },
    {
        "id": 1084,
        "question": "אילו גורמים תורמים ל-De Quervain's Syndrome?",
        "options": [
            "סוכרת ועומס סטטי ממושך על האזור הפלמרי של כף היד",
            "נפילה על יד מושטת לפנים (FOOSH)",
            "תנועה חוזרנית של Grip עם Rad Deviation, הריון והרמת התינוק",
            "עבודה עם כלים כבדים ופעילות חוזרנית של DF שורש כף היד",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1085,
        "question": "מהי הפתופיזיולוגיה המשוערת של Trigger finger?",
        "options": [
            "לחץ על העצב המדיאני",
            "אספקת דם נמוכה לעצם",
            "הידבקויות בקפסולה המפרקית",
            "היצרות של מעטפת הגיד או עיבוי של הגיד",
        ],
        "answer": 3,
        "anatomy_components": ["Flexor Digitorum Profundus", "Flexor Digitorum Superficialis"],
    },
    {
        "id": 1086,
        "question": "מהם התסמינים של Trigger finger?",
        "options": [
            "נעילה של האצבע במצב כפיפה, עם או ללא כאב, ורגישות למישוש בבסיס האצבע",
            "כאב בחלק הרדיאלי של שורש כף היד המתגבר בתנועות האגודל",
            "הפרעה תחושתית באצבעות 1-4",
            "הגבלה בכל טווחי התנועה של שורש כף היד",
        ],
        "answer": 0,
        "anatomy_components": ["Flexor Digitorum Profundus"],
    },
    {
        "id": 1087,
        "question": "מה מוזכר במצגת כקשור אפשרי להתפתחות Trigger finger?",
        "options": [
            "נפילה על יד מושטת לפנים (FOOSH)",
            "כפיפה ממושכת – נשיאת שקיות קניות, טיפוס הרים, כתיבה ממושכת ואחיזה ממושכת של כלים",
            "הריון והרמת התינוק",
            "אוסטאופורוזיס וגיל מבוגר",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1088,
        "question": "היכן ממוקמת הבעיה ב-Pulled (Nursemaid's) Elbow?",
        "options": [
            "ה-Ulnar Collateral lig. נקרע מה-Medial epicondyle",
            "ראש הרדיוס מחליק דרך ה-Annular ligament",
            "הבורסה שמאחורי האולקרנון מתמלאת בנוזל דלקתי",
            "הקצה הדיסטלי של הרדיוס נשבר ונעתק כלפי חוץ",
        ],
        "answer": 1,
        "anatomy_components": ["Annular Ligament", "Radius"],
    },
    {
        "id": 1089,
        "question": "באיזה גיל שכיח Pulled (Nursemaid's) Elbow ובאיזה מנגנון הוא נגרם?",
        "options": [
            "גילאים 1-3, במשיכה פתאומית של האמה",
            "גילאים 1-3, בנפילה על המרפק הכפוף",
            "גילאים 10-15, בפעילות ספורטיבית חוזרת",
            "מעל גיל 60, בנפילה על כף יד פשוטה",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1090,
        "question": "היכן ממוקמת הבעיה ב-Olecranon bursitis?",
        "options": [
            "בגיד המחבר את מפרק המרפק לשרירי האמה",
            "ב-Annular ligament הסובב את ראש הרדיוס",
            "בסחוס המשולש (Triangular Cartilage) של שורש כף היד",
            "בשק (בורסה) מלא הנוזלים שבין עצם המרפק לעור, מאחורי המפרק",
        ],
        "answer": 3,
        "anatomy_components": ["Elbow Joint"],
    },
    {
        "id": 1091,
        "question": "מהם הסימנים האופייניים ל-Olecranon bursitis?",
        "options": [
            "כאב חזק בחזית המרפק המחמיר בהרמת חפצים כבדים",
            "חוסר תחושה ונימול בקצות האצבעות",
            "נפיחות ורגישות מאחורי מפרק המרפק",
            "הגבלה בסופינציה ובפרונציה בלבד, ללא כאב",
        ],
        "answer": 2,
        "anatomy_components": ["Elbow Joint"],
    },
    {
        "id": 1092,
        "question": "היכן מופיע הכאב בדלקת גיד הדו-ראשי (Bicep tendonitis)?",
        "options": [
            "כאב חזק בחזית המרפק",
            "כאב בגב המרפק",
            "כאב בצד החיצוני של המרפק",
            "כאב בצד הרדיאלי של שורש כף היד",
        ],
        "answer": 0,
        "anatomy_components": ["Biceps Brachii"],
    },
    {
        "id": 1093,
        "question": "מה גורם בדרך כלל לדלקת גיד הדו-ראשי (Bicep tendonitis) לפי המצגת?",
        "options": [
            "נפילה על כף יד פשוטה",
            "משיכה פתאומית של האמה",
            "שימוש חוזר בשריר, כמו הרמת חפצים כבדים",
            "זיהום חיידקי שהתפשט מהעור",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1094,
        "question": "דלקת גידים של התלת-ראשי (Tricep tendonitis) גורמת לכאב היכן, וכתוצאה מאיזו תנועה?",
        "options": [
            "כאב בחזית המרפק, כתוצאה מתנועות כיפוף חוזרות",
            "כאב בגב המרפק, כתוצאה מתנועות פשיטה חוזרות עם התנגדות",
            "כאב בצד הפנימי של המרפק, כתוצאה מתנועות סופינציה חוזרות",
            "כאב בשורש כף היד, כתוצאה מסטייה אולנרית חוזרת",
        ],
        "answer": 1,
        "anatomy_components": ["Triceps"],
    },
    {
        "id": 1095,
        "question": "לפי המצגת, איזו אוכלוסייה חווה לעיתים קרובות דלקת גידים של התלת-ראשי (Tricep tendonitis)?",
        "options": ["ילדים בגילאי 1-3", "נשים לאחר גיל המעבר", "רצי מרתון", "מרימי משקולות"],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1096,
        "question": "מהם השברים הנפוצים ביותר במפרק המרפק?",
        "options": [
            "שברים ב-Medial epicondyle ושברים ב-Capitulum",
            "שברים בקצה הדיסטלי של הרדיוס ושברים ב-Scaphoid",
            "שברי אולקרנון (Olecranon) ושברים בראש הרדיוס",
            "שברים בעצמות המסרק (Metacarpals) ובגלילים (Phalanges)",
        ],
        "answer": 2,
        "anatomy_components": ["Radius", "Ulna"],
    },
    {
        "id": 1097,
        "question": "מה נכון לגבי פריקת מפרק המרפק (Elbow dislocation) לפי המצגת?",
        "options": [
            "היא הפציעה השכיחה ביותר במרפק ומתרחשת בעיקר בילדים",
            "היא אינה נפוצה, אך יכולה להתרחש בנפילה על כף היד ולגרום להפרדת העצמות",
            "היא נגרמת תמיד מזיהום בשק הבורסה שמאחורי המרפק",
            "היא מתרחשת רק במקביל לשבר בראש הרדיוס",
        ],
        "answer": 1,
        "anatomy_components": ["Elbow Joint"],
    },
    {
        "id": 1098,
        "question": "מה מבדיל בין Colles fracture לבין Smith's fracture?",
        "options": [
            "Colles הוא שבר באולנה ו-Smith הוא שבר ברדיוס",
            "Colles מתרחש בילדים ו-Smith במבוגרים",
            "ב-Colles ההיסט הוא כלפי חוץ (Outward) וב-Smith כלפי פנים (Inward)",
            "Colles הוא שבר פתוח ו-Smith הוא שבר סגור",
        ],
        "answer": 2,
        "anatomy_components": ["Radius"],
    },
    {
        "id": 1099,
        "question": "מהו המנגנון האופייני לשבר בעצם ה-Scaphoid?",
        "options": [
            "מכה ישירה על גב כף היד",
            "משיכה פתאומית של האמה",
            "תנועות פשיטה חוזרות עם התנגדות",
            "נפילה על כף יד פשוטה (FOOSH - Fall On Outstretched Hand)",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1100,
        "question": "לפי המצגת, באיזה אזור אנטומי של שורש כף היד ממוקמת עצם ה-Scaphoid?",
        "options": [
            "ב-Anatomic snuffbox, בין גידי ה-Extensor pollicis longus וה-Extensor pollicis brevis",
            "מעל האולקרנון, בגב המרפק",
            "בצד האולנרי, בין ה-Lunate ל-Pisiform",
            "בגב כף היד, מעל ה-Hamate",
        ],
        "answer": 0,
        "anatomy_components": ["Scaphoid"],
    },
    {
        "id": 1101,
        "question": "מדוע שבר בעצם ה-Scaphoid עלול לגרום ל-Avascular Necrosis?",
        "options": [
            "מפני שהעצם אינה מכוסה בסחוס מפרקי",
            "מפני שהעצם ניזונה מה-Radial artery ואספקת הדם שלה נפגעת בשבר",
            "מפני שהעצם ממוקמת מחוץ לקופסית המפרק",
            "מפני שהעצם מתחברת ישירות לסחוס המשולש",
        ],
        "answer": 1,
        "anatomy_components": ["Scaphoid"],
    },
    {
        "id": 1102,
        "question": "לפי המצגת, כיצד מקובע שבר בעצם ה-Scaphoid?",
        "options": [
            "בעזרת בורג (Scaphoid Screw)",
            "בגבס בלבד, ללא כל קיבוע פנימי",
            "בעזרת פלטה וברגים על גב הרדיוס",
            "בעזרת מסמור תוך-לשדי של האולנה",
        ],
        "answer": 0,
        "anatomy_components": ["Scaphoid"],
    },
    {
        "id": 1103,
        "question": "לפי המצגת, כיצד מסווגים שברים בעצמות המסרק (Metacarpal fractures)?",
        "options": [
            "לפי מספר קווי השבר בלבד",
            "לפי גיל הנפגע",
            "לפי מיקום השבר בעצם: Head, Neck, Shaft ו-Base",
            "לפי כיוון ההיסט: Outward או Inward",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1104,
        "question": "על פי השקף, מהם המקורות האפשריים לכאבי צוואר?",
        "options": ["שרירי, דיסקים, מפרקי ועצבי", "שרירי ועצבי בלבד", "מפרקי בלבד", "וסקולרי בלבד"],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1105,
        "question": "מהם התסמינים המאפיינים כאבי צוואר?",
        "options": [
            "אי שליטה על סוגרים וירידה תחושתית באזור האוכף",
            "הגבלה בתנועה, כאבים המקרינים אל השכמה והזרוע (לעיתים לבית השחי או לחזה), חולשה ונימול",
            "נוקשות בוקר מעל שעה וירידה בתנועתיות בית החזה",
            "כאב דו צדדי קדמי ללא רגישות למגע",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1106,
        "question": "אילו סימנים בכאבי צוואר דורשים בדיקה רפואית?",
        "options": [
            "הגבלה בתנועות צוואר בלבד",
            "רגישות למישוש בשרירי הצוואר בלבד",
            "הפרעות בהליכה/נפילות, סחרחורות, הפרעות בדיבור, כפל ראייה (דיפלופיה), בחילות וצלצולים באוזניים (טינטון)",
            "כאב ראש חד צדדי המחמיר בסוף היום",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1107,
        "question": "מהו המקור המשוער של Cervicogenic Headache?",
        "options": [
            "היצרות תעלת חוט השדרה",
            "ירידה באספקת הדם לחלקו האחורי של המוח",
            "מתח בשרירי הפנים בלבד",
            "מפרקים ודיסקים באזור הצוואר",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1108,
        "question": "מה מאפיין את התסמינים של Cervicogenic Headache?",
        "options": [
            "כאב חד צדדי לרוב, מושפע מתנועות צוואר או ממנח סטטי לאורך זמן, עם רגישות למישוש באזור חוליות צוואריות",
            "כאב דו צדדי לרוב קדמי, ללא רגישות לאור וקול",
            "סחרחורת, כפל ראייה וקושי בבליעה",
            "כאב המחמיר בלילה וללא קשר לתנועה",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1109,
        "question": "היכן ממוקם הכאב ב-Tension type headache?",
        "options": ["חד צדדי, לרוב עורפי", "דו צדדי, לרוב קדמי", "חד צדדי סביב העין בלבד", "מפושט בכל הגוף"],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1110,
        "question": "מה מאפיין את הסימפטומים של Tension type headache?",
        "options": [
            "כאב פועם עוצמתי המלווה בבחילות והקאות",
            "כאב המלווה בכפל ראייה ובנפילות פתאומיות",
            "עוצמה קלה עד בינונית, כאב לוחץ לא פועם, ללא רגישות לאור/קול וללא בחילות והקאות",
            "כאב המלווה באי שליטה על סוגרים",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1111,
        "question": "היכן ממוקמת הבעיה ב-Vertebro-Basilar Insufficiency (VBI)?",
        "options": [
            "היצרות של תעלת חוט השדרה באזור המותני",
            "החלקה קדמית של חוליה על גבי חברתה",
            "דלקת אוטואימונית של מפרקי עמוד השדרה",
            "ירידה באספקת הדם לחלקו האחורי של המוח",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1112,
        "question": "מהם 5 ה-D's המהווים תסמינים של Vertebrobasilar Insufficiency (VBI)?",
        "options": [
            "Dizziness, Diplopia, Dysarthria, Dysphagia, Drop Attack",
            "Dizziness, Diplopia, Dyspnea, Dysuria, Dystonia",
            "Dysarthria, Dysphagia, Dyslexia, Diplopia, Dizziness",
            "Drop Attack, Dizziness, Dyspepsia, Diplopia, Dysarthria",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1113,
        "question": "כיצד מתבצעת בדיקת הפרובוקציה ל-Vertebrobasilar Insufficiency (VBI)?",
        "options": [
            "כיפוף גו קדימה ובדיקת בליטה של הצלעות",
            "החזקה בסוף הטווח האקטיבי של Neck Extension למשך 10 שניות, ולאחר מכן סוף טווח של Neck Rotation ושל Rotation + Extension",
            "הרמת רגל ישרה בשכיבה על הגב",
            "מישוש נקודות רגישות באזור הצוואר והראש",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1114,
        "question": "מהו מקור הכאב ב-Whiplash Injury על פי השקף?",
        "options": [
            "תמיד פריצת דיסק צווארית",
            "תמיד שבר בחוליה צווארית",
            "אינו ידוע: מפרקים, רצועות, שרירים, עצבים",
            "היצרות של תעלת חוט השדרה",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1115,
        "question": "מהו המנגנון של Whiplash Injury (\"צליפת שוט\")?",
        "options": [
            "עומס חוזר של Extension בעמוד השדרה המותני",
            "עיבוי רצועות ואוסטאופיטים המצרים את תעלת חוט השדרה",
            "מחלה דלקתית כרונית מערכתית אוטואימונית",
            "טראומה, לרוב עקב תאונת דרכים, עם Hyperextension ולאחריו Hyperflexion של הצוואר",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1116,
        "question": "מהן ההמלצות לטיפול ב-Whiplash Injury?",
        "options": [
            "חזרה הדרגתית לעבודה ולפעילויות היומיום, תרגול לתנועתיות צוואר, שילוב פעילות אירובית, מתיחות וחיזוקים בהדרגה",
            "קיבוע מוחלט של הצוואר עד לחלוף הכאב",
            "ניתוח מיידי לקיבוע החוליות הצוואריות",
            "הימנעות מוחלטת מפעילות גופנית למשך שנה",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1117,
        "question": "מה המשמעות של Non-specific LBP, המהווה כ-90% ממקרי כאבי הגב?",
        "options": [
            "הכאב נובע תמיד מפריצת דיסק",
            "המקור האנטומי המדויק שאחראי לתסמינים אינו ידוע",
            "הכאב נובע ממחלה סיסטמית רצינית",
            "ההגדרה ניתנת רק לאחר MRI המדגים ממצא",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1118,
        "question": "מהו שיעור האוכלוסייה הכללית שתחווה כאבי גב תחתון במהלך החיים?",
        "options": ["כ-1%", "כ-2%-3%", "כ-65%-80%", "כ-20%-30%"],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1119,
        "question": "מהי הפרוגנוזה של כאבי גב תחתון על פי השקף?",
        "options": [
            "ברוב המקרים הכאב הופך כרוני ואינו חולף",
            "רק 10% מהמקרים חולפים ללא ניתוח",
            "הכאב חולף תוך 3 חודשים וכמעט ואינו חוזר",
            "ב-90% מהמקרים הכאב יחלוף מעצמו תוך כ-3 חודשים, אך יש שיעור גבוה של חזרה",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1120,
        "question": "מהו המנגנון של פריצת דיסק?",
        "options": [
            "ה-Nucleus Pulposus פורץ דרך ה-Annulus Fibrosus, ברוב המקרים לכיוון אחורי-צידי",
            "ה-Annulus Fibrosus פורץ דרך ה-Nucleus Pulposus לכיוון קדמי",
            "גוף החוליה נסדק ולוחץ על הדיסק מלמעלה",
            "הדיסק מחליק קדימה יחד עם החוליה שמעליו",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1121,
        "question": "מה נכון לגבי המהלך של פריצת דיסק?",
        "options": [
            "פריצת דיסק היא תמיד סימפטומטית ומחייבת ניתוח",
            "לא תמיד סימפטומטית, ובכ-90% מהמקרים הסימפטומטיים יהיה שיפור במהלך 3 חודשים",
            "בקע ופריצה לעולם אינם נספגים",
            "שיפור מתרחש רק לאחר שנה לפחות",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1122,
        "question": "היכן ממוקמת הבעיה ב-Spinal Stenosis?",
        "options": [
            "היצרות של העורק הוורטברלי באזור הצווארי",
            "קרע ב-Annulus Fibrosus בגובה L4-L5-S1",
            "היצרות תעלת חוט השדרה, לרוב באזור L3-L4-L5",
            "שבר מאמץ באזור קשתות עמוד השדרה",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1123,
        "question": "מה מאפיין את הסימפטומים של Spinal Stenosis?",
        "options": [
            "כאב המוחמר בכיפוף גו קדימה ומוקל בפשיטה",
            "כאב ראש חד צדדי המוחמר במנח סטטי",
            "אי שליטה על סוגרים וירידה תחושתית באזור האוכף",
            "נימול, חולשה וכאב המוחמרים בביצוע EXT גו, צליעה נוירוגנית, ולאחר מנוחה קצרה בישיבה (כיפוף גב) מצליחים להמשיך בהליכה",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1124,
        "question": "מהם הגורמים ל-Spinal Stenosis?",
        "options": [
            "עיבוי רצועות עמוד השדרה, אוסטאופיטים, שברי דחיסה של החוליות, בלט/פריצת דיסק, ספונדילוליסטזיס, OA, RA וגידולים",
            "תאונת דרכים בלבד",
            "מקור אידיופתי בכ-80% מהמקרים",
            "מחלה אוטואימונית בלבד",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1125,
        "question": "היכן ממוקם הפגם/שבר המאמץ ב-Spondylolysis?",
        "options": ["בגוף החוליה", "באזור קשתות עמוד השדרה", "בדיסק הבין חולייתי", "במפרק הסקרואיליאק"],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1126,
        "question": "מהם הסימפטומים של Spondylolysis?",
        "options": [
            "כאב המוקל בפשיטת גו ומוחמר בכיפוף",
            "כאב ראש חד צדדי המלווה בסחרחורות",
            "כאב גב באזור השבר, המופיע בתנועות גו ובעיקר Extension, עם הקרנות אפשריות לאזור הישבן והרגליים",
            "נוקשות בוקר מעל שעה וירידה בתנועתיות בית החזה",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1127,
        "question": "באיזה אזור של עמוד השדרה מתרחשת Spondylolysthesis לרוב?",
        "options": ["בחוליות הצוואריות", "בחוליות הגביות", "בעצם העצה (Sacrum)", "בחוליות המותניות"],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1128,
        "question": "מהי Ankylosing Spondylitis?",
        "options": [
            "שבר מאמץ בקשתות החוליות עקב Overuse",
            "דלקת חוליות מקשחת - מחלה דלקתית כרונית מערכתית אוטואימונית הפוגעת במפרקי עמוד השדרה",
            "היצרות של תעלת חוט השדרה עקב אוסטאופיטים",
            "סטייה של החוליות מעל 10 מעלות במישור הקורונלי",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1129,
        "question": "מהם התסמינים של Ankylosing Spondylitis?",
        "options": [
            "כאבים המתגברים בערב ומוקלים לחלוטין בבוקר",
            "כאב המוקל בישיבה ומוחמר בהליכה בלבד",
            "בתחילה כאבים ונוקשות באזור גב תחתון, תסמינים המתגברים בבוקר עם נוקשות בוקר מעל שעה, וירידה בתנועתיות בית החזה ועמוד השדרה",
            "אי שליטה על סוגרים וחולשה דו צדדית בגפיים תחתונות",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1130,
        "question": "איזה עיוות בעמוד השדרה גורם Ankylosing Spondylitis, ובאיזה גיל היא מתחילה בממוצע?",
        "options": [
            "סקוליוזיס, החל בממוצע בגיל 40-50",
            "לורדוזיס מותנית מוגברת, החל בממוצע בגיל 60 ומעלה",
            "קיפוזיס, החל בממוצע בעשור השישי לחיים",
            "קיפוזיס, החל בממוצע בעשור השלישי לחיים (18-30)",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1131,
        "question": "כיצד מוגדרת Scoliosis (עקמת)?",
        "options": [
            "סטייה של החוליות מעל 10 מעלות במישור הקורונלי, ביחס לקו האמצע",
            "סטייה של החוליות מעל 10 מעלות במישור הסגיטלי",
            "כיפוף יתר של עמוד השדרה הגבי במישור הסגיטלי",
            "החלקה קדמית של חוליה מעל 10 מעלות",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1132,
        "question": "מהם הסימנים של Scoliosis (עקמת)?",
        "options": [
            "נוקשות בוקר מעל שעה וירידה בתנועתיות בית החזה",
            "אסימטריה שרירית, בליטת צלעות או שכמה כתוצאה מרוטציה של בית החזה, הבדל במנח האגן או באורך גפיים, ובמקרים חמורים בעיות לב וריאות",
            "סחרחורת, כפל ראייה וקושי בבליעה",
            "כאב המוקל בכיפוף גו ומוחמר בפשיטה",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1133,
        "question": "מהי בדיקת Adam's Forward bend test ולאיזו פתולוגיה היא משמשת לאבחון?",
        "options": [
            "פשיטת צוואר למשך 10 שניות - בדיקת פרובוקציה ל-VBI",
            "הרמת רגל ישרה - בדיקה לפריצת דיסק מותנית",
            "כיפוף גו קדימה לזיהוי בליטה - בדיקה לאבחון Scoliosis (עקמת)",
            "מישוש חוליות צוואריות - בדיקה ל-Cervicogenic Headache",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1134,
        "question": "באיזה גובה בעמוד השדרה ממוקמת הפגיעה ב-Cauda Equina Syndrome?",
        "options": ["C5-T1", "L1-L4", "L4-L5-S1", "L2-S5"],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1135,
        "question": "מהם הסימנים של Cauda Equina Syndrome?",
        "options": [
            "ירידה תחושתית באזור האוכף, אי שליטה על סוגרים, חולשה עד שיתוק דו צדדי של גפיים תחתונות ופגיעה בתפקוד המיני",
            "כאב חד צדדי המקרין לישבן, ללא הפרעה בסוגרים",
            "נוקשות בוקר וירידה בתנועתיות בית החזה",
            "סחרחורת, קושי בדיבור ונפילות פתאומיות",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1136,
        "question": "מהם הדגלים האדומים בכאבי גב?",
        "options": [
            "חרדה, דיכאון, קטסטרופיזציה ו-Fear avoidance behaviour",
            "סרטן, זיהום, טראומה ותסמונת זנב הסוס",
            "עקמת, קיפוזיס, לורדוזיס וספונדילוליזיס",
            "סחרחורת, כפל ראייה, קושי בדיבור וקושי בבליעה",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1137,
        "question": "אילו סימנים בכאבי גב מעלים חשד לסרטן כדגל אדום?",
        "options": [
            "כאב המוחמר בפשיטת גו ומוקל בישיבה",
            "חום גבוה לאחרונה וזריקה ספינלית/קטטר אפידורלי",
            "היסטוריה של סרטן בעבר, ירידה חדה ולא מוסברת במשקל, כאב שמוחמר בלילה, ללא הקלה במנוחה וללא קשר לתנועה",
            "כאב דו צדדי קדמי בראש ללא בחילות",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1138,
        "question": "למה קשורים הדגלים הצהובים בכאבי גב?",
        "options": [
            "למחלה סיסטמית רצינית",
            "לפגיעה נוירולוגית מתקדמת",
            "לצורך בהתערבות ניתוחית דחופה",
            "לכאב כרוני",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1139,
        "question": "איזה מהבאים הוא דגל צהוב בכאבי גב?",
        "options": [
            "Fear avoidance behaviour",
            "אי שליטה על סוגרים",
            "חום גבוה לאחרונה",
            "ירידה חדה ולא מוסברת במשקל",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1140,
        "question": "לפי הסיווג Proximal femoral fracture types, היכן עובר קו השבר בשבר מסוג subcapital ?",
        "options": [
            "בבסיס צוואר הפמור (basicervical)",
            "באמצע צוואר הפמור (midcervical)",
            "מיד מתחת לראש הפמור, במעבר בין הראש לצוואר",
            "מתחת לטרוכנטרים, באזור ה-subtrochanteric",
        ],
        "answer": 2,
        "anatomy_components": ["Femur"],
    },
    {
        "id": 1141,
        "question": "אילו שברים בפמור הפרוקסימלי מסווגים בשקופית כ-extra-capsular ?",
        "options": [
            "pertrochanteric/intertrochanteric ו-subtrochanteric",
            "subcapital ו-midcervical",
            "subcapital בלבד",
            "כל שברי צוואר הפמור",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1142,
        "question": "בסיווג שברי צוואר הפמור המוצג בשקופית (דרגות 1-4), מה מאפיין את דרגות 3 ו-4 ?",
        "options": [
            "השבר הוא extra-capsular",
            "השבר הוא undisplaced – ללא תזוזה של מקטעי השבר",
            "מדובר במפרק תקין ללא שבר",
            "השבר הוא displaced – עם תזוזה של מקטעי השבר",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1143,
        "question": "בצילום מפרק הירך עם שינויים ניווניים (Degenerative changes Osteoarthritis), אילו ממצאים מסומנים בהשוואה למפרק תקין ?",
        "options": [
            "הרחבה של מרווח המפרק ודילול ה-greater trochanter",
            "Bone spurs והיצרות של מרווח המפרק (Joint space narrowing)",
            "קו שבר subcapital ותזוזה של ראש הפמור",
            "היצרות של ה-obturator foramen והרס ה-symphysis pubis",
        ],
        "answer": 1,
        "anatomy_components": ["Acetabulum", "Hip Joint"],
    },
    {
        "id": 1144,
        "question": "היכן ממוקם ה-Joint space שהיצרותו נצפית במפרק הירך ב-Osteoarthritis ?",
        "options": [
            "בין ה-sacrum ל-ilium (Sacroiliac Joint)",
            "בין ה-greater trochanter ל-ilium",
            "בין שתי עצמות ה-pubis (symphysis pubis)",
            "בין ראש הפמור (Femoral Head) ל-acetabulum",
        ],
        "answer": 3,
        "anatomy_components": ["Acetabulum", "Femur", "Hip Joint"],
    },
    {
        "id": 1145,
        "question": "אילו ממצאים מסומנים בצילום הברך עם שינויים ניווניים (Degenerative changes Osteoarthritis) ?",
        "options": [
            "Osteophyte, sclerosis ומרווח מפרקי מוקטן (reduced joint space)",
            "Osteophyte, קרע ב-ACL ומרווח מפרקי מורחב",
            "Sclerosis, שבר subcapital ו-bone spurs",
            "מרווח מפרקי מורחב, קרע במניסקוס ונוזל במפרק",
        ],
        "answer": 0,
        "anatomy_components": ["Knee Joint"],
    },
    {
        "id": 1146,
        "question": "בין אילו מבנים נראה אובדן המרווח המפרקי (Loss of joint space) בברך עם Osteoarthritis ?",
        "options": [
            "בין ה-patella ל-tibia",
            "בין ה-tibia ל-fibula",
            "בין ה-femoral condyle ל-tibial condyle",
            "בין ה-femur ל-patella בלבד",
        ],
        "answer": 2,
        "anatomy_components": ["Femur", "Tibia", "Tibiofemoral Joint"],
    },
    {
        "id": 1147,
        "question": "מה מנגנון הפציעה האופייני לשבר אגן?",
        "options": [
            "כוחות דחיסה - נפילה מגובה או תאונת דרכים",
            "כוח Valgus ומכה בצד הלטרלי של הברך",
            "Plantar flexion + Inversion",
            "רוטציה של הפמור על טיביה מקובעת",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1148,
        "question": "אילו סכנות מאפיינות שבר אגן מורכב?",
        "options": [
            "קרע של ה-ACL בלבד",
            "מוקדי שבר מרובים, סכנת פגיעה באיברים פנימיים, סכנת פריקת SIJ ודימום",
            "אטרופיה של שריר ה-Quadriceps בלבד",
            "עיבוי של גיד אכילס",
        ],
        "answer": 1,
        "anatomy_components": ["Sacroiliac Joint"],
    },
    {
        "id": 1149,
        "question": "לפי סיווג Tile, מה מאפיין שבר אגן מסוג Type C?",
        "options": [
            "טבעת האגן יציבה",
            "טבעת האגן לא יציבה רוטציונית אך יציבה ורטיקלית",
            "טבעת האגן לא יציבה רוטציונית וגם ורטיקלית",
            "שבר שאינו מערב כלל את טבעת האגן",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1150,
        "question": "לפי סיווג Tile, מה מתאר תת-הסוג B1?",
        "options": [
            "Bilateral",
            "Lateral compression, ipsilateral",
            "Avulsion injury שאינו מערב את הטבעת",
            "Open book",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1151,
        "question": "היכן ממוקם השבר ב-Femoral neck fracture?",
        "options": [
            "בצוואר הירך, בין ראש הפמור לאזור האינטר-טרוכנטרי",
            "בגוף (shaft) של עצם הירך",
            "במשטח העליון של הטיביה",
            "באצטבולום",
        ],
        "answer": 0,
        "anatomy_components": ["Femur", "Hip Joint"],
    },
    {
        "id": 1152,
        "question": "באיזו אוכלוסייה נפוץ שבר צוואר הירך?",
        "options": [
            "בילדים בשנים הראשונות לחיים",
            "במבוגרים, ונפוץ בנשים יותר מגברים (אוסטאופורוזיס)",
            "בצעירים, ונפוץ בגברים יותר מנשים",
            "אין הבדל בשכיחות בין גילאים ומינים",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1153,
        "question": "מדוע צוואר הירך מועד לשבר?",
        "options": [
            "משום שאין בו אספקת דם כלל",
            "משום שהוא המפרק הגדול ביותר בגוף",
            "משום שהוא נקודת התורפה של העצם ואזור מעבר כוחות",
            "משום שהוא אזור תוך מפרקי נושא משקל של הטיביה",
        ],
        "answer": 2,
        "anatomy_components": ["Femur"],
    },
    {
        "id": 1154,
        "question": "אילו שתי קבוצות טיפול מוצגות עבור שבר צוואר הירך?",
        "options": [
            "ארטרוסקופיה וניקוי המפרק",
            "קיבוע בגבס בלבד או משיכה",
            "הזרקת סטרואידים או פיזיותרפיה בלבד",
            "Osteosyntheses (קיבוע פנימי) ו-Prostheses (משתלים)",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1155,
        "question": "באיזו אוכלוסייה נפוץ יותר Femoral shaft fracture?",
        "options": ["בצעירים", "בקשישים עם אוסטאופורוזיס", "בתינוקות בלבד", "בנשים לאחר גיל המעבר"],
        "answer": 0,
        "anatomy_components": ["Femur"],
    },
    {
        "id": 1156,
        "question": "מה מנגנון הפציעה ב-Femoral shaft fracture?",
        "options": [
            "כוח ולגוס מהצד הלטרלי של הברך",
            "חבלה ישירה או תאונת דרכים",
            "עומס יתר חוזר בריצה",
            "Plantar flexion + Inversion",
        ],
        "answer": 1,
        "anatomy_components": ["Femur"],
    },
    {
        "id": 1157,
        "question": "מהי הבעיה ב-Developmental/Congenital dysplasia of Hip (DDH/CDH)?",
        "options": [
            "פגיעה באספקת הדם לראש עצם הירך",
            "דלקת של הבורסה מעל הטרוכנטר הגדול",
            "ליקוי בהתפתחות מפרק הירך עם אצטבולום שטוח",
            "שחיקה של הסחוס המפרקי עם הגיל",
        ],
        "answer": 2,
        "anatomy_components": ["Acetabulum", "Hip Joint"],
    },
    {
        "id": 1158,
        "question": "מהם גורמי הסיכון ל-DDH/CDH?",
        "options": [
            "אלכוהוליזם ונטילת סטרואידים",
            "השמנת יתר ועומס יתר בריצה",
            "עישון וסוכרת",
            "גנטיקה, לידה במצג עכוז, מין נקבה ומנשא/עיטוף",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1159,
        "question": "מהם התסמינים של DDH/CDH?",
        "options": [
            "אסימטריה של קפלי העור, אסימטריה באורך רגליים והגבלת טווח אבדוקציה במפרק הירך",
            "צליל POP בזמן הפגיעה ונפיחות מיידית",
            "כאב חד באזור העקב בקימה מהמיטה",
            "קרפיטציות במפרק ה-patellofemoral",
        ],
        "answer": 0,
        "anatomy_components": ["Hip Joint"],
    },
    {
        "id": 1160,
        "question": "כיצד מאשרים אבחנה קלינית של DDH מעל גיל 3 חודשים?",
        "options": ["בבדיקת EMG", "בצילום רנטגן", "במיפוי עצמות", "בארטרוסקופיה"],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1161,
        "question": "מה מבצע הבודק במבחן Barlow?",
        "options": [
            "לחץ כלפי מעלה על ה-Greater trochanter בניסיון להחזיר את הירך למקומה",
            "מתיחה של הברך תוך הפעלת כוח ולגוס",
            "לחץ אחורי על הירך המדיאלית בניסיון לפרוק את הירך לאחור",
            "דחיסה של הפטלה כנגד הפמור",
        ],
        "answer": 2,
        "anatomy_components": ["Hip Joint"],
    },
    {
        "id": 1162,
        "question": "מה נחשב ממצא חיובי במבחן Barlow-Ortolani?",
        "options": [
            "צניחת האגן בצד הנגדי",
            "כאב מתגבר באבדוקציה אקטיבית",
            "הגבלה בטווח ה-Dorsi flexion",
            "קליק נמוש או נשמע",
        ],
        "answer": 3,
        "anatomy_components": ["Hip Joint"],
    },
    {
        "id": 1163,
        "question": "כיצד מחולקת האטיולוגיה של Osteoarthritis (OA) בשקף?",
        "options": [
            "אידיופתי - מסיבה לא ברורה, או משני - בעקבות טראומה או DDH/CDH",
            "זיהומי או אוטואימוני",
            "מולד או גנטי בלבד",
            "וסקולרי או נוירולוגי",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1164,
        "question": "מהם גורמי הסיכון ל-Osteoarthritis של מפרק הירך?",
        "options": [
            "אלכוהוליזם וטיפול בהקרנות",
            "השמנת יתר, פגיעות מפרקיות, הפרעות התפתחותיות מולדות וגיל",
            "לידה במצג עכוז ועיטוף",
            "כוח ולגוס ישיר על המפרק",
        ],
        "answer": 1,
        "anatomy_components": ["Hip Joint"],
    },
    {
        "id": 1165,
        "question": "מהם התסמינים של Osteoarthritis?",
        "options": [
            "צליל POP וחוסר יציבות של המפרק",
            "נעילות וקליקים מכניים",
            "כאב ונוקשות (בעיקר נוקשות בוקר) וקושי בדריכה ובתפקוד הדורש נשיאת משקל",
            "היעדר תסמינים לחלוטין בכל שלבי המחלה",
        ],
        "answer": 2,
        "anatomy_components": ["Hip Joint"],
    },
    {
        "id": 1166,
        "question": "מה נכון לגבי הקשר בין תוצאות צילום הרנטגן לתמונה הקלינית ב-OA?",
        "options": [
            "לא תמיד יש קורלציה בין תוצאות הרנטגן לתמונה הקלינית",
            "תמיד קיימת קורלציה מלאה בין השניים",
            "צילום הרנטגן אינו מדגים כלל שינויים ב-OA",
            "התמונה הקלינית תמיד חמורה יותר מממצאי הרנטגן",
        ],
        "answer": 0,
        "anatomy_components": [],
    },
    {
        "id": 1167,
        "question": "מהו הטיפול המוצע ב-OA של מפרק הירך?",
        "options": [
            "קיבוע בגבס למשך 6 שבועות",
            "ארטרוסקופיה לתפירת המניסקוס",
            "הפחתת גורמי סיכון - ירידה במשקל, הליכה עם אביזר עזר וחיזוק שרירים, ובניתוח - THR",
            "אין טיפול, המצב חולף מעצמו",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1168,
        "question": "מהי הבעיה ב-Avascular Necrosis of Hip (AVN)?",
        "options": [
            "פגיעה באספקת הדם לראש עצם הירך המובילה לנמק של העצם",
            "שחיקה של הסחוס המפרקי בשל עומס",
            "דלקת של הבורסה הטרוכנטרית",
            "ליקוי מולד בהתפתחות האצטבולום",
        ],
        "answer": 0,
        "anatomy_components": ["Femur", "Hip Joint"],
    },
    {
        "id": 1169,
        "question": "באיזה גיל ובאיזה מין נפוץ AVN של מפרק הירך?",
        "options": [
            "מעל גיל 70, נפוץ יותר בנשים",
            "גיל 30-50, נפוץ יותר בגברים",
            "בילדות המוקדמת, נפוץ יותר בבנות",
            "בגיל ההתבגרות, ללא הבדל בין המינים",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1170,
        "question": "מהם גורמי הסיכון ל-Osteonecrosis (AVN)?",
        "options": [
            "לידה במצג עכוז ועיטוף",
            "כוח ולגוס ישיר וכוח ורוס",
            "טראומה (שברים ופריקות), אלכוהוליזם, נטילת סטרואידים וטיפול בהקרנות/כימותרפיה",
            "ירידה בטווח ה-Dorsi flexion",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1171,
        "question": "מהם התסמינים של Osteonecrosis של מפרק הירך?",
        "options": [
            "נעילות וקליקים מכניים במפרק",
            "אסימטריה של קפלי העור",
            "כאב חד בעקב בקימה מהמיטה",
            "בשלבים הראשונים לרוב אין סימפטומים, לאחר מכן כאב המתפתח בהדרגה עם השלכה למפשעה ולעכוז, וצליעה",
        ],
        "answer": 3,
        "anatomy_components": ["Hip Joint"],
    },
    {
        "id": 1172,
        "question": "מה מוחלף בניתוח Total Hip Replacement (THR)?",
        "options": [
            "ראש הירך והאצטבולום",
            "ראש הירך בלבד",
            "המניסקוס המדיאלי והלטרלי",
            "הפטלה והמשטח המפרקי שלה",
        ],
        "answer": 0,
        "anatomy_components": ["Acetabulum", "Femur", "Hip Joint"],
    },
    {
        "id": 1173,
        "question": "מתי לרוב מבוצע ניתוח THR?",
        "options": [
            "מיד עם הופעת הכאב הראשון",
            "לרוב רק לאחר מיצוי טיפול שמרני או בעקבות שברים",
            "רק בילדים עם DDH",
            "רק בעקבות נקע במפרק הקרסול",
        ],
        "answer": 1,
        "anatomy_components": [],
    },
    {
        "id": 1174,
        "question": "אילו גישות ניתוחיות ל-THR מוצגות בשקף?",
        "options": ["מדיאלית ולטרלית בלבד", "עליונה ותחתונה", "קדמית, צידית ואחורית", "ארטרוסקופית בלבד"],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1175,
        "question": "מהם הסיבוכים האפשריים של THR?",
        "options": [
            "קרע ב-ACL ובמניסקוס",
            "דורבן בעצם העקב",
            "Hallux valgus",
            "זיהום, התרופפות ופריקת המשתל, DVT, תסחיף ריאתי והבדל באורך רגליים",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1176,
        "question": "היכן ממוקמת הבעיה ב-Greater Trochanteric Bursitis / Gluteus Medius Tendinopathy?",
        "options": [
            "בבורסה ובגיד ה-Gluteus Medius באזור הטרוכנטר הגדול",
            "בקפסולה של מפרק הברך",
            "ברצועה הצולבת הקדמית",
            "בפאשיה הפלנטרית של כף הרגל",
        ],
        "answer": 0,
        "anatomy_components": ["Gluteus Medius", "Greater Trochanter", "Trochanteric Bursa"],
    },
    {
        "id": 1177,
        "question": "מהם התסמינים של Greater Trochanteric Bursitis?",
        "options": [
            "כאב עמוק בברך המלווה בצליל POP",
            "כאב מקומי עם השלכה אפשרית לירך לטרלית אחורית, המוחמר בשכיבה על הצד, בעמידה, במדרגות ובריצה, ומוקל במנוחה",
            "כאב במפשעה בלבד ללא השלכה",
            "נוקשות בוקר באזור העקב",
        ],
        "answer": 1,
        "anatomy_components": ["Greater Trochanter", "Trochanteric Bursa"],
    },
    {
        "id": 1178,
        "question": "מה נמצא בבדיקה של Greater Trochanteric Bursitis / Gluteus Medius Tendinopathy?",
        "options": [
            "קליק נמוש במבחן Ortolani",
            "צניחת אגן בצד הנגדי בלבד",
            "רגישות מקומית במישוש וכאב מתגבר בביצוע ABD אקטיבי ו-ADD פסיבי",
            "הגבלה בטווח ה-Plantar flexion",
        ],
        "answer": 2,
        "anatomy_components": ["Gluteus Medius", "Greater Trochanter"],
    },
    {
        "id": 1179,
        "question": "מהם גורמי הסיכון ל-Greater Trochanteric Bursitis?",
        "options": ["אוסטאופורוזיס", "לידה במצג עכוז", "נטילת סטרואידים", "טראומה, עומס יתר והשמנת יתר"],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1180,
        "question": "חולשה של איזה שריר מתבטאת ב-Trendelenburg Sign?",
        "options": ["Gluteus Medius", "Quadriceps", "Gastrocnemius", "Iliopsoas"],
        "answer": 0,
        "anatomy_components": ["Gluteus Medius"],
    },
    {
        "id": 1181,
        "question": "מה רואים ב-Trendelenburg Sign בעמידה על רגל אחת?",
        "options": [
            "עלייה של האגן בצד הנגדי",
            "צניחה של האגן בצד הנגדי",
            "כפיפה של הברך בצד הנשען",
            "רוטציה חיצונית של הירך הנשענת",
        ],
        "answer": 1,
        "anatomy_components": ["Gluteus Medius"],
    },
    {
        "id": 1182,
        "question": "היכן ממוקם Tibial plateau fracture?",
        "options": [
            "בגוף עצם הירך",
            "בצוואר הירך",
            "באזור נושא משקל, תוך מפרקי, במשטח העליון של הטיביה",
            "בעצם העקב",
        ],
        "answer": 2,
        "anatomy_components": ["Knee Joint", "Tibia"],
    },
    {
        "id": 1183,
        "question": "מה מנגנון הפציעה ב-Tibial plateau fracture?",
        "options": [
            "פגיעה באנרגיה גבוהה כשהרגל במנח ורוס/ולגוס או בכפיפה - נפילה, תאונת דרכים או סקי",
            "עומס יתר חוזר בריצה ובריקוד",
            "Plantar flexion + Inversion",
            "עיטוף הדוק של התינוק",
        ],
        "answer": 0,
        "anatomy_components": ["Tibia"],
    },
    {
        "id": 1184,
        "question": "מהם התסמינים של Tibial plateau fracture?",
        "options": [
            "אסימטריה באורך רגליים",
            "נפיחות, כאב, חוסר יכולת לשאת משקל על הרגל והגבלה בטווחי התנועה",
            "קושי בנעילת נעליים וכאב במפרק ה-MTP",
            "כאבי בוקר בעקב בקימה מהמיטה",
        ],
        "answer": 1,
        "anatomy_components": ["Knee Joint", "Tibia"],
    },
    {
        "id": 1185,
        "question": "לפי סיווג Schatzker, מה מתאר Type I?",
        "options": [
            "Bicondylar fracture",
            "Central depression",
            "Dissociation of metaphysis and diaphysis",
            "Split",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1186,
        "question": "באיזה אספקט של הברך שכיחה יותר Knee Osteoarthritis?",
        "options": ["באספקט המדיאלי", "באספקט הלטרלי", "באספקט האחורי", "אין הבדל בשכיחות בין האספקטים"],
        "answer": 0,
        "anatomy_components": ["Knee Joint"],
    },
    {
        "id": 1187,
        "question": "אילו גורמים תורמים להתפתחות Knee OA?",
        "options": [
            "לידה במצג עכוז ועיטוף",
            "קרעים קודמים במניסקוס, שברים של המשטח המפרקי, ניתוחים, קרעים של הרצועות וולגוס/ורוס מוגבר",
            "נטילת סטרואידים וטיפול בהקרנות",
            "ירידה בטווח ה-Dorsi flexion",
        ],
        "answer": 1,
        "anatomy_components": ["Knee Joint", "Medial Meniscus"],
    },
    {
        "id": 1188,
        "question": "מהם התסמינים של Knee OA?",
        "options": [
            "צליל POP וחוסר יציבות של המפרק",
            "כאב מקומי חד באזור העקב",
            "קושי לשאת משקל, הגבלה בטווחי תנועה, דפורמציה ונוקשות בוקר",
            "אסימטריה של קפלי העור",
        ],
        "answer": 2,
        "anatomy_components": ["Knee Joint"],
    },
    {
        "id": 1189,
        "question": "מהו הטיפול השמרני ב-Knee OA?",
        "options": [
            "ארטרוסקופיה לתפירת המניסקוס",
            "קיבוע בסד למשך כ-3 שבועות",
            "החלפת המפרק",
            "מנוחה, הורדת משקל, חיזוק ושיפור טווחי תנועה",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1190,
        "question": "מאילו חומרים מורכב המשתל ב-Total Knee Replacement (TKR)?",
        "options": ["שילוב של מתכת ופלסטיק", "עצם עצמית בלבד", "גיד הפטלה", "סיליקון בלבד"],
        "answer": 0,
        "anatomy_components": ["Knee Joint"],
    },
    {
        "id": 1191,
        "question": "מהם הסיבוכים של Total Knee Replacement?",
        "options": [
            "צניחת אגן והגבלת אבדוקציה",
            "זיהום, הרס עצם והתרופפות, DVT ונוקשות",
            "עיוות במפרק ה-MTP הראשון",
            "נמק של ראש עצם הירך",
        ],
        "answer": 1,
        "anatomy_components": ["Knee Joint"],
    },
    {
        "id": 1192,
        "question": "מהם תפקידי המניסקוס?",
        "options": [
            "הובלת דם אל תוך המפרק",
            "מניעת החלקה קדמית של הטיביה",
            "בלימת זעזועים, שיפור התאמה מפרקית וייצוב המפרק",
            "ייצוב קשתות כף הרגל",
        ],
        "answer": 2,
        "anatomy_components": ["Lateral Meniscus", "Medial Meniscus"],
    },
    {
        "id": 1193,
        "question": "כיצד ניזון המניסקוס?",
        "options": [
            "אספקת דם עשירה בכל שטחו",
            "אספקת דם רק במרכז",
            "הזנה עצבית בלבד",
            "אספקת דם רק בשוליים, ובמרכז ההזנה באמצעות דיפוזיה",
        ],
        "answer": 3,
        "anatomy_components": ["Lateral Meniscus", "Medial Meniscus"],
    },
    {
        "id": 1194,
        "question": "איזה מניסקוס נקרע לרוב, ולאיזה מבנה הוא מחובר?",
        "options": [
            "המניסקוס המדיאלי, המחובר ל-MCL",
            "המניסקוס הלטרלי, המחובר ל-LCL",
            "המניסקוס המדיאלי, המחובר ל-ACL",
            "המניסקוס הלטרלי, המחובר ל-PCL",
        ],
        "answer": 0,
        "anatomy_components": ["MCL", "Medial Meniscus"],
    },
    {
        "id": 1195,
        "question": "מהו מנגנון הפגיעה במניסקוס?",
        "options": [
            "כוח ולגוס ישיר בלבד",
            "טראומטי או ניווני",
            "עומס יתר בריצה בלבד",
            "Plantar flexion + Inversion",
        ],
        "answer": 1,
        "anatomy_components": ["Medial Meniscus"],
    },
    {
        "id": 1196,
        "question": "מהם התסמינים של Meniscal Injury?",
        "options": [
            "כאב מפושט באזור הפטלה וקרפיטציות",
            "צניחת אגן בהליכה",
            "כאב מקומי, סימנים מכניים של נעילות וקליקים, נפיחות מאוחרת והגבלה בסופי טווחים",
            "כאב חד באזור העקב בקימה מהמיטה",
        ],
        "answer": 2,
        "anatomy_components": ["Knee Joint", "Medial Meniscus"],
    },
    {
        "id": 1197,
        "question": "מהו הטיפול הניתוחי בפגיעת מניסקוס?",
        "options": [
            "החלפת מפרק מלאה",
            "קיבוע במסמר תוך-מדולרי",
            "קיבוע חיצוני ואנטיביוטיקה",
            "ארטרוסקופיה - ניקוי, הוצאה או תפירה",
        ],
        "answer": 3,
        "anatomy_components": [],
    },
    {
        "id": 1198,
        "question": "איזה כוח גורם ל-MCL sprain?",
        "options": [
            "כוח Valgus - מכה בצד הלטרלי של הברך",
            "כוח Varus - מכה בצד המדיאלי של הברך",
            "Hyper-extension של הברך",
            "Inversion של הקרסול",
        ],
        "answer": 0,
        "anatomy_components": ["Knee Joint", "MCL"],
    },
    {
        "id": 1199,
        "question": "מהו הטיפול בפגיעה מבודדת ב-MCL?",
        "options": [
            "ניתוח דחוף לשחזור הרצועה",
            "לרוב שמרני, ולעתים קיבוע בסד למשך כ-3 שבועות",
            "החלפת המפרק",
            "ארטרוסקופיה להוצאת הרצועה",
        ],
        "answer": 1,
        "anatomy_components": ["MCL"],
    },
    {
        "id": 1200,
        "question": "מה מונעת הרצועה הצולבת הקדמית (ACL)?",
        "options": [
            "החלקה אחורית של הטיביה ביחס לפמור",
            "כוח ולגוס בלבד",
            "החלקה קדמית של הטיביה ביחס לפמור",
            "רוטציה של הפטלה",
        ],
        "answer": 2,
        "anatomy_components": ["ACL"],
    },
    {
        "id": 1201,
        "question": "מה מנגנון קרע ה-ACL?",
        "options": [
            "מכה ישירה בצד הלטרלי של הברך",
            "עומס יתר חוזר בעמידה ממושכת",
            "Plantar flexion + Inversion",
            "רוטציה של הפמור על טיביה מקובעת או Hyper-extension - שינוי כיוון, בלימה או חבלה משחקן אחר",
        ],
        "answer": 3,
        "anatomy_components": ["ACL"],
    },
    {
        "id": 1202,
        "question": "מהם התסמינים של קרע ACL?",
        "options": [
            "צליל POP, כאב עמוק בברך, נפיחות, קושי בנשיאת משקל, הגבלה בטווחי תנועה וחוסר יציבות של המפרק",
            "כאב מפושט סביב הפטלה עם קרפיטציות",
            "נוקשות בוקר ועיבוי של הגיד",
            "אסימטריה באורך רגליים",
        ],
        "answer": 0,
        "anatomy_components": ["ACL", "Knee Joint"],
    },
    {
        "id": 1203,
        "question": "אילו פגיעות עלולות להתלוות לקרע ACL?",
        "options": ["קרע של גיד אכילס", "פגיעת מניסקוס ו/או MCL", "שבר בעצם העקב", "פריקת SIJ"],
        "answer": 1,
        "anatomy_components": ["ACL", "MCL", "Medial Meniscus"],
    },
    {
        "id": 1204,
        "question": "באיזה שתל משתמשים בשחזור ACL לפי השקף?",
        "options": ["שתל מתכתי", "שתל מהפאשיה הפלנטרית", "Patellar tendon graft", "שתל מהמניסקוס הלטרלי"],
        "answer": 2,
        "anatomy_components": ["ACL", "Patella"],
    },
    {
        "id": 1205,
        "question": "מה מנגנון הפציעה בנקע במפרק הקרסול?",
        "options": [
            "Dorsi flexion + Eversion",
            "כוח ולגוס ישיר",
            "Plantar flexion + Inversion",
            "רוטציה של הפמור על טיביה מקובעת",
        ],
        "answer": 2,
        "anatomy_components": ["Ankle Joint"],
    },
    {
        "id": 1206,
        "question": "איזו רצועה נפגעת בשכיחות הגבוהה ביותר בנקע במפרק הקרסול?",
        "options": ["PTFL", "CFL", "Deltoid Ligament", "ATFL"],
        "answer": 3,
        "anatomy_components": ["ATFL"],
    },
    {
        "id": 1207,
        "question": "מהם התסמינים של נקע במפרק הקרסול?",
        "options": [
            "נפיחות, כאב, קושי או חוסר יכולת לדרוך על הרגל וירידה בטווחי התנועה",
            "נעילות וקליקים מכניים",
            "צניחת אגן בהליכה",
            "כאב במפרק ה-MTP הראשון",
        ],
        "answer": 0,
        "anatomy_components": ["Ankle Joint"],
    },
    {
        "id": 1208,
        "question": "מהי הפגיעה ב-High Ankle Sprain?",
        "options": [
            "קרע של ה-ATFL בלבד",
            "קרע של הסינדסמוזיס וה-AITFL מעל מפרק הקרסול",
            "שבר של עצם העקב",
            "קרע של גיד אכילס",
        ],
        "answer": 1,
        "anatomy_components": ["Ankle Joint", "Interosseous Membrane"],
    },
    {
        "id": 1209,
        "question": "לפי Ottawa Ankle Rules, מתי יש לבצע צילום קרסול?",
        "options": [
            "בכל מקרה של כאב בקרסול",
            "רק אם קיימת נפיחות",
            "רק אם המטופל מעל גיל 65",
            "בכאב באזור המלאולי עם רגישות עצם בקצה האחורי או בקצה המלאולוס, או חוסר יכולת לדרוך 4 צעדים",
        ],
        "answer": 3,
        "anatomy_components": ["Ankle Joint"],
    },
    {
        "id": 1210,
        "question": "לפי Ottawa Ankle Rules, אילו נקודות רגישות באזור אמצע כף הרגל מחייבות צילום כף רגל?",
        "options": [
            "הטלוס והקלקנאוס",
            "המלאולוס המדיאלי והלטרלי",
            "הפלנקס הראשון והמפרק ה-MTP",
            "עצם ה-Navicular ובסיס המסרק החמישי",
        ],
        "answer": 3,
        "anatomy_components": ["Metatarsal Bones", "Navicular"],
    },
    {
        "id": 1211,
        "question": "מהי הבעיה ב-Achilles tendinopathy?",
        "options": [
            "שינויים במבנה גיד אכילס",
            "דלקת של הפאשיה הפלנטרית",
            "קרע של הרצועה הצולבת הקדמית",
            "נמק של עצם העקב",
        ],
        "answer": 0,
        "anatomy_components": ["Calcaneus", "Gastrocnemius", "Soleus"],
    },
    {
        "id": 1212,
        "question": "מהם התסמינים של Achilles tendinopathy?",
        "options": [
            "כאב במפרק ה-MTP הראשון וקושי בנעילת נעליים",
            "כאב באזור גיד אכילס, נפיחות, נוקשות בעיקר בבוקר, עיבוי של הגיד וגדילה של עצם העקב באזור חיבור הגיד",
            "נעילות וקליקים בברך",
            "כאב מפושט סביב הפטלה",
        ],
        "answer": 1,
        "anatomy_components": ["Calcaneus", "Gastrocnemius"],
    },
    {
        "id": 1213,
        "question": "מה תפקידה של הרקמה הנפגעת ב-Plantar Fasciitis?",
        "options": [
            "מניעת החלקה קדמית של הטיביה",
            "ייצוב קשתות כף הרגל ובלימת זעזועים",
            "שיפור התאמה מפרקית בברך",
            "ייצוב מפרק הירך",
        ],
        "answer": 1,
        "anatomy_components": ["Calcaneus"],
    },
    {
        "id": 1214,
        "question": "מהם גורמי הסיכון ל-Plantar Fasciitis?",
        "options": [
            "אוסטאופורוזיס ונטילת סטרואידים",
            "לידה במצג עכוז",
            "ירידה בטווח ה-Dorsi flexion, עומס יתר (ריצה, ריקוד), שינוי בעומסים והשמנת יתר",
            "כוח ולגוס ישיר",
        ],
        "answer": 2,
        "anatomy_components": [],
    },
    {
        "id": 1215,
        "question": "מהם התסמינים של Plantar Fasciitis?",
        "options": [
            "כאב עמוק בברך וצליל POP",
            "אסימטריה של קפלי העור",
            "נוקשות בוקר במפרק הירך עם השלכה למפשעה",
            "כאב חד באזור העקב, כאבי בוקר בקימה הראשונה מהמיטה, כאב המתגבר בסוף היום ולאחר הליכה ממושכת, הגבלה בטווח Dorsi flexion ורגישות במישוש",
        ],
        "answer": 3,
        "anatomy_components": ["Ankle Joint", "Calcaneus"],
    },
    {
        "id": 1216,
        "question": "באיזו עצם מתפתח דורבן (Heel Spur)?",
        "options": ["בעצם ה-Talus", "בעצם ה-Navicular", "בעצם העקב (Calcaneus)", "במסרק החמישי"],
        "answer": 2,
        "anatomy_components": ["Calcaneus"],
    },
    {
        "id": 1217,
        "question": "באיזה מפרק מתרחש העיוות ב-Hallux valgus?",
        "options": [
            "במפרק ה-MTP הראשון",
            "במפרק ה-Subtalar",
            "במפרק ה-Talocrural",
            "במפרק ה-Transverse Tarsal",
        ],
        "answer": 0,
        "anatomy_components": ["MTP 1 Joint"],
    },
    {
        "id": 1218,
        "question": "מה מתאר את העיוות ב-Hallux valgus?",
        "options": [
            "ADD של המטטרסוס הראשון ו-ABD של הפלנקס",
            "ABD של המטטרסוס הראשון ו-ADD של הפלנקס",
            "Inversion של המטטרסוס ו-Eversion של הפלנקס",
            "כפיפה של הפלנקס בלבד",
        ],
        "answer": 1,
        "anatomy_components": ["MTP 1 Joint", "Metatarsal Bones", "Phalang 1"],
    },
    {
        "id": 1219,
        "question": "מהם התסמינים של Hallux valgus?",
        "options": [
            "נעילות וקליקים במפרק",
            "צניחת אגן בהליכה",
            "כאב באזור גיד אכילס בבוקר",
            "קושי בנעילת נעליים וכאבים במפרק ה-MTP",
        ],
        "answer": 3,
        "anatomy_components": ["MTP 1 Joint"],
    },
    {
        "id": 1220,
        "question": "היכן ממוקם הכאב ב-Patellofemoral Pain Syndrome?",
        "options": [
            "כאב מפושט באזור הפטלה",
            "כאב מקומי מעל הטרוכנטר הגדול",
            "כאב חד באזור העקב",
            "כאב במפשעה עם השלכה לעכוז",
        ],
        "answer": 0,
        "anatomy_components": ["Patella", "Patellofemoral Joint"],
    },
    {
        "id": 1221,
        "question": "מהם הממצאים ב-Patellofemoral Pain Syndrome?",
        "options": [
            "צניחת אגן בעמידה על רגל אחת",
            "קרפיטציות במפרק ה-patellofemoral בתנועה, אטרופיה של שריר ה-quadriceps וכאבים בדחיסה של הפטלה",
            "קליק נמוש במבחן Ortolani",
            "עיבוי של גיד אכילס",
        ],
        "answer": 1,
        "anatomy_components": ["Patella", "Patellofemoral Joint", "Quadriceps"],
    },
    {
        "id": 1222,
        "question": "אילו פעולות מחמירות את הכאב ב-Patellofemoral Pain Syndrome?",
        "options": [
            "שכיבה על הצד בלבד",
            "הליכה על משטח ישר בלבד",
            "עלייה וירידה במדרגות, ישיבה ממושכת עם ברכיים כפופות, קימה לאחר ישיבה ממושכת ועמידה ממושכת על הברכיים או במנח כריעה",
            "דריכה על הרגל לאחר Inversion",
        ],
        "answer": 2,
        "anatomy_components": ["Patella", "Patellofemoral Joint"],
    },
]
