# -*- coding: utf-8 -*-
# Source: "אנטומיה ב' - שאלות אמריקאיות לתרגול - 97509.pdf"
QUESTIONS = [
    {
        "id": 1,
        "question": "לאיזה מהשרירים הבאים Origin או Insertion ב- Greater Trochanter?",
        "options": ["Iliopsoas", "Gluteus Medius", "Hamstrings", "Gluteus Maximuse"],
        "answer": 1,
        "anatomy_components": ["Iliopsoas", "Gluteus Medius", "Hamstrings", "Gluteus Maximus"],
    },
    {
        "id": 2,
        "question": "מי מהשרירים הבאים מבצעים את אותן הפעולות",
        "options": [
            "Latissimuse Dorsi + Anterior Deltoid",
            "Tibialis Anterior + Tibialis Posterior",
            "Periformis + Obturator Internus",
            "Quadriceps + Semimembranosus",
        ],
        "answer": 2,
        "anatomy_components": [
            "Latissimus Dorsi",
            "Anterior Deltoid",
            "Tibialis Anterior",
            "Tibialis Posterior",
            "Piriformis",
            "Obturator Internus",
            "Quadriceps",
            "Semimembranosus",
        ],
    },
    {
        "id": 3,
        "question": "איזה שריר מהבאים מתחבר אל Coracoid process?",
        "options": ["Coracobrachialis", "Brachialis", "Triceps", "Supraspinatus"],
        "answer": 0,
        "anatomy_components": ["Coracobrachialis", "Brachialis", "Triceps", "Supraspinatus"],
    },
    {
        "id": 4,
        "question": "מפרק הקרסול הוא מפרק מסוג",
        "options": ["Ball & Socket", "Hinge", "Ellipsoid", "Sutur"],
        "answer": 1,
        "anatomy_components": ["Ankle Joint"],
    },
    {
        "id": 5,
        "question": "מי מהבאים מתחבר עם עצם ה- Femur?",
        "options": ["Tibia", "Patella", "Acetabulum", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Femur", "Tibia", "Patella", "Acetabulum"],
    },
    {
        "id": 6,
        "question": "לאיזה מהשרירים הבאים יש נקודת אחיזה זהה?",
        "options": [
            "Trapezius + Deltoid",
            "Pectoralis major + Pectoralis minor",
            "Latissimus dorsi + Deltoid",
            "Supraspinatus + Subscapularis",
        ],
        "answer": 0,
        "anatomy_components": [
            "Trapezius",
            "Deltoid",
            "Pectoralis Major",
            "Pectoralis Minor",
            "Latissimus Dorsi",
            "Supraspinatus",
            "Subscapularis",
        ],
    },
    {
        "id": 7,
        "question": "מי מהשרירים הבאים מסוגל להניע את Phalang 1?",
        "options": [
            "Extensor Indicis",
            "Flexor Digitorum Longus",
            "Brachioradialis",
            "Flexor Pollicis Longus",
        ],
        "answer": 3,
        "anatomy_components": [
            "Extensor Indicis",
            "Flexor Digitorum Longus",
            "Brachioradialis",
            "Flexor Pollicis Longus",
        ],
    },
    {
        "id": 8,
        "question": "מי מהבאים אינו שייך למייצבי הכתף",
        "options": ["Supraspinatus", "Serratus Anterior", "Subscapularis", "Teres Minor"],
        "answer": 1,
        "anatomy_components": ["Supraspinatus", "Serratus Anterior", "Subscapularis", "Teres Minor"],
    },
    {
        "id": 9,
        "question": "מי מהבאים מונע עודף תנועה במישור הסגיטלי?",
        "options": ["M.C.L", "P.C.L", "L.C.L", "Annular Ligament"],
        "answer": 1,
        "anatomy_components": ["MCL", "PCL", "LCL", "Annular Ligament"],
    },
    {
        "id": 10,
        "question": "מי מהבאים שייך למפרקי חגורת הכתפיים",
        "options": [
            "Patello femoral joint",
            "Radio ulnar joint",
            "Acromio clavicular joint",
            "Radio carpal joint",
        ],
        "answer": 2,
        "anatomy_components": [
            "Patellofemoral Joint",
            "Radioulnar Joint",
            "Acromioclavicular Joint",
            "Radiocarpal Joint",
        ],
    },
    {
        "id": 11,
        "question": "תנועת ה-Inversion מתבצעת במפרק",
        "options": ["Subtalar Joint", "P.I.P", "D.I.P", "Hip Joint"],
        "answer": 0,
        "anatomy_components": ["Subtalar Joint", "PIP Joint", "DIP Joint", "Hip Joint"],
    },
    {
        "id": 12,
        "question": "באיזה מישור מסוגל לעבוד ה-Middle Deltoid?",
        "options": ["סגיטלי", "פרונטלי", "הוריזונטלי", "טרנסברסלי"],
        "answer": 1,
        "anatomy_components": ["Deltoid"],
    },
    {
        "id": 13,
        "question": "במפרק Proximal Radioulnar Joint מתקיימת תנועה –",
        "options": ["Flexion", "Extension", "Diviation", "Pronation"],
        "answer": 3,
        "anatomy_components": ["Proximal Radioulnar Joint"],
    },
    {
        "id": 14,
        "question": "ברוטציה של הגב שמאלה יעבדו השרירים",
        "options": [
            "Right External Obliqe + Left Internal Obliqe",
            "Left External Obliqe + Right Internal Obliqe",
            "Left External Obliqe + Left Internal Obliqe",
            "Right External Obliqe + Right Internal Obliqe",
        ],
        "answer": 0,
        "anatomy_components": ["External Oblique", "Internal Oblique"],
    },
    {
        "id": 15,
        "question": "שריר המסתיים בעצם ה-Radius מסוגל לבצע -",
        "options": ["Extension", "Elevation", "Supination", "Abduction"],
        "answer": 2,
        "anatomy_components": ["Radius"],
    },
    {
        "id": 16,
        "question": "מי מהבאים הם אגוניסט אנטגוניסט אחד לשני?",
        "options": [
            "Biceps Brachii + Brachialis",
            "Serratus Anterior + Rhomboid",
            "Deltoid + Supraspinatus",
            "Semimembranosus + Semitendinosus",
        ],
        "answer": 1,
        "anatomy_components": [
            "Biceps Brachii",
            "Brachialis",
            "Serratus Anterior",
            "Rhomboid",
            "Deltoid",
            "Supraspinatus",
            "Semimembranosus",
            "Semitendinosus",
        ],
    },
    {
        "id": 17,
        "question": "מפרק Sterno-clavicular Joint הוא מפרק מסוג:",
        "options": ["Saddle", "Ellipsoid", "Ball & Socket", "Gliding"],
        "answer": 0,
        "anatomy_components": ["Sternoclavicular Joint"],
    },
    {
        "id": 18,
        "question": "מי מהבאים מבצע P.P.T?",
        "options": ["Rectus Abdominis", "Gluteus Maximuse", "External Obliqe", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Rectus Abdominis", "Gluteus Maximus", "External Oblique"],
    },
    {
        "id": 19,
        "question": "מי מהבאים הוא מפרק מסוג Pivot?",
        "options": [
            "C1-C2",
            "Proximal Tibiofibular Joint",
            "Atlanto Occipital Joint",
            "Tibiofemoral Joint",
        ],
        "answer": 0,
        "anatomy_components": [
            "C1-C2 Joint",
            "Proximal Tibiofibular Joint",
            "Atlanto-Occipital Joint",
            "Tibiofemoral Joint",
        ],
    },
    {
        "id": 20,
        "question": "מי מהבאים אחראי על Upward Rotation?",
        "options": ["Posterior Deltoid", "Teres Major", "Teres Minor", "Serratus Anterior"],
        "answer": 3,
        "anatomy_components": ["Posterior Deltoid", "Teres Major", "Teres Minor", "Serratus Anterior"],
    },
]
