# -*- coding: utf-8 -*-
# Sources:
#   ids 1-20  "אנטומיה ב' - שאלות אמריקאיות לתרגול - 97509.pdf" (answer key included)
#   ids 21-23 "אנטומיה ב' - שאלות חזרה ותרגול - 97508.pdf" — the multiple-choice
#             questions on p.6. That document ships no answer key, so those
#             three answers are derived from standard anatomy, not transcribed.
#   ids 24-65 Kahoot "אנטומיה ב' - רפואה משלימה" by tzafiravivlevy, read from
#             Kahoot's public REST API, so the correct answers are the course
#             author's own. Text is verbatim apart from three normalisations:
#             HTML entities unescaped, whitespace collapsed, and a leading
#             "?"/":" moved to the end (28 of the 43 stems stored it first,
#             having been typed in a right-to-left field). The author's joke
#             final question was dropped as it is not anatomy.
#   ids 66-73 Kahoot "שרירים - רפואת הספורט למדריכים" by the same author, same
#             API source and same normalisations. Two of its ten questions ask
#             about an attached picture hosted on Kahoot with no licence
#             information; they were left out rather than commit an unlicensed
#             image, since without it they cannot be answered.
#   ids 74-161 the five course slide decks, read as rendered page images so the
#             Hebrew survived intact (text extraction scrambles the RTL runs):
#             97501 upper limb 74-91, 97502 forearm/hand 92-109, 97503 lower
#             limb 110-127, 97504 ankle/foot 128-145, 97505 abdomen/back/neck
#             146-161. Every question restates something a slide states; slides
#             the lecturer marked "אין צורך לזכור בע"פ" were left alone.
QUESTIONS = [
    {
        "id": 1,
        "question": "לאיזה מהשרירים הבאים Origin או Insertion ב- Greater Trochanter?",
        "options": ["Iliopsoas", "Gluteus Medius", "Hamstrings", "Gluteus Maximuse"],
        "answer": 1,
        "anatomy_components": ["Gluteus Maximus", "Gluteus Medius", "Greater Trochanter", "Hamstrings", "Iliopsoas"],
    },
    {
        "id": 2,
        "question": "מי מהשרירים הבאים מבצעים את אותן הפעולות",
        "options": [
            "Latissimuse Dorsi + Anterior Deltoid",
            "Tibialis Anterior + Tibialis Posterior",
            "Periformis + Obturator Internus",
            "Quadriceps + Semimembranosus",
        ],
        "answer": 2,
        "anatomy_components": [
            "Anterior Deltoid",
            "Latissimus Dorsi",
            "Obturator Internus",
            "Piriformis",
            "Quadriceps",
            "Semimembranosus",
            "Tibialis Anterior",
            "Tibialis Posterior",
        ],
    },
    {
        "id": 3,
        "question": "איזה שריר מהבאים מתחבר אל Coracoid process?",
        "options": ["Coracobrachialis", "Brachialis", "Triceps", "Supraspinatus"],
        "answer": 0,
        "anatomy_components": ["Brachialis", "Coracobrachialis", "Coracoid Process", "Supraspinatus", "Triceps"],
    },
    {
        "id": 4,
        "question": "מפרק הקרסול הוא מפרק מסוג",
        "options": ["Ball & Socket", "Hinge", "Ellipsoid", "Sutur"],
        "answer": 1,
        "anatomy_components": ["Ankle Joint"],
    },
    {
        "id": 5,
        "question": "מי מהבאים מתחבר עם עצם ה- Femur?",
        "options": ["Tibia", "Patella", "Acetabulum", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Acetabulum", "Femur", "Patella", "Tibia"],
    },
    {
        "id": 6,
        "question": "לאיזה מהשרירים הבאים יש נקודת אחיזה זהה?",
        "options": [
            "Trapezius + Deltoid",
            "Pectoralis major + Pectoralis minor",
            "Latissimus dorsi + Deltoid",
            "Supraspinatus + Subscapularis",
        ],
        "answer": 0,
        "anatomy_components": [
            "Deltoid",
            "Latissimus Dorsi",
            "Pectoralis Major",
            "Pectoralis Minor",
            "Subscapularis",
            "Supraspinatus",
            "Trapezius",
        ],
    },
    {
        "id": 7,
        "question": "מי מהשרירים הבאים מסוגל להניע את Phalang 1?",
        "options": [
            "Extensor Indicis",
            "Flexor Digitorum Longus",
            "Brachioradialis",
            "Flexor Pollicis Longus",
        ],
        "answer": 3,
        "anatomy_components": [
            "Brachioradialis",
            "Extensor Indicis",
            "Flexor Digitorum Longus",
            "Flexor Pollicis Longus",
            "Phalang 1",
        ],
    },
    {
        "id": 8,
        "question": "מי מהבאים אינו שייך למייצבי הכתף",
        "options": ["Supraspinatus", "Serratus Anterior", "Subscapularis", "Teres Minor"],
        "answer": 1,
        "anatomy_components": ["Serratus Anterior", "Subscapularis", "Supraspinatus", "Teres Minor"],
    },
    {
        "id": 9,
        "question": "מי מהבאים מונע עודף תנועה במישור הסגיטלי?",
        "options": ["M.C.L", "P.C.L", "L.C.L", "Annular Ligament"],
        "answer": 1,
        "anatomy_components": ["Annular Ligament", "LCL", "MCL", "PCL"],
    },
    {
        "id": 10,
        "question": "מי מהבאים שייך למפרקי חגורת הכתפיים",
        "options": [
            "Patello femoral joint",
            "Radio ulnar joint",
            "Acromio clavicular joint",
            "Radio carpal joint",
        ],
        "answer": 2,
        "anatomy_components": [
            "Acromioclavicular Joint",
            "Patellofemoral Joint",
            "Radiocarpal Joint",
            "Radioulnar Joint",
        ],
    },
    {
        "id": 11,
        "question": "תנועת ה-Inversion מתבצעת במפרק",
        "options": ["Subtalar Joint", "P.I.P", "D.I.P", "Hip Joint"],
        "answer": 0,
        "anatomy_components": ["DIP Joint", "Hip Joint", "PIP Joint", "Subtalar Joint"],
    },
    {
        "id": 12,
        "question": "באיזה מישור מסוגל לעבוד ה-Middle Deltoid?",
        "options": ["סגיטלי", "פרונטלי", "הוריזונטלי", "טרנסברסלי"],
        "answer": 1,
        "anatomy_components": ["Deltoid"],
    },
    {
        "id": 13,
        "question": "במפרק Proximal Radioulnar Joint מתקיימת תנועה –",
        "options": ["Flexion", "Extension", "Diviation", "Pronation"],
        "answer": 3,
        "anatomy_components": ["Proximal Radioulnar Joint"],
    },
    {
        "id": 14,
        "question": "ברוטציה של הגב שמאלה יעבדו השרירים",
        "options": [
            "Right External Obliqe + Left Internal Obliqe",
            "Left External Obliqe + Right Internal Obliqe",
            "Left External Obliqe + Left Internal Obliqe",
            "Right External Obliqe + Right Internal Obliqe",
        ],
        "answer": 0,
        "anatomy_components": ["External Oblique", "Internal Oblique"],
    },
    {
        "id": 15,
        "question": "שריר המסתיים בעצם ה-Radius מסוגל לבצע -",
        "options": ["Extension", "Elevation", "Supination", "Abduction"],
        "answer": 2,
        "anatomy_components": ["Radius"],
    },
    {
        "id": 16,
        "question": "מי מהבאים הם אגוניסט אנטגוניסט אחד לשני?",
        "options": [
            "Biceps Brachii + Brachialis",
            "Serratus Anterior + Rhomboid",
            "Deltoid + Supraspinatus",
            "Semimembranosus + Semitendinosus",
        ],
        "answer": 1,
        "anatomy_components": [
            "Biceps Brachii",
            "Brachialis",
            "Deltoid",
            "Rhomboid",
            "Semimembranosus",
            "Semitendinosus",
            "Serratus Anterior",
            "Supraspinatus",
        ],
    },
    {
        "id": 17,
        "question": "מפרק Sterno-clavicular Joint הוא מפרק מסוג:",
        "options": ["Saddle", "Ellipsoid", "Ball & Socket", "Gliding"],
        "answer": 0,
        "anatomy_components": ["Sternoclavicular Joint"],
    },
    {
        "id": 18,
        "question": "מי מהבאים מבצע P.P.T?",
        "options": ["Rectus Abdominis", "Gluteus Maximuse", "External Obliqe", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["External Oblique", "Gluteus Maximus", "Rectus Abdominis"],
    },
    {
        "id": 19,
        "question": "מי מהבאים הוא מפרק מסוג Pivot?",
        "options": [
            "C1-C2",
            "Proximal Tibiofibular Joint",
            "Atlanto Occipital Joint",
            "Tibiofemoral Joint",
        ],
        "answer": 0,
        "anatomy_components": [
            "Atlanto-Occipital Joint",
            "C1-C2 Joint",
            "Proximal Tibiofibular Joint",
            "Tibiofemoral Joint",
        ],
    },
    {
        "id": 20,
        "question": "מי מהבאים אחראי על Upward Rotation?",
        "options": ["Posterior Deltoid", "Teres Major", "Teres Minor", "Serratus Anterior"],
        "answer": 3,
        "anatomy_components": ["Posterior Deltoid", "Serratus Anterior", "Teres Major", "Teres Minor"],
    },
    {
        "id": 21,
        "question": "מי מהשרירים הבאים מניע את האגודל?",
        "options": [
            "Flexor Indicis",
            "Extensor Digitorum",
            "Abductor Pollicis Brevis",
            "Flexor Carpi Ulnaris",
        ],
        "answer": 2,
        # "Flexor Indicis" is not a real named muscle, so it gets no page.
        "anatomy_components": ["Abductor Pollicis Brevis", "Extensor Digitorum", "Flexor Carpi Ulnaris"],
    },
    {
        "id": 22,
        "question": "מי מהשרירים הבאים מסתיים ב- ULNA?",
        "options": ["Biceps Brachii", "Brachialis", "Supinator", "Pronator Teres"],
        "answer": 1,
        "anatomy_components": ["Biceps Brachii", "Brachialis", "Pronator Teres", "Supinator", "Ulna"],
    },
    {
        "id": 23,
        "question": "מי מהעצמות הבאות לא משתתפת במפרק RADIO-CARPAL JOINT?",
        "options": ["Lunate", "Scaphoid", "Radius", "Metacarpal 2"],
        "answer": 3,
        "anatomy_components": ["Lunate", "Metacarpal 2", "Radiocarpal Joint", "Radius", "Scaphoid"],
    },
    {
        "id": 24,
        "question": "מי מהמפרקים הבאים הוא חלק ממפרקי חגורת הכתפיים?",
        "options": ["Radio-ulnar joint", "Knee joint", "Gleno-humeral joint", "Patello-femoral joint"],
        "answer": 2,
        "anatomy_components": ["Glenohumeral Joint", "Knee Joint", "Patellofemoral Joint", "Radioulnar Joint"],
    },
    {
        "id": 25,
        "question": "מי מהבאים מייצב את הכתף בצורה פאסיבית?",
        "options": ["P.C.L", "Supraspinatus", "Meniscus", "Glenohumeral Ligament"],
        "answer": 3,
        "anatomy_components": ["Glenohumeral Ligament", "PCL", "Supraspinatus"],
    },
    {
        "id": 26,
        "question": "מי מהבאים משתתף במפרק הכתף?",
        "options": [
            "Accetabulum + Humerus",
            "Acromion + spine of scapula",
            "Ilium + Head of humerus",
            "Glenoid fossa + Head of humerus",
        ],
        "answer": 3,
        "anatomy_components": ["Acetabulum", "Acromion", "Glenoid Fossa", "Humerus", "Ilium", "Spine of Scapula"],
    },
    {
        "id": 27,
        "question": "של השכמה Elevation מי מהשרירים הבאים תפקידו לבצע?",
        "options": [
            "Upper Trapezius + Levator Scapula",
            "latissimus Dorsi + Teres Major",
            "Middle Trapezius + Rhomboids",
            "Sternocleidomastoid",
        ],
        "answer": 0,
        "anatomy_components": [
            "Latissimus Dorsi",
            "Levator Scapulae",
            "Rhomboid",
            "Sternocleidomastoid",
            "Teres Major",
            "Trapezius",
        ],
    },
    {
        "id": 28,
        "question": "clavicle - בחלק הלטרלי של ה origin למי מהשרירים הבאים?",
        "options": ["Rhomboids", "Deltoid", "Pectoralis Major", "Latissimus Dorsi"],
        "answer": 1,
        "anatomy_components": ["Clavicle", "Deltoid", "Latissimus Dorsi", "Pectoralis Major", "Rhomboid"],
    },
    {
        "id": 29,
        "question": "במפרק הכתף Internal Rotation מי מהשרירים הבאים מבצע?",
        "options": ["Latissimuse Dorsi", "Teres Major", "Anterior Deltoid", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Anterior Deltoid", "Latissimus Dorsi", "Teres Major"],
    },
    {
        "id": 30,
        "question": "Rotators Cuff - מי מהבאים אינו חלק מקבוצת ה?",
        "options": ["Supraspinatus", "Serratus Anterior", "Subscapularis", "Infraspinatus"],
        "answer": 1,
        "anatomy_components": ["Infraspinatus", "Serratus Anterior", "Subscapularis", "Supraspinatus"],
    },
    {
        "id": 31,
        "question": "מי מהשרירים הבאים עובד במישור הסגיטלי?",
        "options": ["Deltoid", "Gluteus Medius", "Triceps", "Adductors Longus"],
        "answer": 2,
        "anatomy_components": ["Deltoid", "Gluteus Medius", "Triceps"],
    },
    {
        "id": 32,
        "question": "הוא מפרק מסוג Radiocarpal מפרק:",
        "options": ["Ball & Socket", "Condyle", "Hinge", "החלקתי"],
        "answer": 1,
        "anatomy_components": ["Radiocarpal Joint"],
    },
    {
        "id": 33,
        "question": "סמן את המשפט הנכון:",
        "options": [
            "Hinge הוא מפרק מסוג M.T.P 1 מפרק",
            "Hinge מפרק הקרסול הוא מפרק מסוג",
            "Deltoid Ligament- הרצועה הפגיעה ביותר בקרסול שייכת ל",
            "Tibialis Anterior בעלייה על קצות הבהונות השריר שעובד הוא",
        ],
        "answer": 1,
        "anatomy_components": ["Ankle Joint", "Deltoid Ligament", "MTP 1 Joint", "Tibialis Anterior"],
    },
    {
        "id": 34,
        "question": "Coracoid Process - מי מהבאים נאחז ב?",
        "options": ["Long head of biceps", "Triceps", "Short head of biceps", "Deltoid"],
        "answer": 2,
        "anatomy_components": ["Biceps Brachii", "Coracoid Process", "Deltoid", "Triceps"],
    },
    {
        "id": 35,
        "question": "מי מהבאים יודע לבצע סופינציה?",
        "options": ["Biceps Brachii", "Bracioradialis", "Pronator", "Brachialis"],
        "answer": 0,
        "anatomy_components": ["Biceps Brachii", "Brachialis", "Brachioradialis", "Pronator Teres"],
    },
    {
        "id": 36,
        "question": "מי מהשרירים הבאים העמוק ביותר?",
        "options": ["Latissimuse Dorsi", "External Oblique", "Transverse Abdominis", "Sartorius"],
        "answer": 2,
        "anatomy_components": ["External Oblique", "Latissimus Dorsi", "Sartorius", "Transverse Abdominis"],
    },
    {
        "id": 37,
        "question": "ברוטציה של הגב לכיוון שמאל - מי עובד?",
        "options": [
            "Left Internal Obliqe + Left External Obliqe",
            "Left Internal Obliqe + Right External Obliqe",
            "Left External Obliqe + Right External Obliqe",
            "Left Internal Obliqe + Right Internal Obliqe",
        ],
        "answer": 1,
        "anatomy_components": ["External Oblique", "Internal Oblique"],
    },
    {
        "id": 38,
        "question": "Iliacus- מה לא נכון לגבי שריר ה?",
        "options": [
            "Gluteus Maximuse -הוא אנטגוניסט לשריר ה",
            "ומבצע כפיפת ירך Iliac Fossa- מתחיל ב",
            "במפרק ירך Flexion -ו A.P.T יודע לבצע",
            "ומבצע פשיטת ירך Greather Trochanter -מסתיים ב",
        ],
        "answer": 3,
        "anatomy_components": ["Gluteus Maximus", "Greater Trochanter", "Iliacus"],
    },
    {
        "id": 39,
        "question": "P.P.T מי מהשרירים הבאים מבצע?",
        "options": ["Quadriceps", "Rectus Abdominis", "Psoas Major", "Ilio psoas"],
        "answer": 1,
        "anatomy_components": ["Iliopsoas", "Psoas Major", "Quadriceps", "Rectus Abdominis"],
    },
    {
        "id": 40,
        "question": "מי מהבאים הוא שריר דו מפרקי?",
        "options": ["Biceps Brachii", "Sartorius", "Hamstrings", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Biceps Brachii", "Hamstrings", "Sartorius"],
    },
    {
        "id": 41,
        "question": "איזו רצועה מהבאות שייכת למפרק כתף?",
        "options": ["A.C.L", "Coracohumeral Ligament", "M.C.L", "Iliofemoral Ligament"],
        "answer": 1,
        "anatomy_components": ["ACL", "Coracohumeral Ligament", "Iliofemoral Ligament", "MCL"],
    },
    {
        "id": 42,
        "question": "איזה שרירים נאחזים ב- I.T.B",
        "options": [
            "Gluteus Medius + Gluteus Minimus",
            "Gastrochnemius + Soleus",
            "Latissimuse Dordi + Pectoralis Minor",
            "T.F.L + Gluteus Maximuse",
        ],
        "answer": 3,
        "anatomy_components": [
            "Gastrocnemius",
            "Gluteus Maximus",
            "Gluteus Medius",
            "Gluteus Minimus",
            "Iliotibial Band",
            "Latissimus Dorsi",
            "Pectoralis Minor",
            "Soleus",
            "Tensor Fasciae Latae",
        ],
    },
    {
        "id": 43,
        "question": "מי מהבאים מייצב את מפרק הברך?",
        "options": ["Gluteus Minimus", "Psoas Major", "A.C.L + P.C.L", "Patella"],
        "answer": 2,
        "anatomy_components": ["ACL", "Gluteus Minimus", "PCL", "Patella", "Psoas Major"],
    },
    {
        "id": 44,
        "question": "מי מהבאים מבצעים את אותן הפעולות?",
        "options": [
            "Tibialis Anterior+ Tibialis Posterior",
            "Peroneus Longus + Tibialis Anterior",
            "Quadriceps",
            "Gastrochnemius + soleus",
        ],
        "answer": 3,
        "anatomy_components": [
            "Gastrocnemius",
            "Peroneus Longus",
            "Quadriceps",
            "Soleus",
            "Tibialis Anterior",
            "Tibialis Posterior",
        ],
    },
    {
        "id": 45,
        "question": "מי מהבאים מבצע כפיפה של עמוד השדרה?",
        "options": ["Rectus Abdominis", "External Obliqe", "כל התשובות נכונות", "Intrnal Obliqe"],
        "answer": 2,
        "anatomy_components": ["External Oblique", "Internal Oblique", "Rectus Abdominis"],
    },
    {
        "id": 46,
        "question": "מי מהשרירים הבאים יניע את האגודל?",
        "options": [
            "Extensor Indicis",
            "Palmaris Longus",
            "Flexor Pollicis Longus",
            "Flexor Hallucis Longus",
        ],
        "answer": 2,
        "anatomy_components": [
            "Extensor Indicis",
            "Flexor Hallucis Longus",
            "Flexor Pollicis Longus",
            "Palmaris Longus",
        ],
    },
    {
        "id": 47,
        "question": "איזו רצועה מהבאות תפקידה למנוע עודף תנועה במישור הסגיטלי?",
        "options": ["M.C.L", "P.C.L", "Medial Meniscus", "L.C.L"],
        "answer": 1,
        "anatomy_components": ["LCL", "MCL", "Medial Meniscus", "PCL"],
    },
    {
        "id": 48,
        "question": "Femur- בעצם ה origin למי מהשרירים הבאים?",
        "options": ["Vastus Medialis", "Longissimuse", "Semimembranosus", "Rectus Femoris"],
        "answer": 0,
        "anatomy_components": ["Femur", "Longissimus", "Rectus Femoris", "Semimembranosus", "Vastus Medialis"],
    },
    {
        "id": 49,
        "question": "מהי הבורסה העלולה להינזק מעמידה ממושכת על הברכיים?",
        "options": ["Trochanteric Bursa", "Prepatellar Bursa", "Suprapatellar Bursa", "Subacromial Bursa"],
        "answer": 1,
        "anatomy_components": ["Prepatellar Bursa", "Subacromial Bursa", "Suprapatellar Bursa", "Trochanteric Bursa"],
    },
    {
        "id": 50,
        "question": "מבצע Periformis -שריר ה:",
        "options": [
            "Internal Rotation מפרק ירך",
            "Abduction מפרק ירך",
            "External Rotation מפרק ירך",
            "כל התשובות נכונות",
        ],
        "answer": 2,
        "anatomy_components": ["Piriformis"],
    },
    {
        "id": 51,
        "question": "מתבצעת במפרק Eversion- תנועת ה:",
        "options": ["D.I.P jt", "Talo-Crural jt", "Knee jt", "Subtalar jt"],
        "answer": 3,
        "anatomy_components": ["DIP Joint", "Knee Joint", "Subtalar Joint", "Talocrural Joint"],
    },
    {
        "id": 52,
        "question": "מי מהשרירים הבאים מניע שכמה?",
        "options": ["Hamstrings", "Trapezius", "Latissimuse Dorsi", "Subscapularis"],
        "answer": 1,
        "anatomy_components": ["Hamstrings", "Latissimus Dorsi", "Subscapularis", "Trapezius"],
    },
    {
        "id": 53,
        "question": "מבצע Sternoclaidomastoid-שריר ה:",
        "options": ["Extension דו צדדי", "רוטציה לאותו הצד", "Flexion דו צדדי", "סופינציה"],
        "answer": 2,
        "anatomy_components": ["Sternocleidomastoid"],
    },
    {
        "id": 54,
        "question": "Anterior Deltoid מה מבצע?",
        "options": [
            "Extension, Horizontal Abduction, External rotation",
            "Flexion, Horizontal Adduction, Internal rotation",
            "Abduction",
            "כל התשובות נכונות",
        ],
        "answer": 1,
        "anatomy_components": ["Anterior Deltoid"],
    },
    {
        "id": 55,
        "question": "למי מהשרירים הבאים יש נקודת אוריגן זהה?",
        "options": [
            "Pectoralis Minor + Pectoralis Major",
            "Deltoid + Trapezius",
            "Semimembranosus+ Semitendinosus",
            "Gastrocnemius + Soleus",
        ],
        "answer": 2,
        "anatomy_components": [
            "Deltoid",
            "Gastrocnemius",
            "Pectoralis Major",
            "Pectoralis Minor",
            "Semimembranosus",
            "Semitendinosus",
            "Soleus",
            "Trapezius",
        ],
    },
    {
        "id": 56,
        "question": "מי מהבאים מבצעים פעולות מנוגדות של סיבוב אגן ?",
        "options": [
            "Rectus Abdominis - Internal obliqe",
            "External obliqe - Internal Obliqe",
            "Ilio psoas - Gluteus Maximuse",
            "Ilio psoas - Vastus Medialis",
        ],
        "answer": 2,
        "anatomy_components": [
            "External Oblique",
            "Gluteus Maximus",
            "Iliopsoas",
            "Internal Oblique",
            "Rectus Abdominis",
            "Vastus Medialis",
        ],
    },
    {
        "id": 57,
        "question": "מי מהשרירים הבאים מבצע P.P.T?",
        "options": ["Iliopsoas", "Quadriceps", "Rectus Abdominis", "Gluteus Medius"],
        "answer": 2,
        "anatomy_components": ["Gluteus Medius", "Iliopsoas", "Quadriceps", "Rectus Abdominis"],
    },
    {
        "id": 58,
        "question": "איזה מהמפרקים הבאים עלול להוות מצב חירום בעת פריקה?",
        "options": [
            "Acromio-clavicular jt",
            "Sterno-clavicular jt",
            "Gleno-humeral jt",
            "Patello-femoral jt",
        ],
        "answer": 1,
        "anatomy_components": [
            "Acromioclavicular Joint",
            "Glenohumeral Joint",
            "Patellofemoral Joint",
            "Sternoclavicular Joint",
        ],
    },
    {
        "id": 59,
        "question": "לאיזה שריר מהבאים יש Insrtion בעצם ה- Radius?",
        "options": ["Brachialis", "Rhomboids", "Triceps", "Biceps Brachii"],
        "answer": 3,
        "anatomy_components": ["Biceps Brachii", "Brachialis", "Radius", "Rhomboid", "Triceps"],
    },
    {
        "id": 60,
        "question": "מפרק C.M.C 1 הוא מפרק מסוג:",
        "options": ["Gliding", "Pivot", "Saddle", "Ball & Socket"],
        "answer": 2,
        "anatomy_components": ["CMC 1 Joint"],
    },
    {
        "id": 61,
        "question": "למי מהשרירים הבאים אחיזה בצלעות ?",
        "options": ["Latissimuse Dorsi", "Serratus Anterior", "External Obliqe", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["External Oblique", "Latissimus Dorsi", "Serratus Anterior"],
    },
    {
        "id": 62,
        "question": "איזו רצועה מבין הבאות היא הפגיעה ביותר במפרק הקרסול?",
        "options": ["Deltoid Ligament", "Glenohumeral Ligament", "A.T.F.L", "P.C.L"],
        "answer": 2,
        "anatomy_components": ["ATFL", "Ankle Joint", "Deltoid Ligament", "Glenohumeral Ligament", "PCL"],
    },
    {
        "id": 63,
        "question": "למי מהשרירים הבאים Insertion ב - Bicipital Groove ?",
        "options": ["Teres Minor", "Teres Major", "Triceps", "Serratus Anterior"],
        "answer": 1,
        "anatomy_components": ["Bicipital Groove", "Serratus Anterior", "Teres Major", "Teres Minor", "Triceps"],
    },
    {
        "id": 64,
        "question": "מי מהשרירים הבאים מבצע Side Flexion?",
        "options": [
            "Internal Obliqe",
            "Q.L ( Quadratus Lumborum )",
            "External Obliqe",
            "כל התשובות נכונות",
        ],
        "answer": 3,
        "anatomy_components": ["External Oblique", "Internal Oblique", "Quadratus Lumborum"],
    },
    {
        "id": 65,
        "question": "מי מצמד השרירים הבאים מבצעים פעולות מנוגדות?",
        "options": [
            "Rhomboids + Serratus Anterior",
            "Gluteus Medius + Adductor Brevis",
            "Tibialis Anterior + Soleus",
            "כל התשובות נכונות",
        ],
        "answer": 3,
        "anatomy_components": [
            "Adductor Brevis",
            "Gluteus Medius",
            "Rhomboid",
            "Serratus Anterior",
            "Soleus",
            "Tibialis Anterior",
        ],
    },
    {
        "id": 66,
        "question": "מהו השריר העיקרי המרחיק כתף?",
        "options": ["Pectoralis Major", "Quadriceps", "Deltoid", "Hamstrings"],
        "answer": 2,
        "anatomy_components": ["Deltoid", "Hamstrings", "Pectoralis Major", "Quadriceps"],
    },
    {
        "id": 67,
        "question": "למי מהשרירים הבאים יש יותר מגיד אחד בנקודת ההתחלה?",
        "options": ["Biceps Brachii", "Quadriceps", "Triceps", "כל התשובות נכונות"],
        "answer": 3,
        "anatomy_components": ["Biceps Brachii", "Quadriceps", "Triceps"],
    },
    {
        "id": 68,
        "question": "הפעולה העיקרית של שרירי ה- Hamstrings היא:",
        "options": ["פשיטה במפרק הברך", "הרחקה במפרק ירך", "כפיפה במפרק הברך", "כפיפה במפרק כתף"],
        "answer": 2,
        "anatomy_components": ["Hamstrings"],
    },
    {
        "id": 69,
        "question": "מי מהשרירים הבאים מבצע קירוב אופקי במפרק הכתף?",
        "options": ["Gastrocnemius", "Gluteus Medius", "Pectoralis Major", "Triceps"],
        "answer": 2,
        "anatomy_components": ["Gastrocnemius", "Gluteus Medius", "Pectoralis Major", "Triceps"],
    },
    {
        "id": 70,
        "question": "מי מהשרירים שלמדת מקרב שכמות אל עמוד השדרה?",
        "options": ["Rectus Abdominis", "Trapezius", "Hamstrings", "Quadriceps"],
        "answer": 1,
        "anatomy_components": ["Hamstrings", "Quadriceps", "Rectus Abdominis", "Trapezius"],
    },
    {
        "id": 71,
        "question": "מי משרירי הבטן מכופף את הגו?",
        "options": ["Transverse Abdominis", "External Oblique", "Rectus Abdominis", "Internal Oblique"],
        "answer": 2,
        "anatomy_components": ["External Oblique", "Internal Oblique", "Rectus Abdominis", "Transverse Abdominis"],
    },
    {
        "id": 72,
        "question": "מי מהשרירים שלמדת פושט ברך ומכופף ירך?",
        "options": ["Hamstrings", "Biceps Brachii", "Rectus Femoris", "Long head of triceps"],
        "answer": 2,
        "anatomy_components": ["Biceps Brachii", "Hamstrings", "Rectus Femoris", "Triceps"],
    },
    {
        "id": 73,
        "question": "מה מסוגל לבצע ה- Long head of Triceps?",
        "options": ["כפיפת כתף", "פשיטת כתף ופשיטת כתף", "הרחקת כתף", "קירוב אופקי בכתף"],
        "answer": 1,
        "anatomy_components": ["Triceps"],
    },
    {
        "id": 74,
        "question": "מפרק ה- Gleno-Humeral (Ball & Socket) ומפרק ה- Acromio-Clavicular (Gliding) שייכים שניהם לקבוצת:",
        "options": [
            "מפרקים חד ציריים (Uniaxial)",
            "מפרקים דו ציריים (Biaxial)",
            "מפרקים תלת ציריים (Multiaxial)",
            "מפרקים סיביים",
        ],
        "answer": 2,
        "anatomy_components": ["Acromioclavicular Joint", "Glenohumeral Joint"],
    },
    {
        "id": 75,
        "question": "מפרק Acromio-Clavicular הוא מפרק מסוג:",
        "options": ["Hinge", "Gliding", "Saddle", "Pivot"],
        "answer": 1,
        "anatomy_components": ["Acromioclavicular Joint"],
    },
    {
        "id": 76,
        "question": "מי מהמפרקים הבאים אינו נמנה עם מפרקי חגורת הכתפיים?",
        "options": [
            "Scapulo-Thoracic joint",
            "Sterno-Clavicular joint",
            "Acromio-Clavicular joint",
            "Elbow joint",
        ],
        "answer": 3,
        "anatomy_components": [
            "Acromioclavicular Joint",
            "Elbow Joint",
            "Scapulothoracic Joint",
            "Sternoclavicular Joint",
        ],
    },
    {
        "id": 77,
        "question": "איזו מהתנועות הבאות אינה מתבצעת במפרק ה- Scapulo-Thoracic?",
        "options": ["Upward Rotation", "Anterior Tilt", "Supination", "Protraction"],
        "answer": 2,
        "anatomy_components": ["Scapulothoracic Joint"],
    },
    {
        "id": 78,
        "question": "איזו רצועה במפרק הכתף מונעת קפיצת ה- Humerus כלפי מעלה?",
        "options": [
            "Coracohumeral Ligament",
            "Glenohumeral Ligament",
            "Coracoacromial Ligament",
            "Transverse Humeral Ligament",
        ],
        "answer": 2,
        "anatomy_components": [
            "Coracoacromial Ligament",
            "Coracohumeral Ligament",
            "Glenohumeral Ligament",
            "Humerus",
            "Transverse Humeral Ligament",
        ],
    },
    {
        "id": 79,
        "question": "איזו בורסה מונעת חיכוך בין גיד ה- Supraspinatus לבין ה- Acromion?",
        "options": ["Subacromial Bursa", "Subdeltoid Bursa", "Trochanteric Bursa", "Suprapatellar Bursa"],
        "answer": 0,
        "anatomy_components": [
            "Acromion",
            "Subacromial Bursa",
            "Subdeltoid Bursa",
            "Suprapatellar Bursa",
            "Supraspinatus",
            "Trochanteric Bursa",
        ],
    },
    {
        "id": 80,
        "question": "אילו תנועות אופייניות לפריקת כתף קדמית?",
        "options": ["כפיפה וקירוב אופקי", "הרחקה וסיבוב חוץ", "פשיטה וסיבוב פנים", "קירוב וסיבוב פנים"],
        "answer": 1,
        "anatomy_components": ["Glenohumeral Joint"],
    },
    {
        "id": 81,
        "question": "רצועת ה- Coracoclavicular Ligament מחברת בין:",
        "options": [
            "Acromion לבין ה- Clavicle",
            "Coracoid Process לבין ה- Clavicle",
            "Coracoid Process לבין ה- Acromion",
            "Clavicle לבין ה- Humerus",
        ],
        "answer": 1,
        "anatomy_components": [
            "Acromion",
            "Clavicle",
            "Coracoclavicular Ligament",
            "Coracoid Process",
            "Humerus",
        ],
    },
    {
        "id": 82,
        "question": "מהו ה- Origin של שריר ה- Trapezius?",
        "options": [
            "בסיס הגולגולת ועד חוליה T12",
            "חוליות C7-T5",
            "זיזים רוחביים C1-C4",
            "8 הצלעות העליונות",
        ],
        "answer": 0,
        "anatomy_components": ["Trapezius"],
    },
    {
        "id": 83,
        "question": "מהי הפעולה הדו צדדית של שריר ה- Levator Scapula?",
        "options": [
            "Elevation ו- Extension של הצוואר",
            "Elevation ו- Side Flexion של הצוואר",
            "Depression ו- Flexion של הצוואר",
            "Protraction ו- Upward Rotation של השכמה",
        ],
        "answer": 0,
        "anatomy_components": ["Levator Scapulae"],
    },
    {
        "id": 84,
        "question": "מי מהשרירים הבאים מבצע Protraction של השכמה יחד עם Anterior Tilt?",
        "options": ["Rhomboids", "Levator Scapula", "Trapezius", "Pectoralis Minor"],
        "answer": 3,
        "anatomy_components": ["Levator Scapulae", "Pectoralis Minor", "Rhomboid", "Trapezius"],
    },
    {
        "id": 85,
        "question": "מי מהשרירים הבאים נאחז ב- Lesser Tubercle?",
        "options": ["Supraspinatus", "Infraspinatus", "Teres Minor", "Subscapularis"],
        "answer": 3,
        "anatomy_components": [
            "Infraspinatus",
            "Lesser Tubercle",
            "Subscapularis",
            "Supraspinatus",
            "Teres Minor",
        ],
    },
    {
        "id": 86,
        "question": "מי מצמד השרירים הבאים מבצעים External Rotation במפרק הכתף?",
        "options": [
            "Supraspinatus + Subscapularis",
            "Infraspinatus + Teres Minor",
            "Teres Major + Latissimus Dorsi",
            "Deltoid + Pectoralis Major",
        ],
        "answer": 1,
        "anatomy_components": [
            "Deltoid",
            "Infraspinatus",
            "Latissimus Dorsi",
            "Pectoralis Major",
            "Subscapularis",
            "Supraspinatus",
            "Teres Major",
            "Teres Minor",
        ],
    },
    {
        "id": 87,
        "question": "אילו עצמות משתתפות במפרק המרפק?",
        "options": [
            "Humerus + Radius + Ulna",
            "Humerus + Ulna + Scaphoid",
            "Radius + Ulna + Lunate",
            "Humerus + Radius + Clavicle",
        ],
        "answer": 0,
        "anatomy_components": ["Clavicle", "Elbow Joint", "Humerus", "Lunate", "Radius", "Scaphoid", "Ulna"],
    },
    {
        "id": 88,
        "question": "מי מהרצועות הבאות אינה נמנית עם הרצועות המייצבות של מפרק המרפק?",
        "options": ["M.C.L", "L.C.L", "Annular Ligament", "Coracohumeral Ligament"],
        "answer": 3,
        "anatomy_components": ["Annular Ligament", "Coracohumeral Ligament", "Elbow Joint", "LCL", "MCL"],
    },
    {
        "id": 89,
        "question": "שריר ה- Brachioradialis מבצע Flexion במפרק המרפק בעיקר ב:",
        "options": [
            "מנח סופינציה מלאה",
            "מנח פרונציה מלאה",
            "עמדת אמצע של האמה",
            "מנח כפיפה של שורש כף היד",
        ],
        "answer": 2,
        "anatomy_components": ["Brachioradialis", "Elbow Joint"],
    },
    {
        "id": 90,
        "question": "מהו ה- Origin של הראש הארוך (Long Head) של ה- Triceps?",
        "options": ["Lateral Border של השכמה", "Coracoid Process", "Glenoid Fossa", "Spine of Scapula"],
        "answer": 0,
        "anatomy_components": ["Coracoid Process", "Glenoid Fossa", "Spine of Scapula", "Triceps"],
    },
    {
        "id": 91,
        "question": "מהו ה- Origin של שריר ה- Supinator?",
        "options": [
            "Medial Epicondyle של ה- Humerus",
            "Coronoid Process של ה- Ulna",
            "Lateral Epicondyle של ה- Humerus וחלק עליון אחורי של ה- Ulna",
            "1/3 העליון של ה- Radius",
        ],
        "answer": 2,
        "anatomy_components": ["Humerus", "Radius", "Supinator", "Ulna"],
    },
    {
        "id": 92,
        "question": "מי מהעצמות הבאות שייכת לשורה הדיסטלית של עצמות שורש כף היד (Carpal Bones)?",
        "options": ["Lunate", "Scaphoid", "Pisiform", "Hamate"],
        "answer": 3,
        "anatomy_components": ["Hamate", "Lunate", "Pisiform", "Scaphoid"],
    },
    {
        "id": 93,
        "question": "אילו גידים תוחמים את ה- Anatomical Snuffbox (\"תיבת ההרחה\")?",
        "options": [
            "Flexor Carpi Radialis, Palmaris Longus, Flexor Carpi Ulnaris",
            "Extensor Pollicis Longus, Extensor Pollicis Brevis, Abductor Pollicis Longus",
            "Extensor Digitorum, Extensor Indicis, Extensor Digiti Minimi",
            "Pronator Teres, Supinator, Brachioradialis",
        ],
        "answer": 1,
        "anatomy_components": [
            "Abductor Pollicis Longus",
            "Brachioradialis",
            "Extensor Digiti Minimi",
            "Extensor Digitorum",
            "Extensor Indicis",
            "Extensor Pollicis Brevis",
            "Extensor Pollicis Longus",
            "Flexor Carpi Radialis",
            "Flexor Carpi Ulnaris",
            "Palmaris Longus",
            "Pronator Teres",
            "Supinator",
        ],
    },
    {
        "id": 94,
        "question": "מפרק שורש כף היד (Radio Carpal Joint) הוא מפרק:",
        "options": [
            "חד צירי (Uniaxial)",
            "דו צירי (Biaxial)",
            "רב צירי (Multiaxial)",
            "לא צירי (Non-axial)",
        ],
        "answer": 1,
        "anatomy_components": ["Radiocarpal Joint"],
    },
    {
        "id": 95,
        "question": "איזו תנועה מהבאות אינה מתבצעת במפרק שורש כף היד?",
        "options": ["Palmar Flexion", "Ulnar Deviation", "Pronation", "Dorsi Flexion"],
        "answer": 2,
        "anatomy_components": ["Radiocarpal Joint"],
    },
    {
        "id": 96,
        "question": "איזו רצועה מהבאות שייכת למפרק שורש כף היד?",
        "options": [
            "Coracohumeral Ligament",
            "Deltoid Ligament",
            "Annular Ligament",
            "Palmar Radiocarpal Ligament",
        ],
        "answer": 3,
        "anatomy_components": [
            "Annular Ligament",
            "Coracohumeral Ligament",
            "Deltoid Ligament",
            "Palmar Radiocarpal Ligament",
            "Radiocarpal Joint",
        ],
    },
    {
        "id": 97,
        "question": "המפרקים שבין עצמות שורש כף היד (Intercarpal Joints) הם מפרקים סינוביאליים מסוג:",
        "options": ["Gliding", "Hinge", "Saddle", "Condyloid"],
        "answer": 0,
        "anatomy_components": ["Intercarpal Joint"],
    },
    {
        "id": 98,
        "question": "אילו תנועות מתאפשרות במפרק C.M.C 1 (של האגודל)?",
        "options": [
            "Flexion, Extension, Abduction, Adduction",
            "Flexion ו- Extension בלבד",
            "Pronation ו- Supination",
            "Gliding בלבד",
        ],
        "answer": 0,
        "anatomy_components": ["CMC 1 Joint"],
    },
    {
        "id": 99,
        "question": "מפרקי M.P 2-5 הם מפרקים סינוביאליים מסוג:",
        "options": ["Hinge", "Saddle", "Condyloid", "Pivot"],
        "answer": 2,
        "anatomy_components": ["MP Joint"],
    },
    {
        "id": 100,
        "question": "מפרקי ה- P.I.P וה- D.I.P הם מפרקים מסוג Hinge, ולכן מאפשרים:",
        "options": [
            "Flexion ו- Extension בלבד",
            "Flexion, Extension, Abduction ו- Adduction",
            "Opposition",
            "Pronation ו- Supination",
        ],
        "answer": 0,
        "anatomy_components": ["DIP Joint", "PIP Joint"],
    },
    {
        "id": 101,
        "question": "מרבית מכופפי שורש כף היד והאצבעות יוצאים מ-:",
        "options": ["Lateral Epicondyle", "Medial Epicondyle", "Radius", "Interosseous Membrane"],
        "answer": 1,
        "anatomy_components": ["Interosseous Membrane", "Lateral Epicondyle", "Medial Epicondyle", "Radius"],
    },
    {
        "id": 102,
        "question": "מי מהשרירים הבאים שייך לקבוצה העמוקה של מכופפי כף היד והאצבעות?",
        "options": [
            "Palmaris Longus",
            "Flexor Carpi Radialis",
            "Flexor Pollicis Longus",
            "Flexor Digitorum Superficialis",
        ],
        "answer": 2,
        "anatomy_components": [
            "Flexor Carpi Radialis",
            "Flexor Digitorum Superficialis",
            "Flexor Pollicis Longus",
            "Palmaris Longus",
        ],
    },
    {
        "id": 103,
        "question": "מי מהשרירים הבאים מבצע כפיפה של שורש כף היד יחד עם Ulnar Deviation?",
        "options": [
            "Flexor Carpi Radialis",
            "Palmaris Longus",
            "Flexor Carpi Ulnaris",
            "Flexor Digitorum Superficialis",
        ],
        "answer": 2,
        "anatomy_components": [
            "Flexor Carpi Radialis",
            "Flexor Carpi Ulnaris",
            "Flexor Digitorum Superficialis",
            "Palmaris Longus",
        ],
    },
    {
        "id": 104,
        "question": "איזה שריר ממכופפי שורש כף היד מסתיים ב- Palmar Aponeurosis?",
        "options": ["Palmaris Longus", "Flexor Carpi Ulnaris", "Flexor Carpi Radialis", "Pronator Teres"],
        "answer": 0,
        "anatomy_components": [
            "Flexor Carpi Radialis",
            "Flexor Carpi Ulnaris",
            "Palmar Aponeurosis",
            "Palmaris Longus",
            "Pronator Teres",
        ],
    },
    {
        "id": 105,
        "question": "מי מהשרירים הבאים מכופף גם את מפרקי ה- D.I.P של אצבעות 2-5?",
        "options": [
            "Flexor Digitorum Superficialis",
            "Palmaris Longus",
            "Flexor Carpi Radialis",
            "Flexor Digitorum Profundus",
        ],
        "answer": 3,
        "anatomy_components": [
            "DIP Joint",
            "Flexor Carpi Radialis",
            "Flexor Digitorum Profundus",
            "Flexor Digitorum Superficialis",
            "Palmaris Longus",
        ],
    },
    {
        "id": 106,
        "question": "שריר ה- Common Extensor יוצא מ- Lateral Epicondyle של ה- Humerus, וגירוי במקום זה מוכר כ-:",
        "options": ["Golfer's Elbow", "Tennis Elbow", "Carpal Tunnel Syndrome", "De Quervain"],
        "answer": 1,
        "anatomy_components": ["Humerus", "Lateral Epicondyle"],
    },
    {
        "id": 107,
        "question": "מי מהשרירים הבאים מבצע Extension של שורש כף היד יחד עם Ulnar Deviation?",
        "options": [
            "Extensor Carpi Radialis Longus",
            "Extensor Carpi Radialis Brevis",
            "Extensor Indicis",
            "Extensor Carpi Ulnaris",
        ],
        "answer": 3,
        "anatomy_components": [
            "Extensor Carpi Radialis Brevis",
            "Extensor Carpi Radialis Longus",
            "Extensor Carpi Ulnaris",
            "Extensor Indicis",
        ],
    },
    {
        "id": 108,
        "question": "מי מהשרירים הבאים שייך לקבוצת השרירים המניעה את האגודל?",
        "options": [
            "Extensor Digitorum",
            "Extensor Indicis",
            "Extensor Digiti Minimi",
            "Abductor Pollicis Longus",
        ],
        "answer": 3,
        "anatomy_components": [
            "Abductor Pollicis Longus",
            "Extensor Digiti Minimi",
            "Extensor Digitorum",
            "Extensor Indicis",
        ],
    },
    {
        "id": 109,
        "question": "היכן מתחיל (Origin) השריר Extensor Indicis?",
        "options": [
            "Lateral Epicondyle",
            "Medial Epicondyle",
            "Ulna + Interosseous Membrane",
            "Radius בלבד",
        ],
        "answer": 2,
        "anatomy_components": [
            "Extensor Indicis",
            "Interosseous Membrane",
            "Lateral Epicondyle",
            "Medial Epicondyle",
            "Radius",
            "Ulna",
        ],
    },
    {
        "id": 110,
        "question": "אילו עצמות משתתפות במפרק ה- Sacro Iliac Joint?",
        "options": ["Femur + Ilium", "Sacrum + Ilium", "Ilium + Pubis", "Acetabulum + Femur"],
        "answer": 1,
        "anatomy_components": ["Acetabulum", "Femur", "Ilium", "Pubis", "Sacroiliac Joint", "Sacrum"],
    },
    {
        "id": 111,
        "question": "איזו רצועה מחברת בין ה- Sacrum ל- Ischial Tuberosity?",
        "options": [
            "Sacrospinous Ligament",
            "Sacrotuberous Ligament",
            "Iliofemoral Ligament",
            "Transverse Acetabular Ligament",
        ],
        "answer": 1,
        "anatomy_components": [
            "Iliofemoral Ligament",
            "Ischial Tuberosity",
            "Sacrospinous Ligament",
            "Sacrotuberous Ligament",
            "Sacrum",
            "Transverse Acetabular Ligament",
        ],
    },
    {
        "id": 112,
        "question": "מפרק הירך (Hip Joint) הוא מפרק מסוג:",
        "options": ["Hinge", "Saddle", "Ball & Socket", "Gliding"],
        "answer": 2,
        "anatomy_components": ["Hip Joint"],
    },
    {
        "id": 113,
        "question": "מה משותף לרצועות Ilio Femoral, Ischio Femoral ו- Pubo Femoral?",
        "options": [
            "כולן מגבילות עודף Flexion במפרק הירך",
            "כולן מגבילות עודף Extension במפרק הירך",
            "כולן מגבילות עודף Abduction במפרק הירך",
            "כולן שייכות למפרק הברך",
        ],
        "answer": 1,
        "anatomy_components": [
            "Hip Joint",
            "Iliofemoral Ligament",
            "Ischiofemoral Ligament",
            "Knee Joint",
            "Pubofemoral Ligament",
        ],
    },
    {
        "id": 114,
        "question": "שריר ה- Ilio Psoas מורכב משני השרירים:",
        "options": [
            "Psoas Major + Iliacus",
            "Iliacus + Pectineus",
            "Psoas Major + Sartorius",
            "Iliacus + Gluteus Minimus",
        ],
        "answer": 0,
        "anatomy_components": [
            "Gluteus Minimus",
            "Iliacus",
            "Iliopsoas",
            "Pectineus",
            "Psoas Major",
            "Sartorius",
        ],
    },
    {
        "id": 115,
        "question": "מי מהפעולות הבאות אינה מפעולותיו של ה- Tensor Fascia Latae?",
        "options": [
            "Abduction במפרק ירך",
            "Internal Rotation במפרק ירך",
            "Extension במפרק ירך",
            "Flexion במפרק ירך",
        ],
        "answer": 2,
        "anatomy_components": ["Tensor Fasciae Latae"],
    },
    {
        "id": 116,
        "question": "לאילו שני שרירים Origin משותף ב- A.S.I.S?",
        "options": [
            "Sartorius + Tensor Fascia Latae",
            "Rectus Femoris + Sartorius",
            "Gluteus Medius + Piriformis",
            "Biceps Femoris + Semitendinosus",
        ],
        "answer": 0,
        "anatomy_components": [
            "ASIS",
            "Biceps Femoris",
            "Gluteus Medius",
            "Piriformis",
            "Rectus Femoris",
            "Sartorius",
            "Semitendinosus",
            "Tensor Fasciae Latae",
        ],
    },
    {
        "id": 117,
        "question": "איזה שריר אחראי לייצוב האגן בעמידה על רגל אחת?",
        "options": ["Psoas Major", "Adductor Longus", "Semimembranosus", "Gluteus Medius"],
        "answer": 3,
        "anatomy_components": ["Adductor Longus", "Gluteus Medius", "Psoas Major", "Semimembranosus"],
    },
    {
        "id": 118,
        "question": "מי מהשרירים הבאים אינו נמנה עם ה- External Rotators של מפרק הירך?",
        "options": ["Quadratus Femoris", "Obturator Internus", "Gluteus Minimus", "Gemellus Superior"],
        "answer": 2,
        "anatomy_components": [
            "Gemellus Superior",
            "Gluteus Minimus",
            "Hip Joint",
            "Obturator Internus",
            "Quadratus Femoris",
        ],
    },
    {
        "id": 119,
        "question": "מי מהשרירים הבאים אינו שייך לקבוצת מקרבי הירך (Hip Adductors)?",
        "options": ["Pectineus", "Gracilis", "Adductor Magnus", "Sartorius"],
        "answer": 3,
        "anatomy_components": ["Adductor Magnus", "Gracilis", "Pectineus", "Sartorius"],
    },
    {
        "id": 120,
        "question": "מפרק ה- Tibiofemoral הוא מפרק מסוג:",
        "options": ["Ball & Socket", "Gliding", "Hinge", "Saddle"],
        "answer": 2,
        "anatomy_components": ["Tibiofemoral Joint"],
    },
    {
        "id": 121,
        "question": "מהו תפקידן של הרצועות M.C.L ו- L.C.L במפרק הברך?",
        "options": [
            "למנוע עודף תנועה במישור הסגיטלי",
            "למנוע עודף תנועה במישור הפרונטלי",
            "לבלום זעזועים בין ה- Femur ל- Tibia",
            "למנוע רוטציה של השוק ביחס לירך",
        ],
        "answer": 1,
        "anatomy_components": ["Femur", "Knee Joint", "LCL", "MCL", "Tibia"],
    },
    {
        "id": 122,
        "question": "מי מהבאים אינו מתפקידי המניסקוסים במפרק הברך?",
        "options": ["בלימת זעזועים", "מניעת חיכוך", "פיזור הנוזל הסינוביאלי", "הנעת מפרק הברך ל- Extension"],
        "answer": 3,
        "anatomy_components": ["Knee Joint", "Lateral Meniscus", "Medial Meniscus"],
    },
    {
        "id": 123,
        "question": "הפטלה (Patella) שזורה בתוך גידו של השריר:",
        "options": ["Hamstrings", "Sartorius", "Popliteus", "Quadriceps"],
        "answer": 3,
        "anatomy_components": ["Hamstrings", "Patella", "Popliteus", "Quadriceps", "Sartorius"],
    },
    {
        "id": 124,
        "question": "מי מהבאים אינו אחד מארבעת ראשי ה- Quadriceps?",
        "options": ["Vastus Intermedius", "Rectus Femoris", "Biceps Femoris", "Vastus Lateralis"],
        "answer": 2,
        "anatomy_components": [
            "Biceps Femoris",
            "Quadriceps",
            "Rectus Femoris",
            "Vastus Intermedius",
            "Vastus Lateralis",
        ],
    },
    {
        "id": 125,
        "question": "מי משרירי ה- Hamstring נאחז ב- Head Of Fibula?",
        "options": ["Biceps Femoris", "Semitendinosus", "Semimembranosus", "Popliteus"],
        "answer": 0,
        "anatomy_components": [
            "Biceps Femoris",
            "Hamstrings",
            "Head of Fibula",
            "Popliteus",
            "Semimembranosus",
            "Semitendinosus",
        ],
    },
    {
        "id": 126,
        "question": "שריר ה- Popliteus מבצע במפרק הברך:",
        "options": [
            "Internal Rotation ו- Flexion",
            "Extension ו- External Rotation",
            "Abduction ו- Adduction",
            "Extension ו- Flexion בלבד",
        ],
        "answer": 0,
        "anatomy_components": ["Knee Joint", "Popliteus"],
    },
    {
        "id": 127,
        "question": "מפרק ה- Proximal Tibiofibular Joint הוא מפרק מסוג:",
        "options": ["Hinge", "Gliding", "Pivot", "Ball & Socket"],
        "answer": 1,
        "anatomy_components": ["Proximal Tibiofibular Joint"],
    },
    {
        "id": 128,
        "question": "מי מהעצמות הבאות אינה שייכת ל- Tarsal Bones?",
        "options": ["Fibula", "Talus", "Cuboid", "Navicular"],
        "answer": 0,
        "anatomy_components": ["Cuboid", "Fibula", "Navicular", "Talus", "Tarsal Bones"],
    },
    {
        "id": 129,
        "question": "אילו עצמות בונות את ה- Medial Longitudinal Arch?",
        "options": [
            "Calcaneus, Cuboid, head metatarsal 4+5",
            "Calcaneus, Talus, Navicular, head metatarsal 1-3",
            "Tibia, Fibula, Talus",
            "Talus + Calcaneus",
        ],
        "answer": 1,
        "anatomy_components": [
            "Calcaneus",
            "Cuboid",
            "Fibula",
            "Metatarsal Bones",
            "Navicular",
            "Talus",
            "Tibia",
        ],
    },
    {
        "id": 130,
        "question": "רצועת ה- Spring Ligament ( Plantar Calcaneo-Navicular ) מחברת בין:",
        "options": [
            "Calcaneus ל- Cuboid",
            "Talus ל- Fibula",
            "Calcaneus ל- Navicular",
            "Navicular ל- Metatarsal 1",
        ],
        "answer": 2,
        "anatomy_components": [
            "Calcaneus",
            "Cuboid",
            "Fibula",
            "Metatarsal Bones",
            "Navicular",
            "Spring Ligament",
            "Talus",
        ],
    },
    {
        "id": 131,
        "question": "איזו רצועה מחברת בין ה- Calcaneus, ה- Cuboid וה- Metatarsal bone?",
        "options": ["Short Plantar Ligament", "Spring Ligament", "A.T.F.L", "Long Plantar Ligament"],
        "answer": 3,
        "anatomy_components": [
            "ATFL",
            "Calcaneus",
            "Cuboid",
            "Long Plantar Ligament",
            "Metatarsal Bones",
            "Short Plantar Ligament",
            "Spring Ligament",
        ],
    },
    {
        "id": 132,
        "question": "אילו עצמות משתתפות במפרק ה- Talo-Crural jt?",
        "options": [
            "Talus, Calcaneus, Navicular",
            "Tibia, Fibula, Calcaneus",
            "Tibia, Talus, Navicular",
            "Tibia, Fibula, Talus",
        ],
        "answer": 3,
        "anatomy_components": ["Calcaneus", "Fibula", "Navicular", "Talocrural Joint", "Talus", "Tibia"],
    },
    {
        "id": 133,
        "question": "מי מהרצועות הבאות אינה חלק מ- Ankle L.C.L?",
        "options": ["A.T.F.L", "Deltoid Ligament", "P.T.F.L", "C.F.L"],
        "answer": 1,
        "anatomy_components": ["ATFL", "Ankle Joint", "CFL", "Deltoid Ligament", "PTFL"],
    },
    {
        "id": 134,
        "question": "מי מהמפרקים הבאים אינו מפרק החלקה ( Gliding )?",
        "options": ["Subtalar jt", "Transverse Tarsal jt", "Talo-Crural jt", "Tarsal-metatarsal jt"],
        "answer": 2,
        "anatomy_components": [
            "Subtalar Joint",
            "Talocrural Joint",
            "Tarsometatarsal Joint",
            "Transverse Tarsal Joint",
        ],
    },
    {
        "id": 135,
        "question": "אילו עצמות משתתפות במפרקי ה- M.T.P?",
        "options": [
            "Tarsal Bones + Metatarsal Bones",
            "Metatarsal Bones + Proximal Phalanges",
            "Proximal Phalanges + Middle Phalanges",
            "Middle Phalanges + Distal Phalanges",
        ],
        "answer": 1,
        "anatomy_components": ["MTP 1 Joint", "Metatarsal Bones", "Phalanges", "Tarsal Bones"],
    },
    {
        "id": 136,
        "question": "איזו תנועה מתאפשרת במפרקי ה- M.T.P אך אינה מתאפשרת במפרקי ה- I.P?",
        "options": ["Flexion", "Extension", "Abduction", "Plantar Flexion"],
        "answer": 2,
        "anatomy_components": ["DIP Joint", "MTP 1 Joint", "PIP Joint"],
    },
    {
        "id": 137,
        "question": "מי מהשרירים הבאים אינו שייך ל- Anterior Compartment?",
        "options": [
            "Tibialis Anterior",
            "Extensor Digitorum Longus",
            "Extensor Hallucis Longus",
            "Peroneus Longus",
        ],
        "answer": 3,
        "anatomy_components": [
            "Extensor Digitorum Longus",
            "Extensor Hallucis Longus",
            "Peroneus Longus",
            "Tibialis Anterior",
        ],
    },
    {
        "id": 138,
        "question": "מי מהשרירים הבאים שייך ללשכה האחורית העמוקה?",
        "options": ["Tibialis Posterior", "Gastrocnemius", "Soleus", "Plantaris"],
        "answer": 0,
        "anatomy_components": ["Gastrocnemius", "Plantaris", "Soleus", "Tibialis Posterior"],
    },
    {
        "id": 139,
        "question": "מי מהשרירים הבאים נאחז ב- Base of 1 Metatarsal?",
        "options": ["Peroneus Brevis", "Tibialis Posterior", "Peroneus Longus", "Flexor Digitorum Longus"],
        "answer": 2,
        "anatomy_components": [
            "Flexor Digitorum Longus",
            "Metatarsal Bones",
            "Peroneus Brevis",
            "Peroneus Longus",
            "Tibialis Posterior",
        ],
    },
    {
        "id": 140,
        "question": "אילו שרירים מבצעים Eversion?",
        "options": [
            "Tibialis Anterior + Tibialis Posterior",
            "Gastrocnemius + Soleus",
            "Flexor Digitorum Longus + Flexor Hallucis Longus",
            "Peroneus Longus + Peroneus Brevis",
        ],
        "answer": 3,
        "anatomy_components": [
            "Flexor Digitorum Longus",
            "Flexor Hallucis Longus",
            "Gastrocnemius",
            "Peroneus Brevis",
            "Peroneus Longus",
            "Soleus",
            "Tibialis Anterior",
            "Tibialis Posterior",
        ],
    },
    {
        "id": 141,
        "question": "מי משרירי הלשכה האחורית חוצה גם את מפרק הברך ומסייע ב- Flexion של הברך?",
        "options": ["Soleus", "Gastrocnemius", "Tibialis Posterior", "Flexor Hallucis Longus"],
        "answer": 1,
        "anatomy_components": [
            "Flexor Hallucis Longus",
            "Gastrocnemius",
            "Knee Joint",
            "Soleus",
            "Tibialis Posterior",
        ],
    },
    {
        "id": 142,
        "question": "מהו ה- Origin של ה- Plantaris?",
        "options": ["Head of fibula", "Proximal Lateral Tibia", "Calcaneus", "Lateral Condyle Of Femur"],
        "answer": 3,
        "anatomy_components": ["Calcaneus", "Femur", "Fibula", "Plantaris", "Tibia"],
    },
    {
        "id": 143,
        "question": "מי מהשרירים הבאים נאחז ב- Distal Phalanges of hallux ומבצע Extension של הבוהן?",
        "options": [
            "Flexor Hallucis Longus",
            "Extensor Hallucis Longus",
            "Extensor Digitorum Longus",
            "Flexor Digitorum Longus",
        ],
        "answer": 1,
        "anatomy_components": [
            "Extensor Digitorum Longus",
            "Extensor Hallucis Longus",
            "Flexor Digitorum Longus",
            "Flexor Hallucis Longus",
            "Phalanges",
        ],
    },
    {
        "id": 144,
        "question": "מי מהשרירים הבאים מבצע Inversion יחד עם ה- Tibialis Anterior?",
        "options": ["Tibialis Posterior", "Peroneus Longus", "Peroneus Brevis", "Extensor Digitorum Longus"],
        "answer": 0,
        "anatomy_components": [
            "Extensor Digitorum Longus",
            "Peroneus Brevis",
            "Peroneus Longus",
            "Tibialis Anterior",
            "Tibialis Posterior",
        ],
    },
    {
        "id": 145,
        "question": "מי מהשרירים הבאים נאחז ב- Base of distal phalanges 2-5 ומבצע Flexion של אצבעות 2-5?",
        "options": [
            "Flexor Digitorum Longus",
            "Extensor Digitorum Longus",
            "Flexor Hallucis Longus",
            "Tibialis Posterior",
        ],
        "answer": 0,
        "anatomy_components": [
            "Extensor Digitorum Longus",
            "Flexor Digitorum Longus",
            "Flexor Hallucis Longus",
            "Phalanges",
            "Tibialis Posterior",
        ],
    },
    {
        "id": 146,
        "question": "מהי רקמת החיבור הקולגנית המחוברת בין סוף עצם ה- Sternum אל עצמות ה- Pubis ואליה נקשרים כל שרירי הבטן?",
        "options": ["Thoracolumbar Fascia", "Iliac Crest", "Linea Alba", "Mastoid Process"],
        "answer": 2,
        "anatomy_components": [
            "Iliac Crest",
            "Linea Alba",
            "Mastoid Process",
            "Pubis",
            "Sternum",
            "Thoracolumbar Fascia",
        ],
    },
    {
        "id": 147,
        "question": "מהי נקודת ה- Origin של שריר ה- Rectus Abdominis?",
        "options": ["Pubis", "Iliac Crest", "Thoracolumbar Fascia", "צלעות 5-7"],
        "answer": 0,
        "anatomy_components": ["Iliac Crest", "Pubis", "Rectus Abdominis", "Thoracolumbar Fascia"],
    },
    {
        "id": 148,
        "question": "לאיזה משרירי הבטן יש Origin בחלק החיצוני של 8 הצלעות התחתונות ( 5-12 )?",
        "options": ["Internal Oblique", "Transverse Abdominis", "Rectus Abdominis", "External Oblique"],
        "answer": 3,
        "anatomy_components": [
            "External Oblique",
            "Internal Oblique",
            "Rectus Abdominis",
            "Transverse Abdominis",
        ],
    },
    {
        "id": 149,
        "question": "לאיזה משרירי הבטן יש Origin ב- Thoracolumbar Fascia וב- Iliac Crest ו- Insertion ב-4 הצלעות התחתונות ( 8-12 ) וב- Linea Alba?",
        "options": ["External Oblique", "Internal Oblique", "Rectus Abdominis", "Transverse Abdominis"],
        "answer": 1,
        "anatomy_components": [
            "External Oblique",
            "Iliac Crest",
            "Internal Oblique",
            "Linea Alba",
            "Rectus Abdominis",
            "Thoracolumbar Fascia",
            "Transverse Abdominis",
        ],
    },
    {
        "id": 150,
        "question": "מהי הפעולה של שריר ה- Transverse Abdominis?",
        "options": [
            "Extension של עמוד השדרה",
            "העלאת הלחץ התוך בטני",
            "רוטציה של הגו לכיוון הנגדי",
            "Lateral Pelvic Tilt",
        ],
        "answer": 1,
        "anatomy_components": ["Transverse Abdominis"],
    },
    {
        "id": 151,
        "question": "מתחת ל- Arcuate Line, כיצד עוברות האפונורוזות של External Oblique, Internal Oblique ו- Transverse Abdominis ביחס לשריר ה- Rectus Abdominis?",
        "options": [
            "כולן עוברות מלפנים לשריר",
            "כולן עוברות מאחורי השריר",
            "שתיים מלפנים ואחת מאחור",
            "אחת מלפנים ושתיים מאחור",
        ],
        "answer": 0,
        "anatomy_components": [
            "Arcuate Line",
            "External Oblique",
            "Internal Oblique",
            "Rectus Abdominis",
            "Transverse Abdominis",
        ],
    },
    {
        "id": 152,
        "question": "מהי הפעולה של זוקפי הגב השטחיים ( Erector Spinae )?",
        "options": [
            "Flexion של עמוד השדרה ו- P.P.T",
            "העלאת הלחץ התוך בטני",
            "Extension של עמוד השדרה, Side Flexion ו- A.P.T",
            "רוטציה של הצוואר לכיוון הנגדי",
        ],
        "answer": 2,
        "anatomy_components": ["Erector Spinae"],
    },
    {
        "id": 153,
        "question": "מי מזוקפי הגב השטחיים הוא הלטרלי ביותר?",
        "options": ["Spinalis", "Multifidus", "Longissimus", "Iliocostalis"],
        "answer": 3,
        "anatomy_components": ["Iliocostalis", "Longissimus", "Multifidus", "Spinalis"],
    },
    {
        "id": 154,
        "question": "מי מהשרירים הבאים אינו שייך לקבוצת ה- Transversospinalis ( זוקפי הגב העמוקים )?",
        "options": ["Semispinalis", "Multifidus", "Longissimus", "Rotatores"],
        "answer": 2,
        "anatomy_components": [
            "Longissimus",
            "Multifidus",
            "Rotatores",
            "Semispinalis",
            "Transversospinalis",
        ],
    },
    {
        "id": 155,
        "question": "מי מהשרירים הבאים מבצע Lateral Pelvic Tilt בכיווץ חד צדדי?",
        "options": ["Rectus Abdominis", "Quadratus Lumborum", "Transverse Abdominis", "Sternocleidomastoid"],
        "answer": 1,
        "anatomy_components": [
            "Quadratus Lumborum",
            "Rectus Abdominis",
            "Sternocleidomastoid",
            "Transverse Abdominis",
        ],
    },
    {
        "id": 156,
        "question": "מהי נקודת ה- Insertion של שריר ה- Sternocleidomastoid?",
        "options": ["Clavicle", "Sternum", "Mastoid Process", "Transverse process C1-C3"],
        "answer": 2,
        "anatomy_components": ["Clavicle", "Mastoid Process", "Sternocleidomastoid", "Sternum"],
    },
    {
        "id": 157,
        "question": "בכיווץ חד צדדי, מה מבצע שריר ה- Sternocleidomastoid?",
        "options": [
            "Side Flexion של הצוואר לאותו הצד ורוטציה לכיוון הנגדי",
            "Side Flexion ורוטציה לאותו הצד",
            "Extension של הצוואר",
            "Flexion של הצוואר",
        ],
        "answer": 0,
        "anatomy_components": ["Sternocleidomastoid"],
    },
    {
        "id": 158,
        "question": "מי מהשרירים הבאים נאחז ב- Rib 2?",
        "options": ["Posterior Scalene", "Anterior Scalene", "Middle Scalene", "Sternocleidomastoid"],
        "answer": 0,
        "anatomy_components": ["Scalene", "Sternocleidomastoid"],
    },
    {
        "id": 159,
        "question": "מהי נקודת ה- Insertion של שריר ה- Splenius Capitis?",
        "options": [
            "Spinus process C4-C7",
            "Transverse process C1-C3",
            "Spinus process T3-T6",
            "Superior Nuchal Line",
        ],
        "answer": 3,
        "anatomy_components": ["Splenius", "Superior Nuchal Line"],
    },
    {
        "id": 160,
        "question": "בכיווץ חד צדדי, מה מבצע שריר ה- Splenius?",
        "options": [
            "Side Flexion לצד הנגדי",
            "רוטציה לאותו הצד",
            "רוטציה לכיוון הנגדי",
            "Flexion של הצוואר",
        ],
        "answer": 1,
        "anatomy_components": ["Splenius"],
    },
    {
        "id": 161,
        "question": "מי מהשרירים הבאים אינו שייך לקבוצת ה- Suboccipital Muscles?",
        "options": [
            "Rectus capitis posterior major",
            "Oblique capitis superior",
            "Rectus capitis posterior minor",
            "Splenius Capitis",
        ],
        "answer": 3,
        "anatomy_components": ["Splenius", "Suboccipital Muscles"],
    },
]
