// Generated from Wikipedia / Wikimedia Commons. Each entry records author,
// license, and source page so the CC BY-SA attribution requirement is met.
// Files are downloaded into frontend/public/anatomy so the pages don't depend
// on any external host staying up.

export interface AnatomyImage {
  src: string
  author: string
  license: string
  source: string
  /** Optional hint for images where several structures are visible at once. */
  note?: string
}

export const anatomyImages: Record<string, AnatomyImage> = {
  Acetabulum: {
    src: '/anatomy/acetabulum-model.png',
    author: 'Protohiro at English Wikipedia',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Acetabulum_(model).jpg',
  },
  'Acromioclavicular Joint': {
    src: '/anatomy/gray326.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray326.png',
  },
  'Ankle Joint': {
    src: '/anatomy/ankle-en.png',
    author: 'An svg version of image:Ankle.PNG by me (Jak)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Ankle_en.svg',
  },
  'Annular Ligament': {
    src: '/anatomy/en-elbow-joint.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:En-elbow_joint.svg',
  },
  'Anterior Deltoid': {
    src: '/anatomy/deltoideus.png',
    author: 'Original: sv:Användare:Chrizz',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Deltoideus.png',
  },
  'Atlanto-Occipital Joint': {
    src: '/anatomy/gray304.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray304.png',
  },
  'Biceps Brachii': {
    src: '/anatomy/biceps-brachii-muscle01.png',
    author: 'Anatomography (background whitened)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Biceps_brachii_muscle01.png',
    note: 'Biceps brachii is the muscle in red. Both heads run up to the scapula — the long head over the shoulder joint, the short head to the coracoid process — and the distal tendon attaches below the elbow.',
  },
  Brachialis: {
    src: '/anatomy/brachialis-muscle01.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Brachialis_muscle01.png',
    note: 'Brachialis is the muscle highlighted in red, deep to the biceps on the front of the upper arm.',
  },
  Brachioradialis: {
    src: '/anatomy/brachioradialis.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Brachioradialis.png',
  },
  'C1-C2 Joint': {
    src: '/anatomy/gray306.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray306.png',
    note: 'The atlas (C1) seen from above. The odontoid process — the peg projecting up from the axis (C2) — is held against the anterior arch by the transverse ligament. C1 and the skull rotate around that peg, which is what makes this a pivot joint.',
  },
  Coracobrachialis: {
    src: '/anatomy/coracobrachialis-muscle05.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Coracobrachialis_muscle05.png',
  },
  'Coracoid Process': {
    src: '/anatomy/coracoid-process-of-left-scapula02.png',
    author: 'BodyParts3D is made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Coracoid_process_of_left_scapula02.png',
  },
  'DIP Joint': {
    src: '/anatomy/dip-pip-and-mcp-joints-of-hand.png',
    author: 'Kohlins',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:DIP,_PIP_and_MCP_joints_of_hand.jpg',
  },
  Deltoid: {
    src: '/anatomy/deltoideus.png',
    author: 'Original: sv:Användare:Chrizz',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Deltoideus.png',
  },
  'Extensor Indicis': {
    src: '/anatomy/gray421.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray421.png',
  },
  'External Oblique': {
    src: '/anatomy/external-oblique-highlighted.png',
    author: 'Henry Vandyke Carter (recoloured: external oblique in red, rest of the plate greyed)',
    license: 'CC0',
    source: 'https://commons.wikimedia.org/wiki/File:Grays_Anatomy_Muscle_oblique_externe.png',
    note: 'The external oblique is the muscle highlighted in red, with OBLIQUUS EXTERNUS labelled across it. It is the outermost of the three flat abdominal wall muscles.',
  },
  Femur: {
    src: '/anatomy/femur-anterior-view2.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Femur_-_anterior_view2.png',
  },
  'Flexor Digitorum Longus': {
    src: '/anatomy/inferior-view-of-flexor-digitorum-longus-muscle-posterior.png',
    author: 'Polygon data were generated by Database Center for Life Science (DBCLS) (background removed)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Inferior_view_of_flexor_digitorum_longus_muscle_-_posterior.png',
    note: 'Posterior view. The muscle belly is red on the back of the tibia, and its four tendons are visible splaying out to the lateral four toes.',
  },
  'Flexor Pollicis Longus': {
    src: '/anatomy/musculus-flexor-pollicis-longus.png',
    author: "Gray's Anatomy plate, highlighted by a Wikimedia contributor",
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Musculus_flexor_pollicis_longus.png',
  },
  'Gluteus Maximus': {
    src: '/anatomy/gluteus-maximus-3d.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Gluteus_maximus_3D.gif',
  },
  'Gluteus Medius': {
    src: '/anatomy/posterior-hip-muscles-3.png',
    author: 'Unknown',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Posterior_Hip_Muscles_3.PNG',
  },
  'Greater Trochanter': {
    src: '/anatomy/gray243.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray243.png',
  },
  Hamstrings: {
    src: '/anatomy/hamstrings.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Hamstrings.gif',
  },
  'Hip Joint': {
    src: '/anatomy/blausen-0488-hipanatomy.png',
    author: 'BruceBlaus',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Blausen_0488_HipAnatomy.png',
  },
  Iliopsoas: {
    src: '/anatomy/anterior-hip-muscles-2.png',
    author: 'Beth ohara',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Anterior_Hip_Muscles_2.PNG',
    note: 'Iliopsoas is not one muscle but two acting together: psoas major and iliacus, both labelled at the top of this anterior view of the hip.',
  },
  'Internal Oblique': {
    src: '/anatomy/gray395.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray395.png',
    note: 'OBLIQUUS INTERNUS is labelled across the muscle belly. This layer sits directly beneath the external oblique, exposed here with the external oblique removed.',
  },
  LCL: {
    src: '/anatomy/gray348.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray348.png',
  },
  'Latissimus Dorsi': {
    src: '/anatomy/latissimus-dorsi-muscle-back.png',
    author: 'Anatomography (background whitened)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Latissimus_dorsi_muscle_back.png',
  },
  MCL: {
    src: '/anatomy/knee-medial-view.png',
    author: 'National Institute of Arthritis and Musculoskeletal and Skin Diseases (NIAMS)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Knee_medial_view.gif',
  },
  'Obturator Internus': {
    src: '/anatomy/posterior-hip-muscles-1.png',
    author: 'Beth ohara',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Posterior_Hip_Muscles_1.PNG',
  },
  PCL: {
    src: '/anatomy/knee-medial-view.png',
    author: 'National Institute of Arthritis and Musculoskeletal and Skin Diseases (NIAMS)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Knee_medial_view.gif',
  },
  'PIP Joint': {
    src: '/anatomy/dip-pip-and-mcp-joints-of-hand.png',
    author: 'Kohlins',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:DIP,_PIP_and_MCP_joints_of_hand.jpg',
  },
  Patella: {
    src: '/anatomy/anterioraspectofrightpatella.png',
    author: 'John Doe',
    license: 'CC0',
    source: 'https://commons.wikimedia.org/wiki/File:AnteriorAspectOfRightPatella.png',
  },
  'Patellofemoral Joint': {
    src: '/anatomy/knee-diagram.png',
    author: 'Mysid',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Knee_diagram.svg',
  },
  'Pectoralis Major': {
    src: '/anatomy/gray410.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray410.png',
  },
  'Pectoralis Minor': {
    src: '/anatomy/pectoralis-minor.png',
    author: 'Original: ‍Användare:Chrizz Vector: Pixelsquid🎱',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Pectoralis_minor.svg',
  },
  'Phalang 1': {
    src: '/anatomy/scheme-human-hand-bones-en.png',
    author: 'Mariana Ruiz Villarreal (LadyofHats); retouches by Nyks',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Scheme_human_hand_bones-en.svg',
  },
  Piriformis: {
    src: '/anatomy/piriformis.png',
    author: 'Johannes Sobotta',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Piriformis.jpg',
  },
  'Posterior Deltoid': {
    src: '/anatomy/deltoideus.png',
    author: 'Original: sv:Användare:Chrizz',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Deltoideus.png',
  },
  'Proximal Radioulnar Joint': {
    src: '/anatomy/gray333.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray333.png',
  },
  'Proximal Tibiofibular Joint': {
    src: '/anatomy/gray351.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray351.png',
  },
  Quadriceps: {
    src: '/anatomy/quadriceps-3d.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Quadriceps_3D.gif',
  },
  'Radiocarpal Joint': {
    src: '/anatomy/gray335.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray335.png',
  },
  'Radioulnar Joint': {
    src: '/anatomy/gray334.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray334.png',
  },
  Radius: {
    src: '/anatomy/radius-anterior-view2.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Radius_-_anterior_view2.png',
  },
  'Rectus Abdominis': {
    src: '/anatomy/rectus-abdominis.png',
    author: 'Unknown',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Rectus_abdominis.png',
  },
  Rhomboid: {
    src: '/anatomy/rhomboidei.png',
    author: 'Mikael Häggström',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Rhomboidei.PNG',
  },
  Semimembranosus: {
    src: '/anatomy/semimembranosus.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Semimembranosus.gif',
  },
  Semitendinosus: {
    src: '/anatomy/semitendinosus.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Semitendinosus.png',
  },
  'Serratus Anterior': {
    src: '/anatomy/serratus-anterior-muscles-lateral.png',
    author: 'Anatomography (background whitened)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Serratus_anterior_muscles_lateral.png',
  },
  'Sternoclavicular Joint': {
    src: '/anatomy/gray325.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray325.png',
  },
  Subscapularis: {
    src: '/anatomy/subscapularis-muscle-frontal.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Subscapularis_muscle_frontal.png',
  },
  'Subtalar Joint': {
    src: '/anatomy/subtalar-joint.png',
    author: 'Unknown',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Subtalar_Joint.svg',
  },
  Supraspinatus: {
    src: '/anatomy/supraspinatus-muscle-back4.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Supraspinatus_muscle_back4.png',
  },
  'Teres Major': {
    src: '/anatomy/teres-major-muscle-back.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Teres_major_muscle_back.png',
  },
  'Teres Minor': {
    src: '/anatomy/teres-minor-muscle-back3.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Teres_minor_muscle_back3.png',
  },
  Tibia: {
    src: '/anatomy/tibia-frontal-view.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Tibia_-_frontal_view.png',
  },
  'Tibialis Anterior': {
    src: '/anatomy/tibialis.png',
    author: 'Bildberabetning: sv:Användare:Chrizz. Original uploader was Chrizz at sv.wikipedia',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tibialis.png',
  },
  'Tibialis Posterior': {
    src: '/anatomy/superior-view-of-tibialis-posterior-muscle-posterior.png',
    author: 'Polygon data were generated by Database Center for Life Science (DBCLS) (background removed)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Superior_view_of_tibialis_posterior_muscle_-_posterior.png',
    note: 'Posterior view of both lower legs. Tibialis posterior is the muscle in red, running down the back of the tibia and fibula and passing behind the medial malleolus into the foot.',
  },
  'Tibiofemoral Joint': {
    src: '/anatomy/blausen-0597-kneeanatomy-side.png',
    author: 'BruceBlaus',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Blausen_0597_KneeAnatomy_Side.png',
  },
  Trapezius: {
    src: '/anatomy/trapezius.png',
    author: 'Unknown',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Trapezius.png',
  },
  Triceps: {
    src: '/anatomy/triceps-brachii-muscle06.png',
    author: 'BodyParts3D / DBCLS (Anatomography), background whitened',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Triceps_brachii_muscle06.png',
    note: 'Posterior view with the three heads coloured separately: long head in red, lateral head in yellow, medial head in green. Only the long head crosses the shoulder, which is why it can extend the shoulder as well as the elbow.',
  },
  'Extensor Digitorum': {
    src: '/anatomy/extensor-digitorum-muscle.png',
    author: 'Mikael Häggström. When using this image in external works, it may be c',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Extensor_digitorum_muscle.png',
  },
  'Abductor Pollicis Brevis': {
    src: '/anatomy/musculus-abductor-pollicis-brevis-red.png',
    author: 'Arent',
    license: 'CC0',
    source: 'https://commons.wikimedia.org/wiki/File:Musculus_abductor_pollicis_brevis_-_red.png',
  },
  'Flexor Carpi Ulnaris': {
    src: '/anatomy/gray-musculus-flexor-carpi-ulnaris.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray_%E2%80%94_musculus_flexor_carpi_ulnaris.png',
  },
  Supinator: {
    src: '/anatomy/gray-musculus-supinator.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray_%E2%80%94_musculus_supinator.png',
  },
  'Pronator Teres': {
    src: '/anatomy/gray-musculus-pronator-teres.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray_%E2%80%94_musculus_pronator_teres.png',
  },
  Ulna: {
    src: '/anatomy/ulna-anterior-view.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Ulna_-_anterior_view.png',
  },
  Scaphoid: {
    src: '/anatomy/scaphoid-bone-left-hand-01-palmar-view.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Scaphoid_bone_(left_hand)_01_palmar_view.png',
  },
  Lunate: {
    src: '/anatomy/lunate-bone-left-hand-01-palmar-view.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Lunate_bone_(left_hand)_01_palmar_view.png',
  },
  'Metacarpal 2': {
    src: '/anatomy/second-metacarpal-bone-left-hand-01-palmar-view.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Second_metacarpal_bone_(left_hand)_01_palmar_view.png',
  },
  Infraspinatus: {
    src: '/anatomy/a-infraspinatus-back2.png',
    author: 'Anatomography (BodyParts3D / DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Infraspinatus_muscle_back2.png',
  },
  'Levator Scapulae': {
    src: '/anatomy/a-levator-scapulae-lateral.png',
    author: 'Anatomography (BodyParts3D / DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Levator_scapulae_muscle_lateral.png',
  },
  Sternocleidomastoid: {
    src: '/anatomy/a-scm-anatomography.png',
    author: 'Henry Vandyke Carter (Gray\'s Anatomy plate 385), colourised by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Sternocleidomastoideus.png',
  },
  'Palmaris Longus': {
    src: '/anatomy/a-palmaris-longus-gray.png',
    author: 'Henry Vandyke Carter (Gray\'s Anatomy)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray_%E2%80%94_musculus_palmaris_longus.png',
  },
  Humerus: {
    src: '/anatomy/a-humerus-anterior.png',
    author: 'Anatomography (BodyParts3D / DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Humerus_-_anterior_view.png',
  },
  Acromion: {
    src: '/anatomy/a-acromion-left-scapula01.png',
    author: 'BodyParts3D, made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Acromion_of_left_scapula01.png',
  },
  'Glenoid Fossa': {
    src: '/anatomy/a-glenoid-cavity01.png',
    author: 'BodyParts3D / DBCLS (polygon data)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Glenoid_cavity_of_scapula01.png',
  },
  'Bicipital Groove': {
    src: '/anatomy/a-bicipital-groove.png',
    author: 'Doctor Jana',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bicipital-groove.jpg',
  },
  'Spine of Scapula': {
    src: '/anatomy/a-spine-of-scapula02.png',
    author: 'BodyParts3D, made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Spine_of_scapula02.png',
  },
  Clavicle: {
    src: '/anatomy/a-clavicle-anterior.png',
    author: 'Anatomography (BodyParts3D / DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Clavicle_-_anterior_view.png',
  },
  'Transverse Abdominis': {
    src: '/anatomy/b-transversus-abdominis.png',
    author: 'Henry Gray, Anatomy of the Human Body (plate Gray397), colourised by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Transversus_abdominis.png',
  },
  'Quadratus Lumborum': {
    src: '/anatomy/b-quadratus-lumborum.png',
    author: 'Henry Gray, Anatomy of the Human Body (plate Gray389), colourised by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Quadratuslumborum.png',
  },
  Longissimus: {
    src: '/anatomy/b-longissimus.png',
    author: 'Henry Gray, Anatomy of the Human Body (plate Gray389), colourised by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Longissimus.png',
  },
  'Psoas Major': {
    src: '/anatomy/r2-psoas-major.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Psoas_major.gif',
  },
  Iliacus: {
    src: '/anatomy/b-iliacus.png',
    author: 'BodyParts3D/Anatomography (frame taken from the rotating 3D render)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Iliacus.gif',
  },
  'Gluteus Minimus': {
    src: '/anatomy/b-gluteus-minimus.png',
    author: 'BodyParts3D/Anatomography (frame taken from the rotating 3D render)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Gluteus_minimus.gif',
  },
  'Adductor Brevis': {
    src: '/anatomy/b-adductor-brevis.png',
    author: 'BodyParts3D/Anatomography (frame taken from the rotating 3D render)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Adductor_brevis.gif',
  },
  'Adductor Longus': {
    src: '/anatomy/b-adductor-longus.png',
    author: 'BodyParts3D/Anatomography (frame taken from the rotating 3D render)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Adductor_longus.gif',
  },
  'Tensor Fasciae Latae': {
    src: '/anatomy/b-tensor-fasciae-latae.png',
    author: 'Henry Gray, Anatomy of the Human Body (plate Gray549), colourised by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Tensor_fasciae_latae.png',
  },
  Sartorius: {
    src: '/anatomy/b-sartorius.png',
    author: 'Based on \'Illu lower extremity muscles\' (US federal government, public domain), modified by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Sartorius.png',
  },
  Gastrocnemius: {
    src: '/anatomy/c-gastrocnemius-posterior.png',
    author: 'Polygon data generated by Database Center for Life Science (DBCLS) / BodyParts3D, via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Gastrocnemius_muscle_-_posterior_view.png',
  },
  Soleus: {
    src: '/anatomy/c-soleus-posterior.png',
    author: 'Polygon data generated by Database Center for Life Science (DBCLS) / BodyParts3D, via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Soleus_muscle_-_posterior_view.png',
  },
  'Peroneus Longus': {
    src: '/anatomy/c-peroneus-longus-superior.png',
    author: 'Polygon data generated by Database Center for Life Science (DBCLS) / BodyParts3D, via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Superior_view_fibularis_longus_muscle_-_posterior.png',
  },
  'Flexor Hallucis Longus': {
    src: '/anatomy/c-fhl-superior.png',
    author: 'Polygon data generated by Database Center for Life Science (DBCLS) / BodyParts3D, via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Superior_view_of_flexor_hallucis_longus_muscle_-_posterior.png',
  },
  'Vastus Medialis': {
    src: '/anatomy/r1-vastus-medialis.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Vastus_medialis.gif',
  },
  'Rectus Femoris': {
    src: '/anatomy/r1-rectus-femoris.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Rectus_femoris_3D.gif',
  },
  'Iliotibial Band': {
    src: '/anatomy/c-itb-gray430-en.png',
    author: 'Jmarchn, after Henry Vandyke Carter (Gray\'s Anatomy plate 430)',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gray430-en.svg',
  },
  'MTP 1 Joint': {
    src: '/anatomy/articulationes-metatarsophalangeae.png',
    author: 'Jmarchn, after File:Ospied.svg',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Articulationes_metatarsophalangeae-la.svg',
    note: 'The orange band marks the metatarsophalangeal joint line, where the metatarsals (yellow) meet the proximal phalanges (green). MTP 1 is the joint of the big toe, at digit I on the left. Labels are in Latin: metatarsi = metatarsals, phalanges proximales = proximal phalanges.',
  },
  'Medial Meniscus': {
    src: '/anatomy/c-medial-meniscus-gray349.png',
    author: 'Henry Vandyke Carter (Gray\'s Anatomy plate 349)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray349.png',
  },
  'Knee Joint': {
    src: '/anatomy/c-knee-joint-917.png',
    author: 'OpenStax College (Anatomy & Physiology)',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:917_Knee_Joint.jpg',
  },
  Ilium: {
    src: '/anatomy/c-ilium-lateral.png',
    author: 'BodyParts3D, made by Database Center for Life Science (DBCLS), via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Ilium_02_lateral_view.png',
  },
  'Glenohumeral Joint': {
    src: '/anatomy/d-glenohumeral-joint.png',
    author: 'OpenStax College',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:914_Shoulder_Joint.jpg',
  },
  'Talocrural Joint': {
    src: '/anatomy/r5-talocrural-joint.png',
    author: 'BodyParts3D / DBCLS (Anatomography)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Left_Talus_bone_03_lateral_view.png',
    note: 'Lateral view of the left ankle. The talus is red; the tibia and fibula come down onto it from above, and the joint is the mortise between them. Note this is the joint ABOVE the talus - the subtalar joint lies below it, between talus and calcaneus.',
  },
  'CMC 1 Joint': {
    src: '/anatomy/r5-cmc-1-joint.png',
    author: 'BodyParts3D / DBCLS, rendered by was_a_bee — composite of two same-camera renders, modified',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:First_metacarpal_bone_%28left_hand%29_01_palmar_view.png',
    note: 'Red marks the two bones that form the joint: the first metacarpal (above) and the trapezium (below). The saddle joint itself is the gap where they meet at the base of the thumb. Composed from two BodyParts3D renders sharing one camera — the linked first-metacarpal view, with the trapezium from File:Trapezium bone (left)01 palmar view.png.',
  },
  ACL: {
    src: '/anatomy/d-acl.png',
    author: 'Mysid',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Knee_diagram.svg',
  },
  ATFL: {
    src: '/anatomy/d-atfl.png',
    author: 'Jak (SVG version of File:Ankle.PNG)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Ankle_en.svg',
  },
  'Deltoid Ligament': {
    src: '/anatomy/d-deltoid-ligament.png',
    author: 'Henry Vandyke Carter (Gray\'s Anatomy, plate 354)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray354.png',
  },
  'Coracohumeral Ligament': {
    src: '/anatomy/d-coracohumeral-ligament.png',
    author: 'Henry Vandyke Carter (Gray\'s Anatomy, plate 326)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray326.png',
  },
  'Iliofemoral Ligament': {
    src: '/anatomy/d-iliofemoral-ligament.png',
    author: 'Henry Vandyke Carter (Gray\'s Anatomy, plate 339)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray339.png',
  },
  'Trochanteric Bursa': {
    src: '/anatomy/d-trochanteric-bursa.png',
    author: 'Hariadhi',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Greater_trochanteric_pain_syndrome_by_Hariadhi.svg',
    note: 'The bursa is the structure named on its own leader line. The red shading is labelled \'Area of pain\' — it marks where trochanteric pain is felt, not the bursa itself.',
  },
  'Prepatellar Bursa': {
    src: '/anatomy/d-prepatellar-bursa.png',
    author: 'Mikael Haggstrom',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Prepatellar_bursa_(vector).svg',
  },
  'Suprapatellar Bursa': {
    src: '/anatomy/d-suprapatellar-bursa.png',
    author: 'Addingrefs',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Knee-unfolding-recess-diagram.svg',
    note: 'This image is unlabelled: the bursa is the structure picked out in red, shown unfolding as the knee flexes across the three views.',
  },
  'Subacromial Bursa': {
    src: '/anatomy/d-subacromial-bursa.png',
    author: 'OpenStax College',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:914_Shoulder_Joint.jpg',
    note: 'Same shoulder figure as the Glenohumeral Joint page; here the subacromial bursa is the labelled structure of interest.',
  },
}
