// Generated from Wikipedia / Wikimedia Commons. Each entry records author,
// license, and source page so the CC BY-SA attribution requirement is met.
// Files are downloaded into frontend/public/anatomy so the pages don't depend
// on any external host staying up.

export interface AnatomyImage {
  src: string
  author: string
  license: string
  source: string
  /** Optional hint for images where several structures are visible at once. */
  note?: string
}

export const anatomyImages: Record<string, AnatomyImage> = {
  'Abductor Pollicis Brevis': {
    src: '/anatomy/musculus-abductor-pollicis-brevis-red.png',
    author: 'Arent',
    license: 'CC0',
    source: 'https://commons.wikimedia.org/wiki/File:Musculus_abductor_pollicis_brevis_-_red.png',
  },
  'Abductor Pollicis Longus': {
    src: '/anatomy/abductor-pollicis-longus.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_abductor_pollicis_longus.png',
    note: 'The abductor pollicis longus is shown in red on a posterior view of the right forearm.',
  },
  Acetabulum: {
    src: '/anatomy/acetabulum-model.png',
    author: 'Protohiro at English Wikipedia',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Acetabulum_(model).jpg',
  },
  ACL: {
    src: '/anatomy/d-acl.png',
    author: 'Mysid',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Knee_diagram.svg',
  },
  'Acromioclavicular Joint': {
    src: '/anatomy/gray326.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray326.png',
  },
  Acromion: {
    src: '/anatomy/a-acromion-left-scapula01.png',
    author: 'BodyParts3D, made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Acromion_of_left_scapula01.png',
  },
  'Adductor Brevis': {
    src: '/anatomy/b-adductor-brevis.png',
    author: 'BodyParts3D/Anatomography (frame taken from the rotating 3D render)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Adductor_brevis.gif',
  },
  'Adductor Longus': {
    src: '/anatomy/b-adductor-longus.png',
    author: 'BodyParts3D/Anatomography (frame taken from the rotating 3D render)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Adductor_longus.gif',
  },
  'Adductor Magnus': {
    src: '/anatomy/adductor-magnus.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AAdductor_magnus.gif',
    note: '(frame taken from the rotating 3D render)',
  },
  'Ankle Joint': {
    src: '/anatomy/ankle-en.png',
    author: 'An svg version of image:Ankle.PNG by me (Jak)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Ankle_en.svg',
  },
  'Annular Ligament': {
    src: '/anatomy/en-elbow-joint.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:En-elbow_joint.svg',
  },
  'Anterior Deltoid': {
    src: '/anatomy/deltoideus.png',
    author: 'Original: sv:Användare:Chrizz',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Deltoideus.png',
  },
  'Arcuate Line': {
    src: '/anatomy/arcuate-line.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray398.png',
    note: "Posterior surface of the anterior abdominal wall; the arcuate line is the free lower border of the posterior rectus sheath, labelled here by its older name 'Linea semicircularis'.",
  },
  ASIS: {
    src: '/anatomy/asis.png',
    author: 'BodyParts3D is made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AASIS_04_anterior_view.png',
    note: 'The anterior superior iliac spine is the red marker at the front tip of each iliac crest.',
  },
  ATFL: {
    src: '/anatomy/d-atfl.png',
    author: 'Jak (SVG version of File:Ankle.PNG)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Ankle_en.svg',
  },
  'Atlanto-Occipital Joint': {
    src: '/anatomy/gray304.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray304.png',
  },
  'Biceps Brachii': {
    src: '/anatomy/biceps-brachii-muscle01.png',
    author: 'Anatomography (background whitened)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Biceps_brachii_muscle01.png',
    note: 'Biceps brachii is the muscle in red. Both heads run up to the scapula — the long head over the shoulder joint, the short head to the coracoid process — and the distal tendon attaches below the elbow.',
  },
  'Biceps Femoris': {
    src: '/anatomy/biceps-femoris.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ABiceps_femoris.gif',
    note: '(frame taken from the rotating 3D render)',
  },
  'Bicipital Groove': {
    src: '/anatomy/a-bicipital-groove.png',
    author: 'Doctor Jana',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bicipital-groove.jpg',
  },
  Brachialis: {
    src: '/anatomy/brachialis-muscle01.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Brachialis_muscle01.png',
    note: 'Brachialis is the muscle highlighted in red, deep to the biceps on the front of the upper arm.',
  },
  Brachioradialis: {
    src: '/anatomy/brachioradialis.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Brachioradialis.png',
  },
  'C1-C2 Joint': {
    src: '/anatomy/gray306.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray306.png',
    note: 'The atlas (C1) seen from above. The odontoid process — the peg projecting up from the axis (C2) — is held against the anterior arch by the transverse ligament. C1 and the skull rotate around that peg, which is what makes this a pivot joint.',
  },
  Calcaneus: {
    src: '/anatomy/calcaneus.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ACalcaneus03_lateral_view.png',
    note: 'Both feet from the lateral side. The calcaneus is the red heel bone.',
  },
  CFL: {
    src: '/anatomy/cfl.png',
    author: 'Laboratoires Servier',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File%3ALateral_collateral_ligament_of_ankle_joint.png',
    note: 'Lateral view of the right ankle. The calcaneofibular ligament (CFL) is the band labelled at the bottom, running from the tip of the fibula down and back to the lateral calcaneus.',
  },
  Clavicle: {
    src: '/anatomy/a-clavicle-anterior.png',
    author: 'Anatomography (BodyParts3D / DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Clavicle_-_anterior_view.png',
  },
  'CMC 1 Joint': {
    src: '/anatomy/r5-cmc-1-joint.png',
    author: 'BodyParts3D / DBCLS, rendered by was_a_bee — composite of two same-camera renders, modified',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:First_metacarpal_bone_%28left_hand%29_01_palmar_view.png',
    note: 'Red marks the two bones that form the joint: the first metacarpal (above) and the trapezium (below). The saddle joint itself is the gap where they meet at the base of the thumb. Composed from two BodyParts3D renders sharing one camera — the linked first-metacarpal view, with the trapezium from File:Trapezium bone (left)01 palmar view.png.',
  },
  'Coracoacromial Ligament': {
    src: '/anatomy/coracoacromial-ligament.png',
    author: 'Dr. Johannes Sobotta',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3ASobo_1909_196.png',
    note: 'The shoulder with the humerus removed, looking into the glenoid cavity. The coraco-acromial ligament is the band labelled at left, running from the coracoid process back to the acromion and roofing the joint.',
  },
  Coracobrachialis: {
    src: '/anatomy/coracobrachialis-muscle05.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Coracobrachialis_muscle05.png',
  },
  'Coracoclavicular Ligament': {
    src: '/anatomy/coracoclavicular-ligament.png',
    author: 'Dr. Johannes Sobotta',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3ASobo_1909_193.png',
    note: 'The shoulder from the front. The coracoclavicular ligament is labelled in its two parts - the conoid portion and the trapezoid portion - slung from the coracoid process up to the clavicle.',
  },
  'Coracohumeral Ligament': {
    src: '/anatomy/d-coracohumeral-ligament.png',
    author: "Henry Vandyke Carter (Gray's Anatomy, plate 326)",
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray326.png',
  },
  'Coracoid Process': {
    src: '/anatomy/coracoid-process-of-left-scapula02.png',
    author: 'BodyParts3D is made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Coracoid_process_of_left_scapula02.png',
  },
  Cuboid: {
    src: '/anatomy/cuboid.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ACuboid_bone_03.png',
    note: 'Both feet from the lateral side. The cuboid is the green bone on the near foot, on the outer border between the calcaneus and the fourth and fifth metatarsals.',
  },
  Deltoid: {
    src: '/anatomy/deltoideus.png',
    author: 'Original: sv:Användare:Chrizz',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Deltoideus.png',
  },
  'Deltoid Ligament': {
    src: '/anatomy/d-deltoid-ligament.png',
    author: "Henry Vandyke Carter (Gray's Anatomy, plate 354)",
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray354.png',
  },
  'DIP Joint': {
    src: '/anatomy/hand-bones-scheme.png',
    author: 'Mariana Ruiz Villarreal (LadyofHats); retouches by Nyks',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AScheme_human_hand_bones-en.svg',
    note: 'Skeletal hand, bones colour-coded. The DIP joints are the articulations between the orange distal phalanges and the blue intermediate phalanges — the thumb has no DIP joint of this kind, having only two phalanges.',
  },
  'Elbow Joint': {
    src: '/anatomy/elbow-joint.png',
    author: 'DataBase Center for Life Science (DBCLS)',
    license: 'CC BY 4.0',
    source: 'https://commons.wikimedia.org/wiki/File%3A202107_Anterior_view_of_the_elbow_joint.svg',
    note: 'The elbow joint seen from the front. The humerus is above; the radius and ulna below, with the articular cartilage of the humeroulnar and humeroradial articulations shown in white.',
  },
  'Erector Spinae': {
    src: '/anatomy/erector-spinae.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray389_-_Erector_spinae.png',
  },
  'Extensor Carpi Radialis Brevis': {
    src: '/anatomy/extensor-carpi-radialis-brevis.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_extensor_carpi_radialis_brevis.png',
    note: 'The extensor carpi radialis brevis is shown in red on a posterior view of the right forearm.',
  },
  'Extensor Carpi Radialis Longus': {
    src: '/anatomy/extensor-carpi-radialis-longus.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_extensor_carpi_radialis_longus.png',
    note: 'The extensor carpi radialis longus is shown in red on a posterior view of the right forearm.',
  },
  'Extensor Carpi Ulnaris': {
    src: '/anatomy/extensor-carpi-ulnaris.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_extensor_carpi_ulnaris.png',
    note: 'The extensor carpi ulnaris is shown in red on a posterior view of the right forearm.',
  },
  'Extensor Digiti Minimi': {
    src: '/anatomy/extensor-digiti-minimi.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_extensor_digiti_minimi.png',
    note: 'The extensor digiti minimi is shown in red on a posterior view of the right forearm.',
  },
  'Extensor Digitorum': {
    src: '/anatomy/extensor-digitorum-muscle.png',
    author: 'Mikael Häggström. When using this image in external works, it may be c',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Extensor_digitorum_muscle.png',
  },
  'Extensor Digitorum Longus': {
    src: '/anatomy/extensor-digitorum-longus.png',
    author: 'Polygon data were generated by Database Center for Life Science (DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AExtensor_digitorum_longus_muscle_-_anteriror_view.png',
  },
  'Extensor Hallucis Longus': {
    src: '/anatomy/extensor-hallucis-longus.png',
    author: 'Was a bee',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AExtensor_hallucis_longus_muscle_-_anteriror_view_2.png',
  },
  'Extensor Indicis': {
    src: '/anatomy/gray421.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray421.png',
  },
  'Extensor Pollicis Brevis': {
    src: '/anatomy/extensor-pollicis-brevis.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_extensor_pollicis_brevis.png',
    note: 'The extensor pollicis brevis is shown in red on a posterior view of the right forearm.',
  },
  'Extensor Pollicis Longus': {
    src: '/anatomy/extensor-pollicis-longus.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_extensor_pollicis_longus.png',
    note: 'The extensor pollicis longus is shown in red on a posterior view of the right forearm.',
  },
  'External Oblique': {
    src: '/anatomy/external-oblique-highlighted.png',
    author: 'Henry Vandyke Carter (recoloured: external oblique in red, rest of the plate greyed)',
    license: 'CC0',
    source: 'https://commons.wikimedia.org/wiki/File:Grays_Anatomy_Muscle_oblique_externe.png',
    note: 'The external oblique is the muscle highlighted in red, with OBLIQUUS EXTERNUS labelled across it. It is the outermost of the three flat abdominal wall muscles.',
  },
  Femur: {
    src: '/anatomy/femur-anterior-view2.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Femur_-_anterior_view2.png',
  },
  Fibula: {
    src: '/anatomy/fibula.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AFibula_-_anterior_view.png',
    note: 'Lower limbs from the front. The fibula is the red slender bone lateral to the tibia in each leg.',
  },
  'Flexor Carpi Radialis': {
    src: '/anatomy/flexor-carpi-radialis.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_flexor_carpi_radialis.png',
  },
  'Flexor Carpi Ulnaris': {
    src: '/anatomy/gray-musculus-flexor-carpi-ulnaris.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray_%E2%80%94_musculus_flexor_carpi_ulnaris.png',
  },
  'Flexor Digitorum Longus': {
    src: '/anatomy/inferior-view-of-flexor-digitorum-longus-muscle-posterior.png',
    author: 'Polygon data were generated by Database Center for Life Science (DBCLS) (background removed)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Inferior_view_of_flexor_digitorum_longus_muscle_-_posterior.png',
    note: 'Posterior view. The muscle belly is red on the back of the tibia, and its four tendons are visible splaying out to the lateral four toes.',
  },
  'Flexor Digitorum Profundus': {
    src: '/anatomy/flexor-digitorum-profundus.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_flexor_digitorum_profundus.png',
  },
  'Flexor Digitorum Superficialis': {
    src: '/anatomy/flexor-digitorum-superficialis.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray_%E2%80%94_musculus_flexor_digitorum_superficialis.png',
  },
  'Flexor Hallucis Longus': {
    src: '/anatomy/c-fhl-superior.png',
    author: 'Polygon data generated by Database Center for Life Science (DBCLS) / BodyParts3D, via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Superior_view_of_flexor_hallucis_longus_muscle_-_posterior.png',
  },
  'Flexor Pollicis Longus': {
    src: '/anatomy/musculus-flexor-pollicis-longus.png',
    author: "Gray's Anatomy plate, highlighted by a Wikimedia contributor",
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Musculus_flexor_pollicis_longus.png',
  },
  Gastrocnemius: {
    src: '/anatomy/c-gastrocnemius-posterior.png',
    author: 'Polygon data generated by Database Center for Life Science (DBCLS) / BodyParts3D, via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Gastrocnemius_muscle_-_posterior_view.png',
  },
  'Gemellus Superior': {
    src: '/anatomy/gemellus-superior.png',
    author: 'Mikael Häggström. When using this image in external works, it may be cited as: Häggström, Mikael (2014). "Medical gallery of Mikael Häggström 2014". WikiJournal of Medicine 1 (2). DOI:10.15347/wjm/2014.008. ISSN 2002-4436. Public Domain. or By Mikael Häggström, used with permission.',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGemellus_superior_muscle.PNG',
    note: 'Posterior view of the right hip and thigh. The gemellus superior is the small muscle highlighted in red, lying between piriformis above and obturator internus below.',
  },
  'Glenohumeral Joint': {
    src: '/anatomy/d-glenohumeral-joint.png',
    author: 'OpenStax College',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:914_Shoulder_Joint.jpg',
  },
  'Glenoid Fossa': {
    src: '/anatomy/a-glenoid-cavity01.png',
    author: 'BodyParts3D / DBCLS (polygon data)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Glenoid_cavity_of_scapula01.png',
  },
  'Gluteus Maximus': {
    src: '/anatomy/gluteus-maximus-3d.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Gluteus_maximus_3D.gif',
  },
  'Gluteus Medius': {
    src: '/anatomy/posterior-hip-muscles-3.png',
    author: 'Unknown',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Posterior_Hip_Muscles_3.PNG',
  },
  'Gluteus Minimus': {
    src: '/anatomy/b-gluteus-minimus.png',
    author: 'BodyParts3D/Anatomography (frame taken from the rotating 3D render)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Gluteus_minimus.gif',
  },
  Gracilis: {
    src: '/anatomy/gracilis.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AGracilis.gif',
    note: '(frame taken from the rotating 3D render)',
  },
  'Greater Trochanter': {
    src: '/anatomy/gray243.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray243.png',
  },
  Hamate: {
    src: '/anatomy/hamate.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AHamate_bone_%28left_hand%29_01_palmar_view.png',
    note: 'Left hand, palmar view. The hamate is the carpal bone shown in red, on the little-finger side of the distal carpal row.',
  },
  Hamstrings: {
    src: '/anatomy/hamstrings.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Hamstrings.gif',
  },
  'Head of Fibula': {
    src: '/anatomy/head-of-fibula.png',
    author: 'Andrew Francis Dixon (1868-1936)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3ADixon%27s_Manual_of_human_osteology_%281912%29_-_Fig_077.png',
    note: 'The whole right fibula, lateral view. The head is the expanded upper end labelled Capitulum fibulae, just above the neck of fibula; the pointed tip above it is the styloid process (apex).',
  },
  'Hip Joint': {
    src: '/anatomy/blausen-0488-hipanatomy.png',
    author: 'BruceBlaus',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Blausen_0488_HipAnatomy.png',
  },
  Humerus: {
    src: '/anatomy/a-humerus-anterior.png',
    author: 'Anatomography (BodyParts3D / DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Humerus_-_anterior_view.png',
  },
  'Iliac Crest': {
    src: '/anatomy/iliac-crest.png',
    author: 'BodyParts3D is made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AIliac_crest_04_-_anterior_view.png',
    note: 'Anterior view of the pelvis; the iliac crest is the red upper border of each ilium.',
  },
  Iliacus: {
    src: '/anatomy/b-iliacus.png',
    author: 'BodyParts3D/Anatomography (frame taken from the rotating 3D render)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Iliacus.gif',
  },
  Iliocostalis: {
    src: '/anatomy/iliocostalis.png',
    author: 'modified by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AIliostalis.png',
  },
  'Iliofemoral Ligament': {
    src: '/anatomy/d-iliofemoral-ligament.png',
    author: "Henry Vandyke Carter (Gray's Anatomy, plate 339)",
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray339.png',
  },
  Iliopsoas: {
    src: '/anatomy/anterior-hip-muscles-2.png',
    author: 'Beth ohara',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Anterior_Hip_Muscles_2.PNG',
    note: 'Iliopsoas is not one muscle but two acting together: psoas major and iliacus, both labelled at the top of this anterior view of the hip.',
  },
  'Iliotibial Band': {
    src: '/anatomy/c-itb-gray430-en.png',
    author: "Jmarchn, after Henry Vandyke Carter (Gray's Anatomy plate 430)",
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gray430-en.svg',
  },
  Ilium: {
    src: '/anatomy/c-ilium-lateral.png',
    author: 'BodyParts3D, made by Database Center for Life Science (DBCLS), via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Ilium_02_lateral_view.png',
  },
  Infraspinatus: {
    src: '/anatomy/a-infraspinatus-back2.png',
    author: 'Anatomography (BodyParts3D / DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Infraspinatus_muscle_back2.png',
  },
  'Intercarpal Joint': {
    src: '/anatomy/intercarpal-joint.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray336.png',
    note: 'Vertical section through the wrist. The intercarpal joints are the narrow cavities between the carpal bones themselves (navicular, lunate, triquetrum, capitate, hamate and the multangulars), separate from the wrist joint labelled above them.',
  },
  'Internal Oblique': {
    src: '/anatomy/gray395.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray395.png',
    note: 'OBLIQUUS INTERNUS is labelled across the muscle belly. This layer sits directly beneath the external oblique, exposed here with the external oblique removed.',
  },
  'Interosseous Membrane': {
    src: '/anatomy/interosseous-membrane.png',
    author: 'Wikipedia; and me',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3A5_ligaments_of_interosseous_membrane_of_forearm.png',
    note: 'Radius (left) and ulna (right), seen from behind. The coloured bars are the fibre bundles of the interosseous membrane running between the two bones; the central band is the main part.',
  },
  'Ischial Tuberosity': {
    src: '/anatomy/ischial-tuberosity.png',
    author: 'BodyParts3D is made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AIschial_tuberosity_02-2_posterior_view.png',
    note: 'Posterior view of the pelvis; the ischial tuberosities are the red areas at the bottom of each ischium.',
  },
  'Ischiofemoral Ligament': {
    src: '/anatomy/ischiofemoral-ligament.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray340.png',
    note: 'Posterior view of the right hip joint capsule; the ischiofemoral ligament is the fan of fibres running from the ischium up across the back of the joint.',
  },
  'Knee Joint': {
    src: '/anatomy/c-knee-joint-917.png',
    author: 'OpenStax College (Anatomy & Physiology)',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:917_Knee_Joint.jpg',
  },
  'Lateral Epicondyle': {
    src: '/anatomy/lateral-epicondyle.jpg',
    author: 'Doctor Jana',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File%3AMedial-epicondyle-and-lateral-epicondyle.jpg',
    note: 'Distal end of the humerus. The lateral epicondyle is the tinted prominence labelled on the left; the medial epicondyle is labelled opposite it for contrast.',
  },
  'Lateral Meniscus': {
    src: '/anatomy/lateral-meniscus.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray348-2.png',
    note: 'Left knee from behind. The lateral meniscus is labelled on the left of the plate, on the outer (fibular) side of the joint; the medial meniscus is labelled opposite it.',
  },
  'Latissimus Dorsi': {
    src: '/anatomy/latissimus-dorsi-muscle-back.png',
    author: 'Anatomography (background whitened)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Latissimus_dorsi_muscle_back.png',
  },
  LCL: {
    src: '/anatomy/gray348.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray348.png',
  },
  'Lesser Tubercle': {
    src: '/anatomy/lesser-tubercle.jpg',
    author: 'Doctor Jana',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File%3ALesser-Tubercle-of-Right-Humerus.jpg',
    note: 'Upper end of the right humerus. The lesser tubercle is the smaller prominence on the front of the bone, just medial to the intertubercular groove; the greater tubercle lies lateral to it.',
  },
  'Levator Scapulae': {
    src: '/anatomy/a-levator-scapulae-lateral.png',
    author: 'Anatomography (BodyParts3D / DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Levator_scapulae_muscle_lateral.png',
  },
  'Linea Alba': {
    src: '/anatomy/linea-alba.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray399.svg',
    note: 'Transverse section of the anterior abdominal wall; the linea alba is the midline fibrous seam between the two rectus muscles, labelled at centre.',
  },
  'Long Plantar Ligament': {
    src: '/anatomy/long-plantar-ligament.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray358.png',
    note: 'Ligaments of the sole of the right foot. The long plantar ligament is labelled on the left, the long superficial band running forward from the calcaneus to the metatarsal bases.',
  },
  Longissimus: {
    src: '/anatomy/b-longissimus.png',
    author: 'Henry Gray, Anatomy of the Human Body (plate Gray389), colourised by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Longissimus.png',
  },
  Lunate: {
    src: '/anatomy/lunate-bone-left-hand-01-palmar-view.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Lunate_bone_(left_hand)_01_palmar_view.png',
  },
  'Mastoid Process': {
    src: '/anatomy/mastoid-process.png',
    author: 'Polygon data were generated by Database Center for Life Science(DBCLS)[2].',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AMastoid_process_-_lateral_view.png',
    note: 'Left lateral view of the skull; the mastoid process is the red bony prominence just behind and below the ear canal, on the underside of the temporal bone.',
  },
  MCL: {
    src: '/anatomy/knee-medial-view.png',
    author: 'National Institute of Arthritis and Musculoskeletal and Skin Diseases (NIAMS)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Knee_medial_view.gif',
  },
  'Medial Epicondyle': {
    src: '/anatomy/medial-epicondyle.png',
    author: 'Jmarchn',
    license: 'CC BY 4.0',
    source: 'https://commons.wikimedia.org/wiki/File%3AMedial_epicondyle_of_the_humerus.svg',
    note: 'The medial epicondyle is the red projection on the inner side of the lower humerus, at the elbow.',
  },
  'Medial Meniscus': {
    src: '/anatomy/c-medial-meniscus-gray349.png',
    author: "Henry Vandyke Carter (Gray's Anatomy plate 349)",
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray349.png',
  },
  'Metacarpal 2': {
    src: '/anatomy/second-metacarpal-bone-left-hand-01-palmar-view.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Second_metacarpal_bone_(left_hand)_01_palmar_view.png',
  },
  'Metatarsal Bones': {
    src: '/anatomy/metatarsal-bones.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ALeft_Metatarsal_bones01_anterior_view.png',
    note: 'Left foot skeleton. The five metatarsals are the green shafts between the tarsus and the toes.',
  },
  'MP Joint': {
    src: '/anatomy/mp-joint.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray338.png',
    note: 'Ulnar aspect of one digit. The MP (metacarpophalangeal) joint is the upper one, between the metacarpal bone and the 1st phalanx; the two joints below it are the PIP and DIP.',
  },
  'MTP 1 Joint': {
    src: '/anatomy/articulationes-metatarsophalangeae.png',
    author: 'Jmarchn, after File:Ospied.svg',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Articulationes_metatarsophalangeae-la.svg',
    note: 'The orange band marks the metatarsophalangeal joint line, where the metatarsals (yellow) meet the proximal phalanges (green). MTP 1 is the joint of the big toe, at digit I on the left. Labels are in Latin: metatarsi = metatarsals, phalanges proximales = proximal phalanges.',
  },
  Multifidus: {
    src: '/anatomy/multifidus.png',
    author: 'Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AMultifidi.png',
    note: 'Posterior view of the thoracolumbar spine, deep dissection. The multifidus is the red column lying directly against the vertebrae, medial to the longissimus and spinalis.',
  },
  Navicular: {
    src: '/anatomy/navicular.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ANavicular_bone03.png',
    note: 'Left foot from above. The navicular is the green boat-shaped bone between the head of the talus and the three cuneiforms.',
  },
  'Obturator Internus': {
    src: '/anatomy/posterior-hip-muscles-1.png',
    author: 'Beth ohara',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Posterior_Hip_Muscles_1.PNG',
  },
  'Palmar Aponeurosis': {
    src: '/anatomy/palmar-aponeurosis.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray425.png',
  },
  'Palmaris Longus': {
    src: '/anatomy/a-palmaris-longus-gray.png',
    author: "Henry Vandyke Carter (Gray's Anatomy)",
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray_%E2%80%94_musculus_palmaris_longus.png',
  },
  Patella: {
    src: '/anatomy/anterioraspectofrightpatella.png',
    author: 'John Doe',
    license: 'CC0',
    source: 'https://commons.wikimedia.org/wiki/File:AnteriorAspectOfRightPatella.png',
  },
  'Patellofemoral Joint': {
    src: '/anatomy/knee-diagram.png',
    author: 'Mysid',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Knee_diagram.svg',
  },
  PCL: {
    src: '/anatomy/knee-medial-view.png',
    author: 'National Institute of Arthritis and Musculoskeletal and Skin Diseases (NIAMS)',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Knee_medial_view.gif',
  },
  Pectineus: {
    src: '/anatomy/pectineus.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3APectineus_3D.gif',
    note: '(frame taken from the rotating 3D render)',
  },
  'Pectoralis Major': {
    src: '/anatomy/gray410.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray410.png',
  },
  'Pectoralis Minor': {
    src: '/anatomy/pectoralis-minor.png',
    author: 'Original: ‍Användare:Chrizz Vector: Pixelsquid🎱',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Pectoralis_minor.svg',
  },
  'Peroneus Brevis': {
    src: '/anatomy/peroneus-brevis.png',
    author: 'Polygon data were generated by Database Center for Life Science (DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AFibularis_brevis_muscle_-_posterior_view.png',
    note: 'The peroneus (fibularis) brevis is highlighted in red on the lateral fibula; its tendon passes behind the lateral malleolus to the base of the fifth metatarsal.',
  },
  'Peroneus Longus': {
    src: '/anatomy/c-peroneus-longus-superior.png',
    author: 'Polygon data generated by Database Center for Life Science (DBCLS) / BodyParts3D, via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Superior_view_fibularis_longus_muscle_-_posterior.png',
  },
  'Phalang 1': {
    src: '/anatomy/scheme-human-hand-bones-en.png',
    author: 'Mariana Ruiz Villarreal (LadyofHats); retouches by Nyks',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Scheme_human_hand_bones-en.svg',
  },
  Phalanges: {
    src: '/anatomy/phalanges.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3APhalanges_of_the_hand_%28left_hand%29_01_palmar_view.png',
    note: 'Left hand, palmar view. All fourteen phalanges of the hand are red; the metacarpals and carpals are left grey.',
  },
  'PIP Joint': {
    src: '/anatomy/hand-bones-scheme.png',
    author: 'Mariana Ruiz Villarreal (LadyofHats); retouches by Nyks',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AScheme_human_hand_bones-en.svg',
    note: 'Skeletal hand, bones colour-coded. The PIP joints are the articulations between the blue intermediate phalanges and the green proximal phalanges, in digits 2-5.',
  },
  Piriformis: {
    src: '/anatomy/piriformis.png',
    author: 'Johannes Sobotta',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Piriformis.jpg',
  },
  Pisiform: {
    src: '/anatomy/pisiform.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3APisiform_bone_%28left_hand%29_01_palmar_view.png',
    note: 'Left hand, palmar view. The pisiform is the small pea-shaped bone in red, sitting on the front of the triquetrum on the little-finger side of the wrist.',
  },
  Plantaris: {
    src: '/anatomy/plantaris.png',
    author: 'Polygon data is generated by Database Center for Life Science (DBCLS)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3APlantaris_muscle_-_posterior_view.png',
    note: 'Posterior view. The red structure is plantaris: a small belly behind the knee continuing as a very long thin tendon down to the heel.',
  },
  Popliteus: {
    src: '/anatomy/popliteus.png',
    author: 'Polygon data were generated by Database Center for Life Science (DBCLS)[2]',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3APopliteus_muscle_-_posterior_view.png',
  },
  'Posterior Deltoid': {
    src: '/anatomy/deltoideus.png',
    author: 'Original: sv:Användare:Chrizz',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Deltoideus.png',
  },
  'Prepatellar Bursa': {
    src: '/anatomy/d-prepatellar-bursa.png',
    author: 'Mikael Haggstrom',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Prepatellar_bursa_(vector).svg',
  },
  'Pronator Teres': {
    src: '/anatomy/gray-musculus-pronator-teres.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray_%E2%80%94_musculus_pronator_teres.png',
  },
  'Proximal Radioulnar Joint': {
    src: '/anatomy/gray333.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray333.png',
  },
  'Proximal Tibiofibular Joint': {
    src: '/anatomy/gray351.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray351.png',
  },
  'Psoas Major': {
    src: '/anatomy/r2-psoas-major.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Psoas_major.gif',
  },
  PTFL: {
    src: '/anatomy/ptfl.png',
    author: 'Laboratoires Servier',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File%3ALateral_collateral_ligament_of_ankle_joint.png',
    note: 'Lateral view of the right ankle. The posterior talofibular ligament (PTFL) is the band labelled at the top, running horizontally from the fibula back to the talus.',
  },
  Pubis: {
    src: '/anatomy/pubis.png',
    author: 'BodyParts3D is made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3APubis_03_anterior_view.png',
    note: 'Anterior view of the pelvis; the pubis is shown in red on both sides.',
  },
  'Pubofemoral Ligament': {
    src: '/anatomy/pubofemoral-ligament.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray339.png',
    note: 'Anterior view of the left hip joint capsule. The pubofemoral ligament is labelled by its older name, pubocapsular ligament, on the lower right, running from the superior pubic ramus into the capsule below the iliofemoral ligament.',
  },
  'Quadratus Femoris': {
    src: '/anatomy/quadratus-femoris.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AQuadratus_femoris_large.gif',
    note: '(frame taken from the rotating 3D render)',
  },
  'Quadratus Lumborum': {
    src: '/anatomy/b-quadratus-lumborum.png',
    author: 'Henry Gray, Anatomy of the Human Body (plate Gray389), colourised by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Quadratuslumborum.png',
  },
  Quadriceps: {
    src: '/anatomy/quadriceps-3d.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Quadriceps_3D.gif',
  },
  'Radiocarpal Joint': {
    src: '/anatomy/gray335.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray335.png',
  },
  'Radioulnar Joint': {
    src: '/anatomy/gray334.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray334.png',
  },
  Radius: {
    src: '/anatomy/radius-anterior-view2.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Radius_-_anterior_view2.png',
  },
  'Rectus Abdominis': {
    src: '/anatomy/rectus-abdominis.png',
    author: 'Unknown',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Rectus_abdominis.png',
  },
  'Rectus Femoris': {
    src: '/anatomy/r1-rectus-femoris.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Rectus_femoris_3D.gif',
  },
  Rhomboid: {
    src: '/anatomy/rhomboidei.png',
    author: 'Mikael Häggström',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Rhomboidei.PNG',
  },
  Rotatores: {
    src: '/anatomy/rotatores.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ARotatores.png',
  },
  'Sacroiliac Joint': {
    src: '/anatomy/sacroiliac-joint.png',
    author: 'BruceBlaus. When using this image in external sources it can be cited as: Blausen.com staff (2014). "Medical gallery of Blausen Medical 2014". WikiJournal of Medicine 1 (2). DOI:10.15347/wjm/2014.010. ISSN 2002-4436.',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File%3ASacroiliac_Joint.png',
  },
  'Sacrospinous Ligament': {
    src: '/anatomy/sacrospinous-ligament.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray320.png',
    note: 'Posterior view of the right half of the pelvis; the sacrospinous ligament is labelled on the right, running from the sacrum to the ischial spine, deep to the sacrotuberous ligament.',
  },
  'Sacrotuberous Ligament': {
    src: '/anatomy/sacrotuberous-ligament.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray320.png',
    note: 'Posterior view of the right half of the pelvis; the sacrotuberous ligament is labelled at the bottom, running from the sacrum to the ischial tuberosity.',
  },
  Sacrum: {
    src: '/anatomy/sacrum.png',
    author: 'BodyParts3D is made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ASacrum_-_anterior_view04.png',
    note: 'Anterior view of the pelvis; the sacrum is highlighted in red between the two hip bones.',
  },
  Sartorius: {
    src: '/anatomy/b-sartorius.png',
    author: "Based on 'Illu lower extremity muscles' (US federal government, public domain), modified by Uwe Gille",
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Sartorius.png',
  },
  Scalene: {
    src: '/anatomy/scalene.png',
    author: 'User:Mikael Häggström',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AScalenus.png',
  },
  Scaphoid: {
    src: '/anatomy/scaphoid-bone-left-hand-01-palmar-view.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Scaphoid_bone_(left_hand)_01_palmar_view.png',
  },
  'Scapulothoracic Joint': {
    src: '/anatomy/scapulothoracic-joint.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AScapula_-_posterior_view.png',
    note: 'Posterior view of the trunk skeleton, both scapulae in red. The scapulothoracic joint is not a true joint: it is the gliding contact between the front of the scapula and the back of the rib cage, seen here overlying ribs 2-7.',
  },
  Semimembranosus: {
    src: '/anatomy/semimembranosus.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Semimembranosus.gif',
  },
  Semispinalis: {
    src: '/anatomy/semispinalis.png',
    author: 'modified by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3ASemispinalis.png',
  },
  Semitendinosus: {
    src: '/anatomy/semitendinosus.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Semitendinosus.png',
  },
  'Serratus Anterior': {
    src: '/anatomy/serratus-anterior-muscles-lateral.png',
    author: 'Anatomography (background whitened)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Serratus_anterior_muscles_lateral.png',
  },
  'Short Plantar Ligament': {
    src: '/anatomy/short-plantar-ligament.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray358.png',
    note: 'Ligaments of the sole of the right foot. The short plantar ligament is labelled on the left as the plantar calcaneocuboid ligament, the short deep band from the calcaneus to the cuboid.',
  },
  Soleus: {
    src: '/anatomy/c-soleus-posterior.png',
    author: 'Polygon data generated by Database Center for Life Science (DBCLS) / BodyParts3D, via Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Soleus_muscle_-_posterior_view.png',
  },
  Spinalis: {
    src: '/anatomy/spinalis.png',
    author: 'Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3ASpinalis.png',
  },
  'Spine of Scapula': {
    src: '/anatomy/a-spine-of-scapula02.png',
    author: 'BodyParts3D, made by DBCLS',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Spine_of_scapula02.png',
  },
  Splenius: {
    src: '/anatomy/splenius.png',
    author: 'Mikael Häggström. When using this image in external works, it may be cited as: Häggström, Mikael (2014). "Medical gallery of Mikael Häggström 2014". WikiJournal of Medicine 1 (2). DOI:10.15347/wjm/2014.008. ISSN 2002-4436. Public Domain. or By Mikael Häggström, used with permission.',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AMusculus_splenius_capitis_et_cervicis_marked.png',
  },
  'Spring Ligament': {
    src: '/anatomy/spring-ligament.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray358.png',
    note: 'Ligaments of the sole of the right foot. The spring ligament is labelled on the right as the plantar calcaneonavicular ligament, bridging the sustentaculum tali of the calcaneus to the navicular.',
  },
  'Sternoclavicular Joint': {
    src: '/anatomy/gray325.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray325.png',
  },
  Sternocleidomastoid: {
    src: '/anatomy/a-scm-anatomography.png',
    author: "Henry Vandyke Carter (Gray's Anatomy plate 385), colourised by Uwe Gille",
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Sternocleidomastoideus.png',
  },
  Sternum: {
    src: '/anatomy/sternum.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ASternum_front.png',
    note: 'Anterior view of the thorax; the sternum is highlighted in red in the midline of the chest wall.',
  },
  'Subacromial Bursa': {
    src: '/anatomy/d-subacromial-bursa.png',
    author: 'OpenStax College',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:914_Shoulder_Joint.jpg',
    note: 'Same shoulder figure as the Glenohumeral Joint page; here the subacromial bursa is the labelled structure of interest.',
  },
  'Subdeltoid Bursa': {
    src: '/anatomy/subdeltoid-bursa.png',
    author: 'Jmarchn',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File%3AShoulder_joint_back-en.svg',
    note: 'Posterior view of the right shoulder. The purple pocket labelled Bursa is the subacromial-subdeltoid bursa, lying under the acromion and deltoid and above the supraspinatus tendon.',
  },
  'Suboccipital Muscles': {
    src: '/anatomy/suboccipital-muscles.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ASuboccipital_muscles05.png',
    note: 'Posterior view. The four suboccipital muscles are colour-coded on each side: rectus capitis posterior major (blue), rectus capitis posterior minor (orange), obliquus capitis superior (green), obliquus capitis inferior (dark red).',
  },
  Subscapularis: {
    src: '/anatomy/subscapularis-muscle-frontal.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Subscapularis_muscle_frontal.png',
  },
  'Subtalar Joint': {
    src: '/anatomy/subtalar-joint.png',
    author: 'Unknown',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Subtalar_Joint.svg',
  },
  'Superior Nuchal Line': {
    src: '/anatomy/superior-nuchal-line.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3ANuchal_lines_colored.png',
    note: 'External surface of the occipital bone. The superior nuchal line is the blue line — the second from the top, running sideways from the external occipital protuberance; the pink line above it is the highest nuchal line and the green one below is the inferior nuchal line.',
  },
  Supinator: {
    src: '/anatomy/gray-musculus-supinator.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Gray_%E2%80%94_musculus_supinator.png',
  },
  'Suprapatellar Bursa': {
    src: '/anatomy/d-suprapatellar-bursa.png',
    author: 'Addingrefs',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Knee-unfolding-recess-diagram.svg',
    note: 'This image is unlabelled: the bursa is the structure picked out in red, shown unfolding as the knee flexes across the three views.',
  },
  Supraspinatus: {
    src: '/anatomy/supraspinatus-muscle-back4.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Supraspinatus_muscle_back4.png',
  },
  'Talocrural Joint': {
    src: '/anatomy/r5-talocrural-joint.png',
    author: 'BodyParts3D / DBCLS (Anatomography)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Left_Talus_bone_03_lateral_view.png',
    note: 'Lateral view of the left ankle. The talus is red; the tibia and fibula come down onto it from above, and the joint is the mortise between them. Note this is the joint ABOVE the talus - the subtalar joint lies below it, between talus and calcaneus.',
  },
  Talus: {
    src: '/anatomy/talus.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ATalus_bone_05_lateral_view.png',
    note: 'Both feet from the lateral side. The talus is red, sitting between the leg bones above and the calcaneus below.',
  },
  'Tarsal Bones': {
    src: '/anatomy/tarsal-bones.png',
    author: 'BodyParts3D is made by DBCLS.',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3ATarsal_bones01_anterior_view.png',
    note: 'The seven tarsal bones of each foot are colour-coded: talus purple, calcaneus red, navicular yellow, cuboid blue, cuneiforms green.',
  },
  'Tarsometatarsal Joint': {
    src: '/anatomy/tarsometatarsal-joint.png',
    author: 'This image is a derivative work of the following images: File:Ospied.svg licensed with Cc-by-sa-3.0-migrated, GFDL 2009-05-16T11:38:07Z Mario modesto 418x366 (94873 Bytes) Añadido los dedos 2009-05-16T11:30:30Z Mario modesto 418x366 (94142 Bytes) {{Information {{!}}Description=os du pied (tarse, métatarse, phalanges) {{!}}Source=*[[:File:Ospied.jpg|]] {{!}}Date=2009-05-16 12:26 (UTC) {{!}}Author=*[[:File:Ospied.jpg|]]: VonTasha *Ospied-de.svg derivative work: [[User:Uwe Gille|Uwe Gille]] *new derivative work: [[User:HLHJ]] {{!}}Permission=see below {{!}}other_vers',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File%3AArticulationes_tarsometatarsales-la.svg',
    note: 'Left foot, bones colour-coded. The orange band marks the tarsometatarsal (Lisfranc) joint line between the cuneiforms and cuboid and the bases of the five metatarsals. Labels are Latin.',
  },
  'Tensor Fasciae Latae': {
    src: '/anatomy/b-tensor-fasciae-latae.png',
    author: 'Henry Gray, Anatomy of the Human Body (plate Gray549), colourised by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Tensor_fasciae_latae.png',
  },
  'Teres Major': {
    src: '/anatomy/teres-major-muscle-back.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Teres_major_muscle_back.png',
  },
  'Teres Minor': {
    src: '/anatomy/teres-minor-muscle-back3.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Teres_minor_muscle_back3.png',
  },
  'Thoracolumbar Fascia': {
    src: '/anatomy/thoracolumbar-fascia.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray409.png',
    note: "Posterior view of the trunk muscles; the thoracolumbar fascia is the pale sheet in the lower back, labelled 'Lumbo Dorsal Fascia' on the right of the figure.",
  },
  Tibia: {
    src: '/anatomy/tibia-frontal-view.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Tibia_-_frontal_view.png',
  },
  'Tibialis Anterior': {
    src: '/anatomy/tibialis.png',
    author: 'Bildberabetning: sv:Användare:Chrizz. Original uploader was Chrizz at sv.wikipedia',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tibialis.png',
  },
  'Tibialis Posterior': {
    src: '/anatomy/superior-view-of-tibialis-posterior-muscle-posterior.png',
    author: 'Polygon data were generated by Database Center for Life Science (DBCLS) (background removed)',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Superior_view_of_tibialis_posterior_muscle_-_posterior.png',
    note: 'Posterior view of both lower legs. Tibialis posterior is the muscle in red, running down the back of the tibia and fibula and passing behind the medial malleolus into the foot.',
  },
  'Tibiofemoral Joint': {
    src: '/anatomy/blausen-0597-kneeanatomy-side.png',
    author: 'BruceBlaus',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Blausen_0597_KneeAnatomy_Side.png',
  },
  'Transverse Abdominis': {
    src: '/anatomy/b-transversus-abdominis.png',
    author: 'Henry Gray, Anatomy of the Human Body (plate Gray397), colourised by Uwe Gille',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Transversus_abdominis.png',
  },
  'Transverse Acetabular Ligament': {
    src: '/anatomy/transverse-acetabular-ligament.png',
    author: 'Dr. Johannes Sobotta',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3ASobo_1909_214.png',
    note: 'Right acetabulum with the femur removed; the transverse acetabular ligament is the band bridging the notch at the lower edge of the socket, labelled bottom right.',
  },
  'Transverse Humeral Ligament': {
    src: '/anatomy/transverse-humeral-ligament.png',
    author: 'Grant, John Charles Boileua',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGrant_1962_36.png',
    note: 'The shoulder from the front, joint capsule tinted blue. The transverse humeral ligament is labelled at left: the short band bridging the intertubercular groove between the greater and lesser tubercles, holding in the tendon of the long head of biceps.',
  },
  'Transverse Tarsal Joint': {
    src: '/anatomy/transverse-tarsal-joint.png',
    author: 'Henry Vandyke Carter',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3AGray268-transversetarsal.PNG',
    note: 'Right foot from above. The red line marks the transverse tarsal (Chopart) joint, running between the talus and navicular medially and the calcaneus and cuboid laterally.',
  },
  Transversospinalis: {
    src: '/anatomy/transversospinalis.jpg',
    author: 'Leo Testut',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File%3ATransversospinalis.jpg',
    note: "Lateral view of the vertebral column with only the transversospinalis group left in place: the pink muscle mass filling the gutter between the spinous and transverse processes, running from the sacrum up to the cervical spine. The group comprises semispinalis, multifidus and rotatores. C', D' and L' mark the cervical, thoracic and lumbar levels.",
  },
  Trapezius: {
    src: '/anatomy/trapezius.png',
    author: 'Unknown',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Trapezius.png',
  },
  Triceps: {
    src: '/anatomy/triceps-brachii-muscle06.png',
    author: 'BodyParts3D / DBCLS (Anatomography), background whitened',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Triceps_brachii_muscle06.png',
    note: 'Posterior view with the three heads coloured separately: long head in red, lateral head in yellow, medial head in green. Only the long head crosses the shoulder, which is why it can extend the shoulder as well as the elbow.',
  },
  'Trochanteric Bursa': {
    src: '/anatomy/d-trochanteric-bursa.png',
    author: 'Hariadhi',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Greater_trochanteric_pain_syndrome_by_Hariadhi.svg',
    note: "The bursa is the structure named on its own leader line. The red shading is labelled 'Area of pain' — it marks where trochanteric pain is felt, not the bursa itself.",
  },
  Ulna: {
    src: '/anatomy/ulna-anterior-view.png',
    author: 'Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Ulna_-_anterior_view.png',
  },
  'Vastus Intermedius': {
    src: '/anatomy/vastus-intermedius.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AVastus_intermedialis.gif',
    note: 'Anterior view. Vastus intermedius lies deep to rectus femoris; the overlying muscles are not drawn, so the red muscle shown on the front of the femoral shaft is vastus intermedius itself. (frame taken from the rotating 3D render)',
  },
  'Vastus Lateralis': {
    src: '/anatomy/vastus-lateralis.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File%3AVastus_lateralis.gif',
    note: '(frame taken from the rotating 3D render)',
  },
  'Vastus Medialis': {
    src: '/anatomy/r1-vastus-medialis.png',
    author: 'BodyParts3D/Anatomography',
    license: 'CC BY-SA 2.1 jp',
    source: 'https://commons.wikimedia.org/wiki/File:Vastus_medialis.gif',
  },
}
